#!/usr/bin/env bun
// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Appstrate

/**
 * Reference fixture builder.
 *
 * Emits a complete reproducible example under `fixtures/reference/`:
 *
 * - `bundle.afps`    — signed reference ZIP (manifest + prompt)
 * - `bundle-unsigned.afps` — same bundle without signature.sig
 * - `key.json`       — Ed25519 key pair that signed bundle.afps
 * - `trust-root.json`— trust root containing the signing key
 * - `events.json`    — scripted events driving `afps run`
 * - `context.json`   — ExecutionContext used by `afps run`
 * - `snapshot.json`  — SnapshotContextProvider input for `afps render`
 *
 * Third-party conformance runners consume these files verbatim to
 * exercise their adapter against the reference outputs. Re-run
 * `bun run scripts/build-fixtures.ts` whenever the AFPS spec or the
 * reference manifest evolves.
 *
 * Keys are regenerated each run, so the fixture file hashes change
 * between invocations — this is intentional: only the *structure* is
 * a stable contract, not specific byte sequences.
 */

import { writeFile, mkdir } from "node:fs/promises";
import { zipSync } from "fflate";
import { dirname, join } from "node:path";
import { canonicalBundleDigest, generateKeyPair, signBundle } from "../src/bundle/signing.ts";

const FIXTURE_DIR = new URL("../fixtures/reference/", import.meta.url).pathname;
const enc = (s: string): Uint8Array => new TextEncoder().encode(s);

const MANIFEST = {
  name: "@afps/conformance-ref",
  version: "1.0.0",
  type: "agent",
  schemaVersion: "1.1",
  displayName: "Conformance Reference Agent",
  author: "AFPS",
  description: "Canonical reference bundle shipped with the AFPS runtime.",
};

const PROMPT = [
  "# Reference agent",
  "",
  "Run id: `{{runId}}`",
  "Topic: **{{input.topic}}**",
  "",
  "## Prior memories",
  "{{#memories}}",
  "- {{content}}",
  "{{/memories}}",
  "{{^memories}}",
  "(no prior memories)",
  "{{/memories}}",
  "",
  "Produce a short summary about the topic.",
].join("\n");

const EVENTS = [
  { type: "log", level: "info", message: "starting reference run" },
  { type: "add_memory", content: "Reference agents are useful for contract tests." },
  { type: "set_state", state: { iteration: 1 } },
  { type: "output", data: { summary: "AFPS ships a portable runtime.", partial: true } },
  { type: "output", data: { partial: false } },
  { type: "report", content: "All checks executed." },
];

const CONTEXT = { runId: "ref_run_001", input: { topic: "AFPS conformance" } };

const SNAPSHOT = {
  memories: [
    { content: "AFPS is an open spec.", createdAt: 1_700_000_000 },
    { content: "Runtimes implement the conformance adapter.", createdAt: 1_700_000_100 },
  ],
};

async function writeJson(path: string, value: unknown): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, JSON.stringify(value, null, 2) + "\n");
}

async function main(): Promise<void> {
  await mkdir(FIXTURE_DIR, { recursive: true });

  const unsignedFiles: Record<string, Uint8Array> = {
    "manifest.json": enc(JSON.stringify(MANIFEST, null, 2) + "\n"),
    "prompt.md": enc(PROMPT),
  };
  const unsignedZip = zipSync(unsignedFiles);
  await writeFile(join(FIXTURE_DIR, "bundle-unsigned.afps"), unsignedZip);

  const key = generateKeyPair();
  const canonical = canonicalBundleDigest(unsignedFiles);
  const signature = signBundle(canonical, {
    privateKey: key.privateKey,
    keyId: key.keyId,
  });
  const signedZip = zipSync({
    ...unsignedFiles,
    "signature.sig": enc(JSON.stringify(signature, null, 2) + "\n"),
  });
  await writeFile(join(FIXTURE_DIR, "bundle.afps"), signedZip);

  await writeJson(join(FIXTURE_DIR, "key.json"), key);
  await writeJson(join(FIXTURE_DIR, "trust-root.json"), {
    keys: [
      {
        keyId: key.keyId,
        publicKey: key.publicKey,
        comment: "reference signing key — regenerated by build-fixtures.ts",
      },
    ],
  });
  await writeJson(join(FIXTURE_DIR, "events.json"), EVENTS);
  await writeJson(join(FIXTURE_DIR, "context.json"), CONTEXT);
  await writeJson(join(FIXTURE_DIR, "snapshot.json"), SNAPSHOT);

  process.stdout.write(`✓ wrote reference fixtures to ${FIXTURE_DIR}\n`);
  process.stdout.write(`  keyId: ${key.keyId}\n`);
}

await main();
