// SPDX-License-Identifier: Apache-2.0

/**
 * `appstrate skills status <dir-or-skill>` — what a working folder would push.
 * Computed on demand, like `git status`: the folder is compared to the skill's
 * draft on Appstrate, file by file, and the draft's lock is compared to the one
 * this machine last saw. No watcher, no local database: the draft IS the
 * baseline, because when the lock has not moved it is exactly what this
 * machine last pulled or pushed.
 */

import { extractSkillMeta } from "@appstrate/core/validation";
import { encodePackageIdPath, parseScopedName } from "@appstrate/core/naming";
import { apiFetch } from "../lib/api.ts";
import { resolveActiveProfile, type Profile } from "../lib/config.ts";
import { listOrgs } from "../lib/orgs.ts";
import { DEFAULT_IO, type CommandIO } from "../lib/io.ts";
import { formatError } from "../lib/ui.ts";
import { fetchSkillFiles, listSyncableSkills, resolveSkill } from "../lib/skills-sync/plan.ts";
import { resolveSpaces } from "./skills.ts";
import { readPushLocks, readSkillFolder, resolveSkillFolder } from "./skills-push.ts";

export interface SkillsStatusOptions {
  profile?: string;
  /** Folder, or a bare skill name resolved in the work dir. */
  dir: string;
  /** Print a line diff for each modified text file. */
  diff?: boolean;
}

export type ChangeKind = "modified" | "added" | "removed";

export interface FileChange {
  path: string;
  kind: ChangeKind;
}

export interface SkillStatus {
  packageId: string;
  /** No draft on Appstrate yet: every local file is an addition. */
  isNew: boolean;
  changes: FileChange[];
  /** Set when the draft's lock is not the one this machine last saw. */
  remoteMoved: { seen: number; now: number } | null;
  /** The draft manifest's `version`, when the draft exists and declares one. */
  remoteVersion: string | null;
  /** The draft's files, for diffs. Empty when `isNew`. */
  remote: Record<string, Uint8Array>;
}

/** Packaging, never content: the manifest is regenerated by push, RECORD by the server. */
const IGNORED = new Set(["manifest.json", "RECORD"]);

export async function skillsStatusCommand(
  opts: SkillsStatusOptions,
  io: CommandIO = DEFAULT_IO,
): Promise<void> {
  const { profileName, profile } = await resolveActiveProfile(opts.profile);
  if (!profile?.orgId) {
    io.stderr.write(
      profile
        ? "No organization pinned. Run: appstrate org switch\n"
        : `Profile "${profileName}" not configured. Run: appstrate login --profile ${profileName}\n`,
    );
    io.exit(1);
    return;
  }
  try {
    const dir = await resolveSkillFolder(profileName, profile, opts.dir);
    const files = await readSkillFolder(dir);
    const status = await computeStatus(profileName, profile, files);
    io.stdout.write(renderStatus(status, dir, files, opts.diff === true));
  } catch (err) {
    io.stderr.write(`${formatError(err)}\n`);
    io.exit(1);
  }
}

/** Compare a folder's files to the skill's draft. `files` is what `readSkillFolder` returned. */
export async function computeStatus(
  profileName: string,
  profile: Profile,
  files: Record<string, Uint8Array>,
  explicitId?: string,
): Promise<SkillStatus> {
  const packageId = explicitId ?? (await packageIdOf(profileName, profile, files));
  const local = Object.fromEntries(Object.entries(files).filter(([path]) => !IGNORED.has(path)));

  const spaceIds = await resolveSpaces(profileName, profile, undefined);
  const listed = (await listSyncableSkills(profileName, spaceIds)).find(
    (entry) => entry.packageId === packageId,
  );
  const draft = listed ? await resolveSkill(profileName, listed, "draft") : null;
  if (!listed || !draft) {
    return {
      packageId,
      isNew: true,
      changes: Object.keys(local)
        .sort()
        .map((path) => ({ path, kind: "added" as const })),
      remoteMoved: null,
      remoteVersion: null,
      remote: {},
    };
  }

  const remoteAll = await fetchSkillFiles(profileName, draft, "draft");
  const remote = Object.fromEntries(
    Object.entries(remoteAll).filter(([path]) => !IGNORED.has(path)),
  );
  const changes: FileChange[] = [];
  for (const path of new Set([...Object.keys(local), ...Object.keys(remote)])) {
    const mine = local[path];
    const theirs = remote[path];
    if (mine && !theirs) changes.push({ path, kind: "added" });
    else if (!mine && theirs) changes.push({ path, kind: "removed" });
    else if (mine && theirs && !sameBytes(mine, theirs)) changes.push({ path, kind: "modified" });
  }
  changes.sort((a, b) => a.path.localeCompare(b.path));

  // The lock comes from the detail, not the file index: it is the number push
  // will send, so status and push cannot disagree about "moved elsewhere".
  const detail = await apiFetch<{ lock_version?: unknown; manifest?: { version?: unknown } }>(
    profileName,
    `/api/packages/skills/${encodePackageIdPath(packageId)}`,
    { headers: { "X-Space-Id": listed.spaceId } },
  );
  const remoteVersion =
    typeof detail.manifest?.version === "string" ? detail.manifest.version : null;
  const seen = (await readPushLocks(profileName))[packageId];
  const now = typeof detail.lock_version === "number" ? detail.lock_version : undefined;
  const remoteMoved =
    seen !== undefined && now !== undefined && seen !== now ? { seen, now } : null;

  return { packageId, isNew: false, changes, remoteMoved, remoteVersion, remote };
}

export function renderStatus(
  status: SkillStatus,
  dir: string,
  local: Record<string, Uint8Array>,
  withDiff: boolean,
): string {
  const lines: string[] = [];
  lines.push(`${status.packageId} ← ${dir}`);
  if (status.isNew) {
    lines.push("  not on Appstrate yet: push creates it as a draft");
  }
  if (status.remoteMoved) {
    lines.push(
      `  ! the draft was edited elsewhere since this machine last saw it (lock ${status.remoteMoved.seen} → ${status.remoteMoved.now}); push would be refused without --force`,
    );
  }
  if (status.changes.length === 0 && !status.isNew) {
    lines.push("  clean: the folder matches the draft");
    return `${lines.join("\n")}\n`;
  }
  const glyph: Record<ChangeKind, string> = { modified: "M", added: "A", removed: "D" };
  for (const change of status.changes) lines.push(`  ${glyph[change.kind]} ${change.path}`);
  if (withDiff) {
    const decoder = new TextDecoder();
    for (const change of status.changes) {
      if (change.kind !== "modified") continue;
      const mine = local[change.path]!;
      const theirs = status.remote[change.path]!;
      if (!isText(mine) || !isText(theirs)) {
        lines.push(`--- ${change.path}: binary, ${theirs.byteLength} → ${mine.byteLength} bytes`);
        continue;
      }
      lines.push(`--- draft/${change.path}`, `+++ local/${change.path}`);
      lines.push(...lineDiff(decoder.decode(theirs).split("\n"), decoder.decode(mine).split("\n")));
    }
  }
  return `${lines.join("\n")}\n`;
}

async function packageIdOf(
  profileName: string,
  profile: Profile,
  files: Record<string, Uint8Array>,
): Promise<string> {
  const decoder = new TextDecoder();
  const manifestRaw = files["manifest.json"];
  if (manifestRaw) {
    try {
      const parsed = JSON.parse(decoder.decode(manifestRaw)) as { name?: unknown };
      if (typeof parsed.name === "string" && parseScopedName(parsed.name)) return parsed.name;
    } catch {
      // Not usable: fall back to the frontmatter.
    }
  }
  const meta = extractSkillMeta(decoder.decode(files["SKILL.md"]!));
  if (!meta.name) throw new Error("SKILL.md: frontmatter has no `name`.");
  const org = (await listOrgs(profileName)).find((o) => o.id === profile.orgId);
  if (!org) throw new Error(`Organization ${profile.orgId} is not one this profile belongs to.`);
  return `@${org.slug}/${meta.name}`;
}

function sameBytes(a: Uint8Array, b: Uint8Array): boolean {
  if (a.byteLength !== b.byteLength) return false;
  for (let i = 0; i < a.byteLength; i += 1) if (a[i] !== b[i]) return false;
  return true;
}

function isText(bytes: Uint8Array): boolean {
  const sample = bytes.subarray(0, 8000);
  for (const byte of sample) if (byte === 0) return false;
  return true;
}

/** Minimal LCS line diff — skill files are small, quadratic is fine. */
export function lineDiff(a: string[], b: string[]): string[] {
  const n = a.length;
  const m = b.length;
  const table: Uint32Array[] = [];
  for (let i = 0; i <= n; i += 1) table.push(new Uint32Array(m + 1));
  for (let i = n - 1; i >= 0; i -= 1) {
    for (let j = m - 1; j >= 0; j -= 1) {
      table[i]![j] =
        a[i] === b[j] ? table[i + 1]![j + 1]! + 1 : Math.max(table[i + 1]![j]!, table[i]![j + 1]!);
    }
  }
  const out: string[] = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (a[i] === b[j]) {
      out.push(`  ${a[i]}`);
      i += 1;
      j += 1;
    } else if (table[i + 1]![j]! >= table[i]![j + 1]!) {
      out.push(`- ${a[i]}`);
      i += 1;
    } else {
      out.push(`+ ${b[j]}`);
      j += 1;
    }
  }
  while (i < n) out.push(`- ${a[i++]}`);
  while (j < m) out.push(`+ ${b[j++]}`);
  return out;
}
