// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Appstrate

/**
 * Reference fixture round-trip — exercises the full pipeline against
 * the fixtures shipped under `fixtures/reference/` so third-party
 * conformance runners have a concrete target to reproduce.
 *
 * Fixtures are regenerated by `bun run scripts/build-fixtures.ts`;
 * signing keys rotate on every regeneration, so assertions here
 * stay structural (key *present*, signature *valid*) rather than
 * checking specific byte values.
 */

import { describe, it, expect } from "bun:test";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { loadBundleFromBuffer } from "../../src/bundle/loader.ts";
import { validateAfpsManifest } from "../../src/bundle/validator.ts";
import {
  canonicalBundleDigest,
  readBundleSignature,
  verifyBundleSignature,
  type TrustRoot,
} from "../../src/bundle/signing.ts";
import { renderPrompt } from "../../src/bundle/prompt-renderer.ts";
import { reduceEvents } from "../../src/runner/reducer.ts";
import type { EventSink } from "../../src/interfaces/event-sink.ts";
import type { RunEvent } from "../../src/types/run-event.ts";
import type {
  ExecutionContext,
  HistoryEntry,
  MemorySnapshot,
} from "../../src/types/execution-context.ts";
import type { RunResult } from "../../src/types/run-result.ts";

interface SnapshotFile {
  memories?: MemorySnapshot[];
  history?: HistoryEntry[];
  state?: unknown;
}

const FIXTURE = new URL("../../fixtures/reference/", import.meta.url).pathname;

async function readJson<T>(name: string): Promise<T> {
  return JSON.parse(await readFile(join(FIXTURE, name), "utf-8")) as T;
}

describe("fixtures/reference — end-to-end round trip", () => {
  it("loads and validates the signed bundle without issues", async () => {
    const bytes = await readFile(join(FIXTURE, "bundle.afps"));
    const bundle = loadBundleFromBuffer(bytes);
    const result = validateAfpsManifest(bundle);
    expect(result.valid).toBe(true);
    expect(result.issues).toEqual([]);
    expect(bundle.manifest["name"]).toBe("@afps/conformance-ref");
  });

  it("verifies the signature against the shipped trust-root", async () => {
    const bytes = await readFile(join(FIXTURE, "bundle.afps"));
    const bundle = loadBundleFromBuffer(bytes);
    const trustRoot = await readJson<TrustRoot>("trust-root.json");
    const signature = readBundleSignature(bundle);
    expect(signature).not.toBeNull();
    const digest = canonicalBundleDigest(bundle.files);
    const result = verifyBundleSignature(digest, signature!, trustRoot);
    expect(result.ok).toBe(true);
  });

  it("renders the prompt template with the reference context + snapshot", async () => {
    const bytes = await readFile(join(FIXTURE, "bundle.afps"));
    const bundle = loadBundleFromBuffer(bytes);
    const context = await readJson<ExecutionContext>("context.json");
    const snapshot = await readJson<SnapshotFile>("snapshot.json");
    const rendered = await renderPrompt({
      template: bundle.prompt,
      context: {
        ...context,
        ...(snapshot.memories !== undefined ? { memories: snapshot.memories } : {}),
        ...(snapshot.history !== undefined ? { history: snapshot.history } : {}),
        ...(snapshot.state !== undefined ? { state: snapshot.state } : {}),
      },
    });
    expect(rendered).toContain("Run id: `ref_run_001`");
    expect(rendered).toContain("**AFPS conformance**");
    expect(rendered).toContain("- AFPS is an open spec.");
    expect(rendered).not.toContain("(no prior memories)");
  });

  it("replays the scripted events through a sink and reduces them correctly", async () => {
    const events = await readJson<RunEvent[]>("events.json");

    const emitted: RunEvent[] = [];
    let finalized: RunResult | undefined;
    const sink: EventSink = {
      handle: async (event) => {
        emitted.push(event);
      },
      finalize: async (r) => {
        finalized = r;
      },
    };
    for (const event of events) {
      await sink.handle(event);
    }
    const result = reduceEvents(emitted);
    await sink.finalize(result);

    expect(emitted).toHaveLength(events.length);
    expect(result.memories).toHaveLength(1);
    expect(result.state).toEqual({ iteration: 1 });
    expect(result.output).toEqual({ summary: "AFPS ships a portable runtime.", partial: false });
    expect(result.report).toBe("All checks executed.");
    expect(finalized).toBeDefined();
  });

  it("rejects the unsigned bundle when --require-signature is emulated", async () => {
    const bytes = await readFile(join(FIXTURE, "bundle-unsigned.afps"));
    const bundle = loadBundleFromBuffer(bytes);
    expect(readBundleSignature(bundle)).toBeNull();
  });
});
