// SPDX-License-Identifier: Apache-2.0

import { DocsBody, DocsDescription, DocsPage, DocsTitle } from 'fumadocs-ui/page';
import defaultMdxComponents from 'fumadocs-ui/mdx';
import { Accordion, Accordions } from 'fumadocs-ui/components/accordion';
import { Step, Steps } from 'fumadocs-ui/components/steps';
import { Tab, Tabs } from 'fumadocs-ui/components/tabs';
import { MarkdownCopyButton, ViewOptionsPopover } from 'fumadocs-ui/layouts/notebook/page';
import { createAPIPage } from 'fumadocs-openapi/ui';
import { createCodeUsageGeneratorRegistry } from 'fumadocs-openapi/requests/generators';
import { curl } from 'fumadocs-openapi/requests/generators/curl';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { openapi, source } from '@/lib/source';
import { SITE_NAME, SITE_URL } from '@/lib/site';

// Cursor-style API docs:
// - No interactive playground (Send button, form inputs).
// - Only curl in the right rail: a developer can translate it to any language,
//   and without an official SDK, six language snippets would be misleading.
// - Response body schema hidden: the JSON example in the right rail is enough
//   for humans, and agents can read the OpenAPI spec directly.
const codeUsages = createCodeUsageGeneratorRegistry();
codeUsages.add('curl', curl);

const APIPage = createAPIPage(openapi, {
  playground: { enabled: false },
  codeUsages,
  showResponseSchema: false,
  generateTypeScriptDefinitions: false,
});

// The pages come from docs/site, except two kinds generated by
// scripts/sync-content.ts from another source.
const GITHUB_BLOB = 'https://github.com/appstrate/appstrate/blob/main';

function githubSourceUrl(pagePath: string): string {
  if (pagePath === 'self-hosting/environment-variables.mdx') return `${GITHUB_BLOB}/docs/ENV.md`;
  // Per-operation API pages (api/<tag>/<operationId>.mdx) come from the OpenAPI spec.
  if (/^api\/[^/]+\/[^/]+\.mdx$/.test(pagePath)) return `${GITHUB_BLOB}/apps/api/src/openapi/paths`;
  return `${GITHUB_BLOB}/docs/site/${pagePath}`;
}

type Props = { params: Promise<{ slug: string[] }> };

export async function generateMetadata(props: Props): Promise<Metadata> {
  const { slug } = await props.params;
  const page = source.getPage(slug);
  if (!page) return {};
  const title = page.data.title;
  const description = page.data.description;
  const url = `${SITE_URL}/${slug.join('/')}`;
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: { type: 'article', title, description, url, siteName: SITE_NAME, locale: 'en_US' },
    twitter: { card: 'summary', title, description },
  };
}

function capitalizeSegment(segment: string): string {
  return segment
    .split('-')
    .map((part) => (part.length > 0 ? part[0].toUpperCase() + part.slice(1) : part))
    .join(' ');
}

export default async function Page(props: Props) {
  const { slug } = await props.params;
  const page = source.getPage(slug);
  if (!page) notFound();

  const MDXContent = page.data.body;
  // Raw source of every page, written next to its HTML by scripts/postbuild.ts.
  const markdownUrl = `/${slug.join('/')}.md`;
  const githubUrl = githubSourceUrl(page.path);

  const breadcrumbItems: { name: string; url: string }[] = [{ name: 'Docs', url: SITE_URL }];
  for (let i = 0; i < slug.length; i++) {
    const segmentSlug = slug.slice(0, i + 1);
    const segmentPage = source.getPage(segmentSlug);
    breadcrumbItems.push({
      name: segmentPage?.data.title ?? capitalizeSegment(slug[i]),
      url: `${SITE_URL}/${segmentSlug.join('/')}`,
    });
  }

  const breadcrumbJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: breadcrumbItems.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <DocsPage toc={page.data.toc} full={page.data.full}>
        <DocsTitle>{page.data.title}</DocsTitle>
        <DocsDescription>{page.data.description}</DocsDescription>
        <div className="flex items-center gap-2 mt-2 pb-6 border-b border-fd-border">
          <MarkdownCopyButton markdownUrl={markdownUrl} />
          <ViewOptionsPopover markdownUrl={markdownUrl} githubUrl={githubUrl} />
        </div>
        <DocsBody>
          <MDXContent
            components={{ ...defaultMdxComponents, APIPage, Steps, Step, Tabs, Tab, Accordion, Accordions }}
          />
        </DocsBody>
      </DocsPage>
    </>
  );
}

export function generateStaticParams() {
  return source.generateParams().filter((params) => params.slug.length > 0);
}

// Static export: every page is known at build time.
export const dynamicParams = false;
