// SPDX-License-Identifier: Apache-2.0

/**
 * The fake data lab mode serves.
 *
 * Every export is declared as the type the OpenAPI spec generates for the
 * endpoint that returns it (`Json200<path, method>` below, resolved from
 * `api/schema.d.ts`, regenerated by `bun run generate:api`). That is the whole
 * guarantee of this file: when the API adds, renames or drops a field,
 * `bun run typecheck` fails HERE, so the lab cannot quietly keep showing a
 * shape the backend stopped returning.
 */
import type { paths, components } from "../api/schema";

export type Json200<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends {
  responses: { 200: { content: { "application/json": infer B } } };
}
  ? B
  : never;

export const ORG_ID = "org_lab";
export const APP_ID = "app_lab";
export const USER_ID = "user_lab";

/**
 * Clock anchor: the current hour, truncated. Screenshots stay identical across
 * reloads within the hour (so a visual diff is a real diff), while "started 2
 * minutes ago" still reads as 2 minutes to the UI, which computes elapsed time
 * against the live clock. A hard-coded date drifts and shows a live run as
 * having been going for hours.
 */
const T0 = Math.floor(Date.now() / 3_600_000) * 3_600_000;
const ago = (minutes: number) => new Date(T0 - minutes * 60_000).toISOString();

/* -------------------------------------------------------------------------- */
/* Identity                                                                    */
/* -------------------------------------------------------------------------- */

export const profile: Json200<"/api/profile", "get"> = {
  id: USER_ID,
  displayName: "Olivier Tarbès",
  language: "fr",
  email: "olivier@tractr.net",
  name: "Olivier Tarbès",
};

/** better-auth's own wire shape — it is not described by the OpenAPI spec. */
export const session = {
  session: {
    id: "sess_lab",
    userId: USER_ID,
    expiresAt: "2027-01-01T00:00:00.000Z",
    token: "lab",
    createdAt: ago(60),
    updatedAt: ago(60),
  },
  user: {
    id: USER_ID,
    email: profile.email,
    emailVerified: true,
    name: profile.name,
    image: null,
    createdAt: ago(60),
    updatedAt: ago(60),
  },
};

export const orgs: Json200<"/api/orgs", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    { id: ORG_ID, name: "Tractr", slug: "tractr", role: "owner", createdAt: ago(60) },
    { id: "org_lab_2", name: "Appstrate", slug: "appstrate", role: "admin", createdAt: ago(60) },
  ],
};

type Application = Json200<"/api/applications", "get">["data"][number];

function makeApplication(id: string, orgId: string, name: string, isDefault = false): Application {
  return {
    id,
    object: "application",
    orgId,
    name,
    isDefault,
    settings: {},
    created_by: USER_ID,
    createdAt: ago(60),
    updatedAt: ago(60),
  };
}

/**
 * Workspaces PER ORGANISATION — the switcher's second column shows the ones
 * belonging to the org being explored, so a single flat list would make it look
 * right while proving nothing. Tractr has three, Appstrate one: the asymmetry
 * is the point.
 */
export const applicationsByOrg: Record<string, Application[]> = {
  [ORG_ID]: [
    makeApplication(APP_ID, ORG_ID, "Default", true),
    makeApplication("app_lab_prod", ORG_ID, "Production"),
    makeApplication("app_lab_sandbox", ORG_ID, "Bac à sable"),
  ],
  org_lab_2: [makeApplication("app_lab_2_default", "org_lab_2", "Default", true)],
};

export const applications: Json200<"/api/applications", "get"> = {
  object: "list",
  hasMore: false,
  data: applicationsByOrg[ORG_ID]!,
};

/* -------------------------------------------------------------------------- */
/* Runs                                                                        */
/* -------------------------------------------------------------------------- */

type Run = components["schemas"]["Run"];

/**
 * Factory rather than literals: `Run` carries ~45 required fields, and spelling
 * them out per row would bury the handful that actually drive the design (name,
 * status, duration, cost, who launched it).
 */
function makeRun(over: Partial<Run> & Pick<Run, "id" | "status">): Run {
  return {
    packageId: "@tractr/compta-trimestrielle",
    userId: USER_ID,
    orgId: ORG_ID,
    input: null,
    result: null,
    artifacts: null,
    checkpoint: null,
    error: null,
    token_usage: { input_tokens: 18_420, output_tokens: 3_190 },
    started_at: ago(30),
    completed_at: ago(28),
    duration: 124_000,
    scheduleId: null,
    version_label: "1.4.0",
    version_ref: "1.4.0",
    proxy_label: null,
    model_label: "claude-opus-5",
    model_source: "org",
    cost: 0.42,
    cost_pricing_status: "priced",
    endUserId: null,
    apiKeyId: null,
    applicationId: APP_ID,
    metadata: null,
    config: null,
    config_override: null,
    generation: null,
    generation_override: null,
    user_name: "Olivier Tarbès",
    end_user_name: null,
    api_key_name: null,
    schedule_name: null,
    runner_name: null,
    runner_kind: null,
    agent_scope: "@tractr",
    agent_name: "compta-trimestrielle",
    package_ephemeral: false,
    document_counts: { input: 0, output: 2 },
    primary_document_id: null,
    unread: false,
    runNumber: 128,
    runOrigin: "platform",
    contextSnapshot: null,
    modelCredentialId: null,
    connection_overrides: null,
    dependency_overrides: null,
    connections_used: null,
    ...over,
  };
}

/**
 * Deliberately mixed: a success, a live run, a failure with a long error, a
 * scheduled run, and an agent name long enough to test truncation. A list where
 * every row looks the same validates nothing.
 */
export const runs: Run[] = [
  makeRun({
    id: "run_01",
    status: "running",
    started_at: ago(2),
    completed_at: null,
    duration: null,
    cost: null,
    cost_pricing_status: null,
    unread: true,
    runNumber: 131,
  }),
  makeRun({ id: "run_02", status: "success", runNumber: 130, started_at: ago(46) }),
  makeRun({
    id: "run_03",
    status: "failed",
    packageId: "@tractr/rq-entreprise-communications",
    agent_name: "rq-entreprise-communications",
    error:
      "Connexion clicSÉQUR refusée : le code 2FA reçu par courriel a expiré avant la soumission du formulaire (délai 90 s dépassé).",
    duration: 41_000,
    cost: 0.08,
    runNumber: 129,
    started_at: ago(180),
    completed_at: ago(179),
  }),
  makeRun({
    id: "run_04",
    status: "success",
    packageId: "@default/wiki-brain",
    agent_scope: "@default",
    agent_name: "wiki-brain",
    schedule_name: "Tous les matins à 7 h",
    scheduleId: "sch_01",
    // A scheduled run belongs to nobody: `user_name` was already null while
    // `userId` still pointed at the signed-in member, which is the one shape
    // the "Mes runs" filter reads (own runs OR unattributed ones).
    userId: null,
    user_name: null,
    duration: 312_000,
    cost: 1.17,
    runNumber: 96,
    started_at: ago(430),
    completed_at: ago(425),
  }),
  makeRun({
    id: "run_05",
    status: "cancelled",
    packageId: "@tractr/analyse-recurrence-articles-tastet",
    agent_name: "analyse-recurrence-articles-tastet",
    duration: 8_000,
    cost: 0.01,
    runNumber: 12,
    started_at: ago(1_440),
    completed_at: ago(1_439),
  }),
  // Someone else's run: without one, "Mes runs" filters nothing and proves
  // nothing.
  makeRun({
    id: "run_06",
    status: "success",
    packageId: "@default/wiki-brain",
    agent_scope: "@default",
    agent_name: "wiki-brain",
    userId: "user_lab_2",
    user_name: "Pierre",
    duration: 74_000,
    cost: 0.21,
    runNumber: 95,
    started_at: ago(520),
    completed_at: ago(519),
  }),
  // An inline run: the shadow package the chat creates for a one-off agent.
  // Same reason — the Type filter needs something to separate.
  makeRun({
    id: "run_07",
    status: "success",
    packageId: "@inline/r-8f2c41",
    agent_scope: "@inline",
    agent_name: "Relecture d'un contrat",
    package_ephemeral: true,
    duration: 21_000,
    cost: 0.05,
    runNumber: 94,
    started_at: ago(610),
    completed_at: ago(609),
  }),
];

const STATUS_CYCLE = [
  "success",
  "failed",
  "running",
  "timeout",
] as const satisfies readonly Run["status"][];

/**
 * What a run that ended badly says about it. The heavy rows used to carry no
 * error at all, so the run table's result column was 200 em-dashes and the one
 * thing volume is meant to test there — a long message truncating in a narrow
 * column — could not be looked at.
 */
const FAILURE_MESSAGES: Partial<Record<Run["status"], string>> = {
  failed:
    "TypeError: Cannot read properties of undefined (reading 'rows') at normalizeStatement (/app/src/parse.ts:114:22)",
  timeout: "Délai dépassé après 15 min : le conteneur n'a rendu aucun événement.",
};

/** 200 rows: pagination, virtualisation and scroll behaviour under real volume. */
export const heavyRuns: Run[] = Array.from({ length: 200 }, (_, i) => {
  const status = STATUS_CYCLE[i % STATUS_CYCLE.length] ?? "success";
  // Every third row belongs to someone else and every fifth is inline, so the
  // Scope and Kind filters have something to separate at volume too — with 200
  // identical rows they narrowed nothing and looked broken.
  const someoneElse = i % 3 === 1;
  const inline = i % 5 === 2;
  return makeRun({
    id: `run_h_${i}`,
    status,
    error: FAILURE_MESSAGES[status] ?? null,
    runNumber: 200 - i,
    started_at: ago(i * 17),
    completed_at: ago(i * 17 - 2),
    ...(someoneElse ? { userId: "user_lab_2", user_name: "Pierre" } : {}),
    ...(inline
      ? {
          packageId: `@inline/r-h${i}`,
          agent_scope: "@inline",
          agent_name: `Demande ponctuelle ${i}`,
          package_ephemeral: true,
        }
      : {}),
  });
});

/* -------------------------------------------------------------------------- */
/* Agents                                                                      */
/* -------------------------------------------------------------------------- */

export const agents: Json200<"/api/agents", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "@tractr/compta-trimestrielle",
      display_name: "Compta trimestrielle",
      description:
        "Pipeline de comptabilité trimestrielle : renomme les relevés BNC, extrait les transactions, concilie les factures et génère le récapitulatif Excel.",
      author: "Tractr",
      keywords: ["compta", "drive", "excel"],
      source: "local",
      scope: "@tractr",
      version: "1.4.0",
      type: "agent",
      running_runs: 1,
      dependencies: {
        skills: { "compta-references": "1.0.0" },
        integrations: { "google-drive": "2.1.0" },
      },
    },
    {
      id: "@default/wiki-brain",
      display_name: "Wiki-brain",
      description: "Mémoire proactive par personne : capte, range et rappelle ce qui compte.",
      author: "Appstrate",
      keywords: ["mémoire"],
      source: "system",
      scope: "@default",
      version: "0.3.1",
      type: "agent",
      running_runs: 0,
      dependencies: {},
    },
    {
      id: "@tractr/analyse-recurrence-articles-tastet",
      display_name: "Analyse de récurrence des articles Tastet",
      description: "Détecte le potentiel de récurrence éditoriale d'un corpus d'articles.",
      keywords: [],
      source: "local",
      scope: "@tractr",
      version: "0.1.0",
      type: "agent",
      running_runs: 0,
      dependencies: {},
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Secondary reads the shell issues on every screen                            */
/* -------------------------------------------------------------------------- */

type Schedule = Json200<"/api/schedules", "get">["data"][number];

function makeSchedule(over: Partial<Schedule> & Pick<Schedule, "id" | "packageId">): Schedule {
  return {
    userId: USER_ID,
    endUserId: null,
    orgId: ORG_ID,
    applicationId: APP_ID,
    name: null,
    enabled: true,
    cron_expression: "0 7 * * *",
    timezone: "America/Toronto",
    input: null,
    config_override: null,
    generation_config_override: null,
    model_id_override: null,
    proxy_id_override: null,
    version_override: null,
    connection_overrides: null,
    dependency_overrides: null,
    last_run_at: ago(430),
    next_run_at: ago(-1_000),
    createdAt: ago(20_000),
    updatedAt: ago(430),
    actor_name: "Olivier Tarbès",
    actor_type: "user",
    running_runs: 0,
    unread_count: 0,
    last_run_number: 0,
    ...over,
  };
}

/**
 * 200 agents, the same volume as `heavyRuns`, because a card grid is the one
 * collection nobody has ever seen carry a real catalogue: it is not
 * virtualised, and how many columns it takes is its whole question. Built off
 * the real three so the cards keep believable names, descriptions of different
 * lengths and a mix of states — a grid of 200 identical cards proves the
 * scroll and nothing else.
 */
export const heavyAgents: (typeof agents)["data"] = Array.from({ length: 200 }, (_, i) => {
  const base = agents.data[i % agents.data.length]!;
  return {
    ...base,
    id: `${base.id}-${i + 1}`,
    display_name: `${base.display_name} ${i + 1}`,
    running_runs: i % 7 === 0 ? 1 : 0,
  };
});

export const schedules: Json200<"/api/schedules", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    makeSchedule({
      id: "sch_01",
      packageId: "@default/wiki-brain",
      name: "Tous les matins à 7 h",
      last_run_number: 96,
    }),
    makeSchedule({
      id: "sch_02",
      packageId: "@tractr/compta-trimestrielle",
      name: "Récap de fin de trimestre",
      cron_expression: "0 9 1 */3 *",
      last_run_at: ago(4_300),
      next_run_at: ago(-40_000),
      last_run_number: 128,
      unread_count: 3,
      running_runs: 1,
    }),
    // Paused: the database still holds a `next_run_at`, which is exactly the
    // row that catches a table promising a run that is not coming.
    makeSchedule({
      id: "sch_03",
      packageId: "@tractr/analyse-recurrence-articles-tastet",
      name: "Veille hebdomadaire",
      cron_expression: "30 6 * * 1",
      enabled: false,
      last_run_at: ago(11_000),
      next_run_at: ago(-3_000),
      last_run_number: 11,
    }),
    // Never fired, and run by someone else.
    makeSchedule({
      id: "sch_04",
      packageId: "@default/wiki-brain",
      name: "Rappel du vendredi",
      cron_expression: "0 16 * * 5",
      userId: "user_lab_2",
      actor_name: "Pierre",
      last_run_at: null,
      next_run_at: ago(-20_000),
    }),
  ],
};

export const chatSessions: Json200<"/api/chat/sessions", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      object: "chat_session",
      id: "chat_01",
      title: "Refonte de la page Runs",
      generating: false,
      unread: false,
      createdAt: ago(90),
      updatedAt: ago(35),
    },
  ],
};

type ChatSession = (typeof chatSessions)["data"][number];

/**
 * A long history — what the conversation list in the shell sidebar has to hold
 * without pushing the new-conversation row or the meta block off screen. 200
 * rows, the same volume as the other heavy fixtures, and the list is NOT
 * virtualised. Titles of very different lengths on purpose: truncation and the
 * fixed-width right slot (timestamp / unread dot / spinner) are what break
 * first.
 */
export const heavyChatSessions: ChatSession[] = Array.from({ length: 200 }, (_, i) => ({
  object: "chat_session",
  id: `chat_h_${i}`,
  title:
    i % 5 === 0
      ? `Conversation ${i + 1} — un titre assez long pour être coupé dans la barre latérale`
      : `Conversation ${i + 1}`,
  generating: i === 1,
  unread: i % 7 === 3,
  createdAt: ago(i * 90 + 120),
  updatedAt: ago(i * 90),
}));

/**
 * One conversation with actual turns. `GET /api/chat/sessions/:id` is outside
 * the OpenAPI surface (the chat module serves it), so this mirrors what
 * `loadHistory` reads by hand: rows of `{ id, content }` where `content` is an
 * ai-sdk UIMessage minus its id.
 *
 * Without it the lab only ever shows an EMPTY thread — the one screen the chat
 * is actually about could not be looked at.
 */
export const chatHistory = {
  messages: [
    {
      id: "msg_01",
      content: {
        role: "user",
        parts: [{ type: "text", text: "Où en est la refonte de la page Runs ?" }],
      },
    },
    {
      id: "msg_02",
      content: {
        role: "assistant",
        parts: [
          {
            type: "text",
            text: "La page Runs est passée au nouveau cadre gris : les lignes sont des cartes blanches, le filtre reste collé en haut.\n\nIl reste deux choses :\n\n1. la colonne de coût, qui déborde sous 1200 px ;\n2. le badge « en cours », encore sur l’ancienne teinte.",
          },
        ],
      },
    },
    {
      id: "msg_03",
      content: {
        role: "user",
        parts: [{ type: "text", text: "Montre-moi le dernier run échoué." }],
      },
    },
    {
      id: "msg_04",
      content: {
        role: "assistant",
        parts: [
          {
            type: "text",
            text: "Le run #199 (Compta trimestrielle) a échoué hier à 21:43 après 124 s : le relevé de mars manquait dans le dossier Drive du trimestre.",
          },
        ],
      },
    },
  ],
};

export const notifications: Json200<"/api/notifications", "get"> = {
  has_more: false,
  data: [
    {
      id: "ntf_01",
      type: "run.completed",
      run_id: "run_02",
      payload: { status: "success" },
      read_at: null,
      created_at: ago(46),
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Billing                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * `/api/billing` is served by the cloud module, not the OpenAPI surface, so it
 * has no generated type to bind to — this one mirrors `hooks/use-billing`'s
 * `BillingInfo` by hand. Deliberately at 68%: a gauge is only worth looking at
 * somewhere between empty and full.
 */
export const billing = {
  plan: "pro",
  plans: [{ id: "pro", name: "Pro", price: 49, credit_quota: 50_000 }],
  usage_percent: 68,
  credits_used: 34_120,
  credit_quota: 50_000,
  period_end: new Date(T0 + 11 * 24 * 3_600_000).toISOString(),
  status: "active",
  upgrades: [],
};

/* -------------------------------------------------------------------------- */
/* Skills and MCP servers — the two lists the guard found unserved             */
/* -------------------------------------------------------------------------- */

/**
 * These two screens were believed to be showing an EMPTY list in every
 * scenario — the doc said so — and they were showing a failed request: neither
 * endpoint had a handler, so `/api/packages/skills` and
 * `/api/packages/mcp-servers` both 404'd and the screens rendered their error
 * state. Nobody noticed, because "no rows" and "the request died" look alike
 * from across the room. `e2e/lab/shots.mjs` is what caught it, by listening for
 * `[lab] no fixture` rather than by looking.
 */
export const skills: Json200<"/api/packages/skills", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "@tractr/compta-references",
      name: "compta-references",
      description:
        "Références et scripts de la comptabilité Tractr : année fiscale, règles d'extraction BNC, mapping des marchands.",
      source: "local",
      created_by: USER_ID,
      created_by_name: "Olivier Tarbès",
      used_by_agents: 2,
      version: "1.4.0",
      auto_installed: false,
      forked_from: null,
      createdAt: ago(120_000),
      updatedAt: ago(3_000),
    },
    {
      id: "@default/triage-sentiment",
      name: "triage-sentiment",
      description: "Classe un message entrant par intention et par urgence, puis le route.",
      source: "system",
      orgId: null,
      created_by: null,
      used_by_agents: 1,
      version: "0.3.1",
      auto_installed: true,
      forked_from: null,
      createdAt: ago(200_000),
      updatedAt: ago(90_000),
    },
    {
      id: "@tractr/wiki-brain-method",
      name: "wiki-brain-method",
      description: "Mémoire proactive par personne : quoi retenir, quand le rappeler.",
      source: "local",
      created_by: USER_ID,
      created_by_name: "Olivier Tarbès",
      used_by_agents: 0,
      version: "0.9.0",
      auto_installed: false,
      forked_from: "@default/triage-sentiment",
      createdAt: ago(40_000),
      updatedAt: ago(1_500),
    },
  ],
};

export const mcpServers: Json200<"/api/packages/mcp-servers", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "@appstrate/gdrive-mcp",
      name: "gdrive-mcp",
      description: "Serveur MCP Google Drive : recherche, lecture, dépôt de fichiers.",
      source: "system",
      orgId: null,
      created_by: null,
      used_by_agents: 3,
      version: "2.1.0",
      auto_installed: true,
      forked_from: null,
      createdAt: ago(200_000),
      updatedAt: ago(60_000),
    },
    {
      id: "@tractr/qbo-mcp",
      name: "qbo-mcp",
      description: "QuickBooks Online, lecture seule : 69 outils comptables.",
      source: "local",
      created_by: USER_ID,
      created_by_name: "Olivier Tarbès",
      used_by_agents: 1,
      version: "1.0.0",
      auto_installed: false,
      forked_from: null,
      createdAt: ago(30_000),
      updatedAt: ago(800),
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Documents                                                                   */
/* -------------------------------------------------------------------------- */

type LabDocument = Json200<"/api/documents", "get">["data"][number];

/** Everything a tile can draw: an image, a spreadsheet, a PDF, and an upload. */
const documentRows: LabDocument[] = [
  {
    object: "document",
    id: "doc_lab_1",
    uri: "document://doc_lab_1",
    purpose: "agent_output",
    presentation: "primary",
    applicationId: APP_ID,
    run_id: "run_01",
    chat_session_id: null,
    packageId: "@tractr/compta-trimestrielle",
    name: "recapitulatif-2026-Q2.xlsx",
    mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 184_320,
    sha256: "9f2c4d1a8b7e6f5c4d3b2a1908f7e6d5c4b3a2918f7e6d5c4b3a29180f7e6d5c",
    downloadable: true,
    capabilities: {
      visible: true,
      metadata: true,
      download: true,
      preview: false,
      keep: true,
      delete: true,
    },
    previewable: false,
    preview_kind: null,
    expiresAt: ago(-60_000),
    createdAt: ago(2_400),
  },
  {
    object: "document",
    id: "doc_lab_2",
    uri: "document://doc_lab_2",
    purpose: "agent_output",
    presentation: null,
    applicationId: APP_ID,
    run_id: "run_01",
    chat_session_id: null,
    packageId: "@tractr/compta-trimestrielle",
    name: "releve-mastercard-juin.pdf",
    mime: "application/pdf",
    size: 512_000,
    sha256: "1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6e7f809",
    downloadable: true,
    capabilities: {
      visible: true,
      metadata: true,
      download: true,
      preview: true,
      keep: true,
      delete: true,
    },
    previewable: true,
    preview_kind: "pdf",
    expiresAt: null,
    createdAt: ago(2_600),
  },
  {
    object: "document",
    id: "doc_lab_3",
    uri: "document://doc_lab_3",
    purpose: "user_upload",
    presentation: null,
    applicationId: APP_ID,
    run_id: null,
    chat_session_id: null,
    packageId: null,
    name: "logo-tractr.png",
    mime: "image/png",
    size: 24_576,
    sha256: "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    downloadable: true,
    capabilities: {
      visible: true,
      metadata: true,
      download: true,
      preview: true,
      keep: true,
      delete: true,
    },
    previewable: true,
    preview_kind: "image",
    expiresAt: ago(-4_000),
    createdAt: ago(9_000),
  },
  {
    // A document the caller may see but not read: the metadata capability is
    // off, so the name and mime degrade the way the API degrades them. It is
    // the one row that proves the tile does not assume it may show everything.
    object: "document",
    id: "doc_lab_4",
    uri: "document://doc_lab_4",
    purpose: "user_upload",
    presentation: null,
    applicationId: APP_ID,
    run_id: "run_03",
    chat_session_id: null,
    packageId: null,
    name: "document",
    mime: "application/octet-stream",
    size: 71_680,
    downloadable: false,
    capabilities: {
      visible: true,
      metadata: false,
      download: false,
      preview: false,
      keep: false,
      delete: false,
    },
    previewable: false,
    preview_kind: null,
    expiresAt: null,
    createdAt: ago(15_000),
  },
];

export const documents: Json200<"/api/documents", "get"> = {
  object: "list",
  data: documentRows,
  hasMore: false,
  limit: 25,
};

/**
 * The bytes a thumbnail is made of: a 64×64 flat-blue PNG, base64.
 *
 * Small enough to sit in the source, real enough to decode — the tile fetches
 * the content as a BLOB and makes an object URL of it, so a JSON stand-in
 * silently becomes a placeholder and the gallery reads as broken.
 */
const THUMBNAIL_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAT0lEQVR42u3PQQkAAAgEsCtjMuNbwgi+hcEKLNXzWgQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQELguYZjFanhwbHAAAAABJRU5ErkJggg==";

export function thumbnailPng(): Uint8Array {
  const binary = atob(THUMBNAIL_PNG_BASE64);
  return Uint8Array.from(binary, (c) => c.charCodeAt(0));
}

/** Enough to make the gallery's "load more" reachable. */
export const heavyDocuments: LabDocument[] = Array.from({ length: 60 }, (_, i) => {
  const base = documentRows[i % documentRows.length]!;
  return { ...base, id: `doc_lab_h${i + 1}`, name: `${i + 1}-${base.name}` };
});

/* -------------------------------------------------------------------------- */
/* Agent detail, run detail, and agent memory                                  */
/* -------------------------------------------------------------------------- */

/**
 * The agent behind the runs, so its detail page can be looked at.
 *
 * It is here for the two tabs that host a compact list and could not be reached
 * at all before: Connexions (which reads `dependencies.integrations` and then
 * asks the integration endpoints, already fixtured) and Mémoire.
 */
export const agentDetail: Json200<"/api/packages/agents/{scope}/{name}", "get"> = {
  id: "@tractr/compta-trimestrielle",
  display_name: "Compta trimestrielle",
  description:
    "Pipeline de comptabilité trimestrielle : renomme les relevés BNC, extrait les transactions, concilie les factures et génère le récapitulatif Excel.",
  source: "local",
  scope: "@tractr",
  version: "1.4.0",
  updatedAt: ago(3_000),
  lock_version: 12,
  config: { schema: {}, current: {} },
  dependencies: {
    skills: [{ id: "@tractr/compta-references", version: "1.4.0" }],
    mcp_servers: [{ id: "@appstrate/gdrive-mcp", version: "2.1.0" }],
    integrations: [
      { id: "@appstrate/google-drive", version: "2.1.0", tools: ["drive_search", "drive_upload"] },
    ],
  },
  last_run: { id: "run_01", status: "running", started_at: ago(2), duration: null },
  running_runs: 1,
  version_count: 6,
  forked_from: null,
  has_unarchived_changes: true,
  effective_timeout_seconds: 1_800,
};

/** A handful of log lines, so a run detail is not an empty console. */
export const runLogs: Json200<"/api/runs/{id}/logs", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: 1,
      runId: "run_01",
      type: "system",
      level: "info",
      event: "run.started",
      message: "Démarrage du conteneur d'exécution.",
      createdAt: ago(2),
    },
    {
      id: 2,
      runId: "run_01",
      type: "agent",
      level: "info",
      event: "tool.call",
      message: "drive_search : 42 relevés trouvés dans finances/2026-Q2.",
      createdAt: ago(2),
    },
    {
      id: 3,
      runId: "run_01",
      type: "agent",
      level: "warn",
      event: "tool.call",
      message: "Deux marchands sans mapping : SQ *TIM HORTONS, AMZN MKTP CA.",
      createdAt: ago(1),
    },
  ],
};

type Persistence = Json200<"/api/agents/{scope}/{name}/persistence", "get">;

/**
 * The agent's memory, which is the surface this fixture mainly exists for: the
 * panel had no fixture, so it could only ever be seen empty, and it draws
 * neither a loading nor an error state — meaning a failed request has always
 * read as "there is nothing here". Both tiers are represented, because the
 * panel's whole shape is pinned slots above archive memories.
 */
export const agentPersistence: Persistence = {
  pinned: [
    {
      id: 1,
      key: "persona",
      content:
        "Comptable méthodique. Ne devine jamais un montant : si une pièce manque, le signaler plutôt que d'estimer.",
      runId: null,
      actor_type: "shared",
      actor_id: null,
      createdAt: ago(120_000),
      updatedAt: ago(40_000),
    },
    {
      id: 2,
      key: "checkpoint",
      content: {
        trimestre: "2026-Q2",
        etape: "conciliation",
        releves_traites: 42,
        factures_en_attente: 3,
      },
      runId: "run_01",
      actor_type: "user",
      actor_id: USER_ID,
      createdAt: ago(2),
      updatedAt: ago(1),
    },
  ],
  memories: [
    {
      id: 11,
      content:
        "Les relevés Mastercard de mai 2026 arrivent avec deux jours de retard chez BNC : ne pas conclure à une pièce manquante avant le 5 du mois.",
      runId: "run_02",
      actor_type: "shared",
      actor_id: null,
      createdAt: ago(46),
    },
    {
      id: 12,
      content:
        "SQ *TIM HORTONS se classe en « Repas et représentation », pas en « Fournitures de bureau ». Corrigé à la main deux trimestres de suite.",
      runId: "run_02",
      actor_type: "user",
      actor_id: USER_ID,
      createdAt: ago(2_800),
    },
    {
      id: 13,
      content:
        "L'année fiscale Tractr va du 1er septembre au 31 août : un trimestre nommé Q2 couvre décembre à février, jamais avril à juin.",
      runId: null,
      actor_type: "shared",
      actor_id: null,
      createdAt: ago(90_000),
    },
  ],
};

/**
 * What the agent's Connexions tab reads: which connection each declared
 * integration would actually use, and why.
 *
 * The picker's whole subject is the CASCADE (admin pin > enforced org default >
 * member pin > the only candidate), so a fixture with one healthy candidate
 * proves nothing. Two candidates here, one of them another member's shared
 * connection, with the status left at `must_choose` — the state that makes the
 * picker draw a choice rather than a fait accompli.
 */
export const agentConnectionReadiness: Json200<
  "/api/agents/{scope}/{name}/connection-readiness",
  "get"
> = {
  blocks_run: false,
  errors: [],
  integrations: [
    {
      integration_id: "@appstrate/google-drive",
      run_blocking: false,
      resolution: {
        status: "must_choose",
        resolved_connection_id: null,
        resolved_missing_scopes: [],
        resolved_owned_by_actor: false,
        admin_pinned_connection_id: null,
        member_pinned_connection_id: null,
        org_default_connection_id: null,
        org_default_enforced: false,
        can_add_connection: true,
        candidates: [
          {
            id: "conn_lab_1",
            auth_key: "drive",
            account_id: "108453099102",
            label: "olivier@tractr.net",
            owner_user_id: USER_ID,
            owner_end_user_id: null,
            owner_name: "Olivier Tarbès",
            scopes_granted: [
              "https://www.googleapis.com/auth/drive.readonly",
              "https://www.googleapis.com/auth/drive.file",
            ],
            shared_with_org: true,
            needs_reconnection: false,
            missing_scopes: [],
            is_own: true,
          },
          {
            id: "conn_lab_3",
            auth_key: "drive",
            account_id: "119003471228",
            label: "compta@tractr.net",
            owner_user_id: "user_lab_2",
            owner_end_user_id: null,
            owner_name: "Pierre",
            scopes_granted: ["https://www.googleapis.com/auth/drive"],
            shared_with_org: true,
            needs_reconnection: false,
            // Under-scoped on purpose: the amber warning under a candidate is a
            // state of this picker that nothing else in the lab reaches.
            missing_scopes: ["https://www.googleapis.com/auth/drive.file"],
            is_own: false,
          },
        ],
      },
    },
  ],
};

/** Latest published version + the draft the editor is on. */
export const agentVersionInfo: Json200<"/api/packages/agents/{scope}/{name}/versions/info", "get"> =
  {
    latest_published_version: "1.4.0",
    active_version: "1.4.0",
  };

/** The version the selector resolves `latest` to. */
export const agentLatestVersion: components["schemas"]["PackageVersionDetail"] = {
  id: 6,
  version: "1.4.0",
  manifest: { name: "@tractr/compta-trimestrielle", version: "1.4.0", type: "agent" },
  yanked: false,
  yanked_reason: null,
  integrity: "sha256-3f9a1c8e7d6b5a4938271605f4e3d2c1b0a9f8e7d6c5b4a3928170f6e5d4c3b2",
  artifact_size: 48_120,
  createdAt: ago(3_000),
  dist_tags: ["latest"],
};

/** The agent's model override: none, so the org default decides. */
export const agentModel: Json200<"/api/agents/{scope}/{name}/model", "get"> = {
  modelId: null,
  generation: null,
};

/* -------------------------------------------------------------------------- */
/* The settings lists                                                          */
/* -------------------------------------------------------------------------- */

/**
 * The provider catalogue the model picker reads. Two entries, no `models`
 * catalogue: this fixture exists so the picker can be OPENED, and the per
 * provider model list is the heavy half of the real payload.
 */
export const providerRegistry: Json200<"/api/model-provider-credentials/registry", "get"> = {
  object: "list",
  total: 2,
  hasMore: false,
  data: [
    {
      providerId: "anthropic",
      displayName: "Anthropic",
      apiShape: "anthropic-messages",
      defaultBaseUrl: "https://api.anthropic.com",
      baseUrlOverridable: false,
      authMode: "api_key",
      featured: true,
    },
    {
      providerId: "openai-compatible",
      displayName: "OpenAI-compatible",
      description: "Tout serveur exposant l'API OpenAI : vLLM, Ollama, LM Studio.",
      apiShape: "openai-completions",
      defaultBaseUrl: "http://localhost:11434/v1",
      baseUrlOverridable: true,
      authMode: "api_key",
      featured: false,
    },
  ],
};

/** Webhooks, one per level, one switched off. */
export const webhooks: Json200<"/api/webhooks", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "wh_lab_1",
      object: "webhook",
      level: "application",
      applicationId: APP_ID,
      url: "https://tractr.net/hooks/appstrate/runs",
      events: ["run.succeeded", "run.failed"],
      packageId: "@tractr/compta-trimestrielle",
      payloadMode: "full",
      enabled: true,
      createdAt: ago(90_000),
      updatedAt: ago(4_000),
    },
    {
      id: "wh_lab_2",
      object: "webhook",
      level: "org",
      applicationId: null,
      url: "https://hooks.slack.com/services/T0000/B0000/xxxxxxxxxxxx",
      events: ["run.failed"],
      packageId: null,
      payloadMode: "summary",
      enabled: false,
      createdAt: ago(150_000),
      updatedAt: ago(20_000),
    },
  ],
};

/** End-users of the workspace: one named, one known only by its external id. */
export const endUsers: Json200<"/api/end-users", "get"> = {
  object: "list",
  hasMore: false,
  limit: 25,
  data: [
    {
      id: "eu_lab_1",
      object: "end_user",
      applicationId: APP_ID,
      name: "Marie Lavoie",
      email: "marie@client-a.example",
      externalId: "crm-40129",
      metadata: { plan: "pro" },
      createdAt: ago(60_000),
      updatedAt: ago(1_200),
    },
    {
      id: "eu_lab_2",
      object: "end_user",
      applicationId: APP_ID,
      name: null,
      email: null,
      externalId: "crm-40877",
      metadata: null,
      createdAt: ago(8_000),
      updatedAt: ago(8_000),
    },
  ],
};

/** CLI sessions, admin view: two members, one of them this browser's own. */
export const cliSessions: Json200<"/api/orgs/{orgId}/cli-sessions", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      familyId: "cli_lab_1",
      userId: USER_ID,
      userEmail: "olivier@tractr.net",
      userName: "Olivier Tarbès",
      deviceName: "MacBook Pro",
      userAgent: "appstrate-cli/2.4.0 (darwin arm64)",
      createdIp: "24.201.44.10",
      lastUsedIp: "24.201.44.10",
      lastUsedAt: ago(120),
      createdAt: ago(40_000),
      expiresAt: ago(-200_000),
      current: true,
    },
    {
      familyId: "cli_lab_2",
      userId: "user_lab_2",
      userEmail: "pierre@tractr.net",
      userName: "Pierre",
      deviceName: null,
      userAgent: "appstrate-cli/2.3.1 (linux x64)",
      createdIp: "142.113.9.201",
      lastUsedIp: "142.113.9.201",
      lastUsedAt: ago(5_000),
      createdAt: ago(80_000),
      expiresAt: ago(-100_000),
      current: false,
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Organisation detail                                                         */
/* -------------------------------------------------------------------------- */

export const orgDetail: Json200<"/api/orgs/{orgId}", "get"> = {
  id: ORG_ID,
  name: "Tractr",
  slug: "tractr",
  createdAt: ago(200_000),
  storage: { used_bytes: 2_411_724_800, limit_bytes: null, effective_limit_bytes: null },
  members: [
    {
      userId: USER_ID,
      displayName: "Olivier Tarbès",
      email: "olivier@tractr.net",
      role: "owner",
      joinedAt: ago(200_000),
    },
    {
      userId: "user_lab_2",
      displayName: "Pierre",
      email: "pierre@tractr.net",
      role: "admin",
      joinedAt: ago(90_000),
    },
    {
      userId: "user_lab_3",
      displayName: "Camille",
      email: "camille@tractr.net",
      role: "member",
      joinedAt: ago(12_000),
    },
  ],
  invitations: [],
};

export const orgSettings: Json200<"/api/orgs/{orgId}/settings", "get"> = {
  api_version: "2026-08-01",
  dashboard_sso_enabled: false,
};

/**
 * The integration catalogue, so the one list that is still cards-only can be
 * looked at at all. Six of them because the grid's whole question is how many
 * columns it takes and what happens on the last row; two inactive, since the
 * page opens on the "Activées" tab and a tab that filters nothing proves
 * nothing.
 */
export const integrations: Json200<"/api/integrations", "get"> = {
  object: "list",
  total: 6,
  hasMore: false,
  data: [
    {
      id: "@appstrate/google-drive",
      orgId: "org_tractr",
      source: "system",
      active: true,
      manifest: {
        display_name: "Google Drive",
        description:
          "Lire, écrire et organiser les fichiers d'un Drive : documents, tableurs, dossiers partagés.",
        version: "2.1.0",
        keywords: ["drive", "fichiers", "google"],
      },
    },
    {
      id: "@appstrate/gmail",
      orgId: "org_tractr",
      source: "system",
      active: true,
      manifest: {
        display_name: "Gmail",
        description: "Chercher, lire et envoyer des courriels au nom de l'employé connecté.",
        version: "1.8.2",
        keywords: ["courriel", "google"],
      },
    },
    {
      id: "@appstrate/clickup",
      orgId: "org_tractr",
      source: "local",
      active: true,
      manifest: {
        display_name: "ClickUp",
        description: "Tâches, listes et suivi du temps.",
        version: "0.9.0",
        keywords: ["tâches", "temps"],
      },
    },
    {
      id: "@tractr/qbo-mcp",
      orgId: "org_tractr",
      source: "local",
      active: true,
      manifest: {
        display_name: "QuickBooks Online",
        description:
          "Comptabilité : factures, dépenses, comptes à recevoir. Lecture seule, 69 outils.",
        version: "1.0.0",
      },
    },
    {
      id: "@appstrate/slack",
      orgId: "org_tractr",
      source: "system",
      active: false,
      manifest: {
        display_name: "Slack",
        description: "Messages et canaux.",
        version: "1.2.0",
      },
    },
    {
      id: "@appstrate/notion",
      orgId: "org_tractr",
      source: "system",
      active: false,
      manifest: { display_name: "Notion", description: "Pages et bases.", version: "3.0.1" },
    },
  ],
};

/**
 * The same catalogue at the size a real org reaches.
 *
 * The FIRST row keeps its real id: the detail page reads its activation state
 * out of this list, so a catalogue where every id is suffixed made
 * `/integrations/@appstrate/google-drive` say "not activated" under `heavy` and
 * the tables the scenario exists to load were never drawn at all.
 */
export const heavyIntegrations: (typeof integrations)["data"] = Array.from(
  { length: 60 },
  (_, i) => {
    const base = integrations.data[i % integrations.data.length]!;
    return { ...base, id: i === 0 ? base.id : `${base.id}-${i + 1}`, active: true };
  },
);

/* -------------------------------------------------------------------------- */
/* Integration detail — the two tables the Connexions and Configuration tabs   */
/* draw                                                                        */
/* -------------------------------------------------------------------------- */

/** The integration the detail fixtures are about — the catalogue's first row. */
export const INTEGRATION_ID = "@appstrate/google-drive";

/** The auth the accounts and the OAuth clients hang off — named once, read by
 *  every handler that has to answer "which auth is this?". */
export const INTEGRATION_AUTH_KEY = "drive";

type IntegrationDetail = Json200<"/api/integrations/{packageId}", "get">;
type IntegrationAuth = IntegrationDetail["auths"][number];
type Connection = IntegrationAuth["connections"][number];

/**
 * Connected accounts for the oauth2 auth.
 *
 * Three, because every control on that row is gated on something and one
 * happy account proves none of them: a healthy one the signed-in user owns
 * (rename, share, disconnect all live), one of theirs that needs
 * reconnecting (the renew CTA, and an expiry in the past), and one shared by
 * ANOTHER member — whose row must show the owner badge and no owner-only
 * control at all, since the API answers 403 for each of them.
 */
const driveConnections: Connection[] = [
  {
    id: "conn_lab_1",
    packageId: INTEGRATION_ID,
    auth_key: "drive",
    account_id: "108453099102",
    identity_claims: { email: "olivier@tractr.net" },
    scopes_granted: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
    ],
    needs_reconnection: false,
    expiresAt: ago(-40_000),
    owner_type: "user",
    owner_id: USER_ID,
    owner_name: "Olivier Tarbès",
    label: "olivier@tractr.net",
    shared_with_org: true,
    client_ref: "cli_lab_custom",
    createdAt: ago(60_000),
    updatedAt: ago(400),
  },
  {
    id: "conn_lab_2",
    packageId: INTEGRATION_ID,
    auth_key: "drive",
    account_id: "114820071553",
    identity_claims: { email: "olivier@appstrate.com" },
    scopes_granted: ["https://www.googleapis.com/auth/drive.readonly"],
    needs_reconnection: true,
    expiresAt: ago(2_800),
    owner_type: "user",
    owner_id: USER_ID,
    owner_name: "Olivier Tarbès",
    label: "olivier@appstrate.com",
    shared_with_org: false,
    client_ref: "cli_lab_custom",
    createdAt: ago(50_000),
    updatedAt: ago(2_800),
  },
  {
    id: "conn_lab_3",
    packageId: INTEGRATION_ID,
    auth_key: "drive",
    account_id: "119003471228",
    identity_claims: { email: "compta@tractr.net" },
    scopes_granted: [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
    ],
    needs_reconnection: false,
    expiresAt: ago(-20_000),
    owner_type: "user",
    owner_id: "user_lab_2",
    owner_name: "Pierre",
    label: "compta@tractr.net",
    shared_with_org: true,
    client_ref: "cli_lab_custom",
    createdAt: ago(30_000),
    updatedAt: ago(1_200),
  },
];

/**
 * The integration detail.
 *
 * THREE auths on purpose, because the states are per-auth and one happy auth
 * shows none of them: `drive` (oauth2) carries the accounts and the clients;
 * `mcp` is a remote-MCP auth whose client is auto-provisioned, which is the
 * only way to reach the clients table's EMPTY state and the hint that explains
 * it; `service_account` is a `custom` auth with nothing connected, which shows
 * the connections table's empty state and the Configuration tab's "this auth
 * has no OAuth client" line. None of the three was visible while the screen had
 * no fixture at all.
 */
export const integrationDetail: IntegrationDetail = {
  manifest: {
    display_name: "Google Drive",
    description:
      "Lire, écrire et organiser les fichiers d'un Drive : documents, tableurs, dossiers partagés.",
    version: "2.1.0",
    author: "Appstrate",
    license: "Apache-2.0",
    // The DECLARED auths, keyed like the manifest. The Configuration tab reads
    // this map and skips any auth missing from it, so without these two the
    // whole tab renders as the access-rules row alone.
    auths: {
      drive: {
        type: "oauth2",
        authorized_uris: [
          "https://www.googleapis.com/drive/v3",
          "https://www.googleapis.com/upload/drive/v3",
          "https://oauth2.googleapis.com/token",
          "https://www.googleapis.com/oauth2/v3/userinfo",
        ],
      },
      mcp: { type: "oauth2", authorized_uris: ["https://mcp.googleapis.com"] },
      service_account: { type: "custom", authorized_uris: ["https://www.googleapis.com"] },
    },
  },
  auths: [
    {
      auth_key: "drive",
      type: "oauth2",
      required: true,
      scopes: [
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/drive.file",
      ],
      resource: "https://www.googleapis.com/",
      connections: driveConnections,
      ready: true,
      has_oauth_client: true,
      has_system_client: true,
      client_auto_provisioned: false,
    },
    {
      // A remote MCP auth: no client is registered and none has to be — the
      // server mints one at connect time (DCR/CIMD). It is here because it is
      // the only way to look at the clients table's EMPTY state, at the hint
      // that explains it, and at the manual escape hatch under it.
      auth_key: "mcp",
      type: "oauth2",
      required: false,
      scopes: ["mcp:tools"],
      resource: "https://mcp.googleapis.com/",
      connections: [],
      ready: false,
      has_oauth_client: false,
      has_system_client: false,
      client_auto_provisioned: true,
    },
    {
      auth_key: "service_account",
      type: "custom",
      required: false,
      scopes: [],
      resource: null,
      connections: [],
      ready: false,
      has_oauth_client: false,
      has_system_client: false,
      client_auto_provisioned: false,
    },
  ],
  tool_catalog: [
    { name: "drive_search", description: "Chercher des fichiers par nom, type ou contenu." },
    { name: "drive_read_file", description: "Lire le contenu d'un fichier." },
    { name: "drive_upload", description: "Déposer un fichier dans un dossier." },
  ],
  allow_undeclared_tools: false,
  active: true,
  block_user_connections: false,
  platform_redirect_uri: "https://app.appstrate.com/api/integrations/oauth/callback",
};

/** The same auth with a dozen accounts — what a shared workspace reaches. */
export const heavyIntegrationConnections: Connection[] = Array.from({ length: 12 }, (_, i) => {
  const base = driveConnections[i % driveConnections.length]!;
  return {
    ...base,
    id: `conn_lab_h${i + 1}`,
    label: `equipe-${i + 1}@tractr.net`,
    account_id: `1084530991${i}`,
  };
});

/**
 * The OAuth clients of the `drive` auth. Three, for the same reason: a system
 * client nobody may edit or delete, the org's own client which is the default,
 * and a second custom one — without which the "définir par défaut" control has
 * no row to appear on.
 */
export const integrationClients: Json200<
  "/api/integrations/{packageId}/auths/{authKey}/clients",
  "get"
> = {
  object: "list",
  hasMore: false,
  data: [
    {
      client_ref: "sys_a91f2c",
      source: "built-in",
      client_id: "sys_a91f2c4d",
      is_default: false,
      auto_provisioned: false,
      has_client_secret: true,
      token_endpoint_auth_method: "client_secret_post",
      redirect_uri: null,
    },
    {
      client_ref: "cli_lab_custom",
      source: "custom",
      client_id: "884012773901-h9v2c1k8s0m4.apps.googleusercontent.com",
      is_default: true,
      auto_provisioned: false,
      has_client_secret: true,
      token_endpoint_auth_method: "client_secret_post",
      redirect_uri: null,
    },
    {
      client_ref: "cli_lab_second",
      source: "custom",
      client_id: "884012773901-p3t7d5j1a2f6.apps.googleusercontent.com",
      is_default: false,
      auto_provisioned: false,
      has_client_secret: false,
      token_endpoint_auth_method: "none",
      redirect_uri: "https://tractr.appstrate.com/api/integrations/oauth/callback",
    },
  ],
};

/** The package row behind the integration — the header's source and version. */
export const integrationPackage: components["schemas"]["OrgPackageItemDetail"] = {
  id: INTEGRATION_ID,
  orgId: null,
  name: "google-drive",
  description: "Lire, écrire et organiser les fichiers d'un Drive.",
  content: "# Google Drive\n\nIntégration système.\n",
  source: "system",
  created_by: null,
  auto_installed: true,
  version: "2.1.0",
  forked_from: null,
  agents: [{ id: "@tractr/compta-trimestrielle", display_name: "Compta trimestrielle" }],
  createdAt: ago(200_000),
  updatedAt: ago(4_000),
};

/** The agents that consume the integration — the pin section's left column. */
export const integrationConsumingAgents: Json200<
  "/api/integrations/{packageId}/consuming-agents",
  "get"
> = {
  object: "list",
  hasMore: false,
  data: [
    { packageId: "@tractr/compta-trimestrielle", display_name: "Compta trimestrielle" },
    { packageId: "@tractr/wiki-brain", display_name: "Wiki-brain" },
  ],
};

/**
 * Proxies, so the settings table can be looked at. Three of them because the
 * column set is only interesting with a mix: a built-in that cannot be edited
 * or deleted, one that is the org default, and one that is switched off.
 */
export const proxies: Json200<"/api/proxies", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "prx_builtin",
      label: "Sortie directe",
      urlPrefix: "https://egress.appstrate.internal",
      source: "built-in",
      enabled: true,
      is_default: false,
      created_by: null,
      createdAt: "2026-06-01T09:00:00.000Z",
      updatedAt: "2026-06-01T09:00:00.000Z",
    },
    {
      id: "prx_eu",
      label: "Sortie Europe",
      urlPrefix: "https://eu-proxy.tractr.net:8443",
      source: "custom",
      enabled: true,
      is_default: true,
      created_by: "Olivier Tarbès",
      createdAt: "2026-07-14T11:20:00.000Z",
      updatedAt: "2026-08-02T16:05:00.000Z",
    },
    {
      id: "prx_lab",
      label: "Bac à sable",
      urlPrefix: "http://localhost:8888",
      source: "custom",
      enabled: false,
      is_default: false,
      created_by: "Pierre",
      createdAt: "2026-08-11T08:40:00.000Z",
      updatedAt: "2026-08-11T08:40:00.000Z",
    },
  ],
};

/** Models, so both settings tables can be looked at rather than inferred. */
export const models: Json200<"/api/models", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "mdl_sonnet",
      label: "Claude Sonnet 5",
      modelId: "claude-sonnet-5",
      apiShape: "anthropic",
      baseUrl: null,
      iconUrl: null,
      providerId: "anthropic",
      providerName: "Anthropic",
      generation: null,
      credentialId: "cred_builtin",
      created_by: null,
      source: "built-in",
      enabled: true,
      is_default: true,
      aliased: false,
      needs_reconnection: false,
      createdAt: "2026-05-02T10:00:00.000Z",
      updatedAt: "2026-05-02T10:00:00.000Z",
    },
    {
      id: "mdl_opus",
      label: "Claude Opus 5",
      modelId: "claude-opus-5",
      apiShape: "anthropic",
      baseUrl: null,
      iconUrl: null,
      providerId: "anthropic",
      providerName: "Anthropic",
      generation: null,
      credentialId: "cred_openai",
      created_by: "Olivier Tarbès",
      source: "custom",
      enabled: true,
      is_default: false,
      aliased: false,
      needs_reconnection: false,
      createdAt: "2026-06-18T14:30:00.000Z",
      updatedAt: "2026-06-18T14:30:00.000Z",
    },
    {
      id: "mdl_local",
      label: "Mistral local",
      modelId: "mistral-small",
      apiShape: "openai-compatible",
      baseUrl: "http://localhost:11434/v1",
      iconUrl: null,
      providerId: null,
      providerName: null,
      generation: null,
      credentialId: null,
      created_by: "Pierre",
      source: "custom",
      enabled: false,
      is_default: false,
      aliased: false,
      // The row the "shown but disabled" default control exists for.
      needs_reconnection: true,
      createdAt: "2026-07-30T08:15:00.000Z",
      updatedAt: "2026-08-14T09:00:00.000Z",
    },
  ],
};

/** Provider credentials: one built-in, one API key, one OAuth to reconnect. */
export const modelCredentials: Json200<"/api/model-provider-credentials", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "cred_builtin",
      label: "Anthropic (plateforme)",
      apiShape: "anthropic",
      baseUrl: null,
      source: "built-in",
      authMode: "api_key",
      providerId: null,
      oauth_email: null,
      needs_reconnection: false,
      created_by: null,
      createdAt: "2026-05-02T10:00:00.000Z",
      updatedAt: "2026-05-02T10:00:00.000Z",
    },
    {
      id: "cred_openai",
      label: "OpenAI — clé Tractr",
      apiShape: "openai",
      baseUrl: null,
      source: "custom",
      authMode: "api_key",
      providerId: null,
      oauth_email: null,
      needs_reconnection: false,
      created_by: "Olivier Tarbès",
      createdAt: "2026-06-11T16:45:00.000Z",
      updatedAt: "2026-06-11T16:45:00.000Z",
    },
    {
      id: "cred_oauth",
      label: "Claude Code",
      apiShape: "anthropic",
      baseUrl: null,
      source: "custom",
      authMode: "oauth2",
      providerId: "claude-code",
      oauth_email: "olivier@tractr.net",
      needs_reconnection: true,
      created_by: "Olivier Tarbès",
      createdAt: "2026-08-01T11:00:00.000Z",
      updatedAt: "2026-08-19T07:20:00.000Z",
    },
  ],
};

/**
 * The library matrix: packages down, workspaces across. Three workspaces
 * because the whole question of a matrix is how many columns it grows, and a
 * mix of installed and not so the checkboxes are not all in one state. The
 * system row is there for the locked case (agents and skills treat a system
 * package as globally available; integrations do not).
 */
export const library: Json200<"/api/library", "get"> = {
  object: "library",
  applications: [
    { id: "app_default", name: "Default", isDefault: true },
    { id: "app_compta", name: "Comptabilité", isDefault: false },
    { id: "app_veille", name: "Veille", isDefault: false },
  ],
  packages: {
    agent: [
      {
        type: "agent" as const,
        id: "@tractr/compta-trimestrielle",
        name: "Compta trimestrielle",
        description: "Pipeline de comptabilité trimestrielle.",
        source: "local",
        installed_in: ["app_default", "app_compta"],
      },
      {
        type: "agent" as const,
        id: "@tractr/wiki-brain",
        name: "Wiki-brain",
        description: "Mémoire proactive par personne.",
        source: "system",
        installed_in: ["app_default"],
      },
      {
        type: "agent" as const,
        id: "@tractr/analyse-recurrence",
        name: "Analyse de récurrence des articles Tastet",
        description: "Détecte le potentiel de récurrence éditoriale.",
        source: "local",
        installed_in: ["app_veille"],
      },
    ],
    skill: [
      {
        type: "skill" as const,
        id: "@tractr/compta-references",
        name: "compta-references",
        description: "Références et scripts pour la comptabilité Tractr.",
        source: "local",
        installed_in: ["app_compta"],
      },
    ],
    integration: [
      {
        type: "integration" as const,
        id: "@appstrate/google-drive",
        name: "Google Drive",
        description: "Fichiers, documents et dossiers partagés.",
        source: "system",
        installed_in: ["app_default", "app_compta", "app_veille"],
      },
      {
        type: "integration" as const,
        id: "@appstrate/gmail",
        name: "Gmail",
        description: "Courriels au nom de l'employé connecté.",
        source: "system",
        installed_in: [],
      },
    ],
    // The library page has three tabs; MCP servers are in the response shape
    // but not on screen, so the group is present and empty.
    "mcp-server": [],
  },
};
