// SPDX-License-Identifier: Apache-2.0

/**
 * The fake data lab mode serves.
 *
 * Every export is declared as the type the OpenAPI spec generates for the
 * endpoint that returns it (`Json200<path, method>` below, resolved from
 * `api/schema.d.ts`, regenerated by `bun run generate:api`). That is the whole
 * guarantee of this file: when the API adds, renames or drops a field,
 * `bun run typecheck` fails HERE, so the lab cannot quietly keep showing a
 * shape the backend stopped returning.
 */
import type { paths, components } from "../api/schema";

export type Json200<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends {
  responses: { 200: { content: { "application/json": infer B } } };
}
  ? B
  : never;

export const ORG_ID = "org_lab";
export const APP_ID = "app_lab";
export const USER_ID = "user_lab";

/**
 * Clock anchor: the current hour, truncated. Screenshots stay identical across
 * reloads within the hour (so a visual diff is a real diff), while "started 2
 * minutes ago" still reads as 2 minutes to the UI, which computes elapsed time
 * against the live clock. A hard-coded date drifts and shows a live run as
 * having been going for hours.
 */
const T0 = Math.floor(Date.now() / 3_600_000) * 3_600_000;
const ago = (minutes: number) => new Date(T0 - minutes * 60_000).toISOString();

/* -------------------------------------------------------------------------- */
/* Identity                                                                    */
/* -------------------------------------------------------------------------- */

export const profile: Json200<"/api/profile", "get"> = {
  id: USER_ID,
  displayName: "Olivier Tarbès",
  language: "fr",
  email: "olivier@tractr.net",
  name: "Olivier Tarbès",
};

/** better-auth's own wire shape — it is not described by the OpenAPI spec. */
export const session = {
  session: {
    id: "sess_lab",
    userId: USER_ID,
    expiresAt: "2027-01-01T00:00:00.000Z",
    token: "lab",
    createdAt: ago(60),
    updatedAt: ago(60),
  },
  user: {
    id: USER_ID,
    email: profile.email,
    emailVerified: true,
    name: profile.name,
    image: null,
    createdAt: ago(60),
    updatedAt: ago(60),
  },
};

export const orgs: Json200<"/api/orgs", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    { id: ORG_ID, name: "Tractr", slug: "tractr", role: "owner", createdAt: ago(60) },
    { id: "org_lab_2", name: "Appstrate", slug: "appstrate", role: "admin", createdAt: ago(60) },
  ],
};

type Application = Json200<"/api/applications", "get">["data"][number];

function makeApplication(id: string, orgId: string, name: string, isDefault = false): Application {
  return {
    id,
    object: "application",
    orgId,
    name,
    isDefault,
    settings: {},
    created_by: USER_ID,
    createdAt: ago(60),
    updatedAt: ago(60),
  };
}

/**
 * Workspaces PER ORGANISATION — the switcher's second column shows the ones
 * belonging to the org being explored, so a single flat list would make it look
 * right while proving nothing. Tractr has three, Appstrate one: the asymmetry
 * is the point.
 */
export const applicationsByOrg: Record<string, Application[]> = {
  [ORG_ID]: [
    makeApplication(APP_ID, ORG_ID, "Default", true),
    makeApplication("app_lab_prod", ORG_ID, "Production"),
    makeApplication("app_lab_sandbox", ORG_ID, "Bac à sable"),
  ],
  org_lab_2: [makeApplication("app_lab_2_default", "org_lab_2", "Default", true)],
};

export const applications: Json200<"/api/applications", "get"> = {
  object: "list",
  hasMore: false,
  data: applicationsByOrg[ORG_ID]!,
};

/* -------------------------------------------------------------------------- */
/* Runs                                                                        */
/* -------------------------------------------------------------------------- */

type Run = components["schemas"]["Run"];

/**
 * Factory rather than literals: `Run` carries ~45 required fields, and spelling
 * them out per row would bury the handful that actually drive the design (name,
 * status, duration, cost, who launched it).
 */
function makeRun(over: Partial<Run> & Pick<Run, "id" | "status">): Run {
  return {
    packageId: "@tractr/compta-trimestrielle",
    userId: USER_ID,
    orgId: ORG_ID,
    input: null,
    result: null,
    artifacts: null,
    checkpoint: null,
    error: null,
    token_usage: { input_tokens: 18_420, output_tokens: 3_190 },
    started_at: ago(30),
    completed_at: ago(28),
    duration: 124_000,
    scheduleId: null,
    version_label: "1.4.0",
    version_ref: "1.4.0",
    proxy_label: null,
    model_label: "claude-opus-5",
    model_source: "org",
    cost: 0.42,
    cost_pricing_status: "priced",
    endUserId: null,
    apiKeyId: null,
    applicationId: APP_ID,
    metadata: null,
    config: null,
    config_override: null,
    generation: null,
    generation_override: null,
    user_name: "Olivier Tarbès",
    end_user_name: null,
    api_key_name: null,
    schedule_name: null,
    runner_name: null,
    runner_kind: null,
    agent_scope: "@tractr",
    agent_name: "compta-trimestrielle",
    package_ephemeral: false,
    document_counts: { input: 0, output: 2 },
    primary_document_id: null,
    unread: false,
    runNumber: 128,
    runOrigin: "platform",
    contextSnapshot: null,
    modelCredentialId: null,
    connection_overrides: null,
    dependency_overrides: null,
    connections_used: null,
    ...over,
  };
}

/**
 * Deliberately mixed: a success, a live run, a failure with a long error, a
 * scheduled run, and an agent name long enough to test truncation. A list where
 * every row looks the same validates nothing.
 */
export const runs: Run[] = [
  makeRun({
    id: "run_01",
    status: "running",
    started_at: ago(2),
    completed_at: null,
    duration: null,
    cost: null,
    cost_pricing_status: null,
    unread: true,
    runNumber: 131,
  }),
  makeRun({ id: "run_02", status: "success", runNumber: 130, started_at: ago(46) }),
  makeRun({
    id: "run_03",
    status: "failed",
    packageId: "@tractr/rq-entreprise-communications",
    agent_name: "rq-entreprise-communications",
    error:
      "Connexion clicSÉQUR refusée : le code 2FA reçu par courriel a expiré avant la soumission du formulaire (délai 90 s dépassé).",
    duration: 41_000,
    cost: 0.08,
    runNumber: 129,
    started_at: ago(180),
    completed_at: ago(179),
  }),
  makeRun({
    id: "run_04",
    status: "success",
    packageId: "@default/wiki-brain",
    agent_scope: "@default",
    agent_name: "wiki-brain",
    schedule_name: "Tous les matins à 7 h",
    scheduleId: "sch_01",
    user_name: null,
    duration: 312_000,
    cost: 1.17,
    runNumber: 96,
    started_at: ago(430),
    completed_at: ago(425),
  }),
  makeRun({
    id: "run_05",
    status: "cancelled",
    packageId: "@tractr/analyse-recurrence-articles-tastet",
    agent_name: "analyse-recurrence-articles-tastet",
    duration: 8_000,
    cost: 0.01,
    runNumber: 12,
    started_at: ago(1_440),
    completed_at: ago(1_439),
  }),
];

const STATUS_CYCLE = [
  "success",
  "failed",
  "running",
  "timeout",
] as const satisfies readonly Run["status"][];

/** 200 rows: pagination, virtualisation and scroll behaviour under real volume. */
export const heavyRuns: Run[] = Array.from({ length: 200 }, (_, i) =>
  makeRun({
    id: `run_h_${i}`,
    status: STATUS_CYCLE[i % STATUS_CYCLE.length] ?? "success",
    runNumber: 200 - i,
    started_at: ago(i * 17),
    completed_at: ago(i * 17 - 2),
  }),
);

/* -------------------------------------------------------------------------- */
/* Agents                                                                      */
/* -------------------------------------------------------------------------- */

export const agents: Json200<"/api/agents", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "@tractr/compta-trimestrielle",
      display_name: "Compta trimestrielle",
      description:
        "Pipeline de comptabilité trimestrielle : renomme les relevés BNC, extrait les transactions, concilie les factures et génère le récapitulatif Excel.",
      author: "Tractr",
      keywords: ["compta", "drive", "excel"],
      source: "local",
      scope: "@tractr",
      version: "1.4.0",
      type: "agent",
      running_runs: 1,
      dependencies: {
        skills: { "compta-references": "1.0.0" },
        integrations: { "google-drive": "2.1.0" },
      },
    },
    {
      id: "@default/wiki-brain",
      display_name: "Wiki-brain",
      description: "Mémoire proactive par personne : capte, range et rappelle ce qui compte.",
      author: "Appstrate",
      keywords: ["mémoire"],
      source: "system",
      scope: "@default",
      version: "0.3.1",
      type: "agent",
      running_runs: 0,
      dependencies: {},
    },
    {
      id: "@tractr/analyse-recurrence-articles-tastet",
      display_name: "Analyse de récurrence des articles Tastet",
      description: "Détecte le potentiel de récurrence éditoriale d'un corpus d'articles.",
      keywords: [],
      source: "local",
      scope: "@tractr",
      version: "0.1.0",
      type: "agent",
      running_runs: 0,
      dependencies: {},
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Secondary reads the shell issues on every screen                            */
/* -------------------------------------------------------------------------- */

export const schedules: Json200<"/api/schedules", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      id: "sch_01",
      packageId: "@default/wiki-brain",
      userId: USER_ID,
      endUserId: null,
      orgId: ORG_ID,
      applicationId: APP_ID,
      name: "Tous les matins à 7 h",
      enabled: true,
      cron_expression: "0 7 * * *",
      timezone: "America/Toronto",
      input: null,
      config_override: null,
      generation_config_override: null,
      model_id_override: null,
      proxy_id_override: null,
      version_override: null,
      connection_overrides: null,
      dependency_overrides: null,
      last_run_at: ago(430),
      next_run_at: ago(-1_000),
      createdAt: ago(20_000),
      updatedAt: ago(430),
      actor_name: "Olivier Tarbès",
      actor_type: "user",
      running_runs: 0,
      unread_count: 0,
      last_run_number: 96,
    },
  ],
};

export const chatSessions: Json200<"/api/chat/sessions", "get"> = {
  object: "list",
  hasMore: false,
  data: [
    {
      object: "chat_session",
      id: "chat_01",
      title: "Refonte de la page Runs",
      generating: false,
      unread: false,
      createdAt: ago(90),
      updatedAt: ago(35),
    },
  ],
};

type ChatSession = (typeof chatSessions)["data"][number];

/**
 * A long history — what the conversation list in the shell sidebar has to hold
 * without pushing the new-conversation row or the meta block off screen. 200
 * rows, the same volume as the other heavy fixtures, and the list is NOT
 * virtualised. Titles of very different lengths on purpose: truncation and the
 * fixed-width right slot (timestamp / unread dot / spinner) are what break
 * first.
 */
export const heavyChatSessions: ChatSession[] = Array.from({ length: 200 }, (_, i) => ({
  object: "chat_session",
  id: `chat_h_${i}`,
  title:
    i % 5 === 0
      ? `Conversation ${i + 1} — un titre assez long pour être coupé dans la barre latérale`
      : `Conversation ${i + 1}`,
  generating: i === 1,
  unread: i % 7 === 3,
  createdAt: ago(i * 90 + 120),
  updatedAt: ago(i * 90),
}));

/**
 * One conversation with actual turns. `GET /api/chat/sessions/:id` is outside
 * the OpenAPI surface (the chat module serves it), so this mirrors what
 * `loadHistory` reads by hand: rows of `{ id, content }` where `content` is an
 * ai-sdk UIMessage minus its id.
 *
 * Without it the lab only ever shows an EMPTY thread — the one screen the chat
 * is actually about could not be looked at.
 */
export const chatHistory = {
  messages: [
    {
      id: "msg_01",
      content: {
        role: "user",
        parts: [{ type: "text", text: "Où en est la refonte de la page Runs ?" }],
      },
    },
    {
      id: "msg_02",
      content: {
        role: "assistant",
        parts: [
          {
            type: "text",
            text: "La page Runs est passée au nouveau cadre gris : les lignes sont des cartes blanches, le filtre reste collé en haut.\n\nIl reste deux choses :\n\n1. la colonne de coût, qui déborde sous 1200 px ;\n2. le badge « en cours », encore sur l’ancienne teinte.",
          },
        ],
      },
    },
    {
      id: "msg_03",
      content: {
        role: "user",
        parts: [{ type: "text", text: "Montre-moi le dernier run échoué." }],
      },
    },
    {
      id: "msg_04",
      content: {
        role: "assistant",
        parts: [
          {
            type: "text",
            text: "Le run #199 (Compta trimestrielle) a échoué hier à 21:43 après 124 s : le relevé de mars manquait dans le dossier Drive du trimestre.",
          },
        ],
      },
    },
  ],
};

export const notifications: Json200<"/api/notifications", "get"> = {
  has_more: false,
  data: [
    {
      id: "ntf_01",
      type: "run.completed",
      run_id: "run_02",
      payload: { status: "success" },
      read_at: null,
      created_at: ago(46),
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Billing                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * `/api/billing` is served by the cloud module, not the OpenAPI surface, so it
 * has no generated type to bind to — this one mirrors `hooks/use-billing`'s
 * `BillingInfo` by hand. Deliberately at 68%: a gauge is only worth looking at
 * somewhere between empty and full.
 */
export const billing = {
  plan: "pro",
  plans: [{ id: "pro", name: "Pro", price: 49, credit_quota: 50_000 }],
  usage_percent: 68,
  credits_used: 34_120,
  credit_quota: 50_000,
  period_end: new Date(T0 + 11 * 24 * 3_600_000).toISOString(),
  status: "active",
  upgrades: [],
};

/* -------------------------------------------------------------------------- */
/* Organisation detail                                                         */
/* -------------------------------------------------------------------------- */

export const orgDetail: Json200<"/api/orgs/{orgId}", "get"> = {
  id: ORG_ID,
  name: "Tractr",
  slug: "tractr",
  createdAt: ago(200_000),
  storage: { used_bytes: 2_411_724_800, limit_bytes: null, effective_limit_bytes: null },
  members: [
    {
      userId: USER_ID,
      displayName: "Olivier Tarbès",
      email: "olivier@tractr.net",
      role: "owner",
      joinedAt: ago(200_000),
    },
    {
      userId: "user_lab_2",
      displayName: "Pierre",
      email: "pierre@tractr.net",
      role: "admin",
      joinedAt: ago(90_000),
    },
    {
      userId: "user_lab_3",
      displayName: "Camille",
      email: "camille@tractr.net",
      role: "member",
      joinedAt: ago(12_000),
    },
  ],
  invitations: [],
};

export const orgSettings: Json200<"/api/orgs/{orgId}/settings", "get"> = {
  api_version: "2026-08-01",
  dashboard_sso_enabled: false,
};
