// SPDX-License-Identifier: Apache-2.0

/**
 * Where synced skills land, and how they get there without a torn state.
 *
 * Three destinations, two shapes:
 *
 *  - `claude-plugin` writes a whole Claude Code plugin under
 *    `<dataDir>/claude-plugin/`. The directory is ours end to end — nothing
 *    else writes there — so the swap replaces the entire tree at once. That
 *    matters more here than anywhere else: a `source: "command"` plugin's
 *    version is the hash of its contents, so a background run killed midway
 *    through a per-file write would leave a half-plugin that Claude Code
 *    happily hashes and installs.
 *  - `codex` (`~/.agents/skills/`) and `claude-user` (`~/.claude/skills/`) are
 *    SHARED with the user's own hand-written skills. The whole-tree swap is
 *    not available there; each skill directory is swapped individually and
 *    nothing outside the sync's own ledger is ever removed.
 *
 * Staging happens under a single dot-prefixed directory
 * (`.appstrate-staging/`, inside a shared root and beside the plugin root)
 * rather than as a bare sibling of each destination. Both Codex and Claude Code enumerate `<root>/*` for skill
 * directories, so an in-flight `.appstrate-sync-…/SKILL.md` sitting directly
 * in `~/.agents/skills/` would be a scannable half-skill for the length of the
 * build; one dot-prefixed parent keeps every temporary path out of that
 * enumeration. It stays inside the root so `rename` is same-filesystem and
 * therefore atomic, and it is removed in a `finally`.
 */

import {
  cp,
  lstat,
  mkdir,
  readdir,
  readFile,
  rename,
  rm,
  rmdir,
  writeFile,
} from "node:fs/promises";
import { dirname, join } from "node:path";
import { getDataDir, homeDir } from "../config.ts";

export const SYNC_TARGETS = ["claude-plugin", "codex", "claude-user"] as const;
export type SyncTarget = (typeof SYNC_TARGETS)[number];

/**
 * Dot-prefixed staging area. Inside a shared target root for `codex` and
 * `claude-user`; beside the plugin root for `claude-plugin`, which is itself
 * the directory being swapped. Dot-prefixed so neither Codex nor Claude Code
 * enumerates it as a skill directory.
 */
const STAGING_DIR = ".appstrate-staging";

/** Claude Code plugin name — skills are invoked as `/appstrate:<slug>`. */
const PLUGIN_NAME = "appstrate";

/**
 * The plugin manifest carries a `name` and nothing that moves.
 *
 * No `version`: for a `command` source the content hash is the version, and a
 * field that changed per sync would make every run look like an upgrade. No
 * org name either — it would rewrite the manifest (and so the hash, and so the
 * plugin version) on an org rename that changed no skill.
 */
const PLUGIN_MANIFEST = {
  name: PLUGIN_NAME,
  description: "Skills from your Appstrate organization, kept in sync by `appstrate skills sync`.",
};

/**
 * Deliberately does NOT promise that every sync rewrites every skill: a skill
 * whose artifact has not changed is carried over from the previous tree, so a
 * hand-edit inside it survives until that skill is next refreshed. Promising
 * otherwise would be the more comforting sentence and the false one.
 */
const PLUGIN_README = `# Appstrate skills

This directory is generated by \`appstrate skills sync\` from the skills
installed in the space pinned on your Appstrate CLI profile.

**Do not edit it.** Any sync that refreshes a skill overwrites it, and edits
are never synced back. Edit the skill in Appstrate and publish a new version
instead.

Skills appear in Claude Code as \`/${PLUGIN_NAME}:<skill>\`.
`;

/**
 * Every fixed file of the plugin, by path relative to its root.
 *
 * One definition for the writer AND the up-to-date check. Kept apart, the
 * check only ever looked at `skills/` — so a deleted `README.md`, a tampered
 * `plugin.json`, or a CLI upgrade that changed either of them survived every
 * subsequent sync untouched, while the README promised each run rebuilds the
 * tree.
 */
const PLUGIN_FILES: Readonly<Record<string, string>> = {
  ".claude-plugin/plugin.json": `${JSON.stringify(PLUGIN_MANIFEST, null, 2)}\n`,
  "README.md": PLUGIN_README,
};

/** Top-level entries a complete plugin root holds — and nothing else. */
const PLUGIN_ROOT_ENTRIES = [".claude-plugin", "README.md", "skills"];

/**
 * Absolute root each target writes into.
 *
 * `homeDir()` is the SAME helper `getDataDir()` uses, so the ledger under
 * `<dataDir>/skills-sync/` and the directories it claims can never disagree
 * about where home is.
 */
export function targetRoot(target: SyncTarget): string {
  switch (target) {
    case "claude-plugin":
      return join(getDataDir(), "claude-plugin");
    case "codex":
      return join(homeDir(), ".agents", "skills");
    case "claude-user":
      return join(homeDir(), ".claude", "skills");
  }
}

/** Directory holding one slug's `SKILL.md`, for any target. */
export function skillDir(target: SyncTarget, slug: string): string {
  const root = targetRoot(target);
  return target === "claude-plugin" ? join(root, "skills", slug) : join(root, slug);
}

/** One materialized skill: its directory name and the files inside it. */
export interface SkillTree {
  slug: string;
  files: Record<string, Uint8Array>;
}

/** One skill that could not be placed into the plugin tree. */
export interface SkillWriteFailure {
  slug: string;
  error: unknown;
}

/**
 * Rebuild the whole `claude-plugin` tree and swap it into place.
 *
 * `carryOver` names the slugs whose bytes did not change and are copied from
 * the current tree instead of being re-downloaded — the plugin has to be
 * rebuilt in full to be swapped in full, but that is no reason to re-fetch
 * artifacts whose integrity already matched.
 *
 * Each skill directory is built in its OWN try, and the failures are returned
 * rather than thrown: one malformed artifact (entries `a` and `a/b` cannot
 * both exist) used to abort the whole build, so the run produced no plugin at
 * all, every session, until that one skill was fixed server-side. Only the
 * final swap is allowed to fail the run.
 */
export async function writePluginTree(
  fresh: SkillTree[],
  carryOver: string[],
  root: string,
): Promise<SkillWriteFailure[]> {
  const failures: SkillWriteFailure[] = [];
  // Same shape as the shared roots: a dot-prefixed `.appstrate-staging/` next
  // to what is being swapped. It cannot live INSIDE the plugin root, because
  // the plugin root is the directory being replaced.
  await withStaging(root, join(dirname(root), STAGING_DIR), async (staging) => {
    for (const [path, contents] of Object.entries(PLUGIN_FILES)) {
      const dest = join(staging, path);
      await mkdir(dirname(dest), { recursive: true });
      await writeFile(dest, contents);
    }
    await mkdir(join(staging, "skills"), { recursive: true });
    for (const slug of [...carryOver].sort()) {
      try {
        await cp(join(root, "skills", slug), join(staging, "skills", slug), {
          recursive: true,
          dereference: false,
        });
      } catch (error) {
        failures.push({ slug, error });
      }
    }
    for (const tree of [...fresh].sort((a, b) => a.slug.localeCompare(b.slug))) {
      try {
        await writeTreeInto(join(staging, "skills", tree.slug), tree.files);
      } catch (error) {
        // Leave nothing half-written behind: the slug is reported as failed,
        // so the tree must not carry a partial copy of it.
        await rm(join(staging, "skills", tree.slug), { recursive: true, force: true });
        failures.push({ slug: tree.slug, error });
      }
    }
  });
  return failures;
}

/**
 * Whether the plugin root is already exactly what a rebuild would produce.
 *
 * Compares the fixed files BY CONTENT and the top-level entry set, not just
 * their presence: an upgrade that changes `plugin.json` or the README must
 * reach a tree whose skills all happen to be up to date, and a stray file
 * somebody dropped in must not survive forever.
 */
export async function pluginTreeMatches(root: string, expectedSlugs: string[]): Promise<boolean> {
  if (!(await entriesMatch(root, PLUGIN_ROOT_ENTRIES))) return false;
  for (const [path, contents] of Object.entries(PLUGIN_FILES)) {
    let actual: string;
    try {
      actual = await readFile(join(root, path), "utf-8");
    } catch {
      return false;
    }
    if (actual !== contents) return false;
  }
  return entriesMatch(join(root, "skills"), expectedSlugs);
}

async function entriesMatch(dir: string, expected: string[]): Promise<boolean> {
  let present: string[];
  try {
    present = (await readdir(dir)).sort();
  } catch {
    return false;
  }
  const want = [...expected].sort();
  return present.length === want.length && present.every((name, i) => name === want[i]);
}

/**
 * Swap ONE skill directory into a shared target root. Used for `codex` and
 * `claude-user`, where the surrounding directory belongs to the user.
 */
export async function writeSharedSkill(
  target: SyncTarget,
  tree: SkillTree,
  root: string,
): Promise<void> {
  await mkdir(root, { recursive: true });
  await withStaging(skillDir(target, tree.slug), join(root, STAGING_DIR), async (staging) => {
    await writeTreeInto(staging, tree.files);
  });
}

/**
 * Whether a destination already exists that this sync did not create.
 *
 * The caller has the ledger and knows whether the slug is ours; this answers
 * the other half — is anything there at all. A `true` on a slug the ledger
 * does not list is hand-written user content, and `writeSharedSkill` must not
 * be called for it: the swap renames the existing directory aside and deletes
 * it, which for `~/.agents/skills/<slug>` would be silent data loss.
 */
export async function destinationExists(target: SyncTarget, slug: string): Promise<boolean> {
  try {
    await lstat(skillDir(target, slug));
    return true;
  } catch {
    return false;
  }
}

/**
 * Delete a directory this sync created.
 *
 * The caller is responsible for having proved ownership from the state
 * ledger; the check here is the narrower one that a ledger cannot make — the
 * path must be a real directory, never a symlink, so removing a managed entry
 * can never follow a link out of the target tree.
 */
export async function removeManagedDir(path: string): Promise<void> {
  let stats: Awaited<ReturnType<typeof lstat>>;
  try {
    stats = await lstat(path);
  } catch {
    return; // already gone — the ledger outlived the directory
  }
  if (!stats.isDirectory()) {
    // A symlink (or a file) standing where a managed directory should be is
    // not something this sync created. `rm` would unlink it happily; refusing
    // keeps "we only delete what we wrote" literally true.
    throw new Error(`Refusing to remove ${path}: not a directory`);
  }
  await rm(path, { recursive: true, force: true });
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

/**
 * Build `dest` under `stagingParent`, then move it into place.
 *
 * POSIX `rename` cannot overwrite a non-empty directory, so an existing
 * destination is first renamed aside and deleted afterwards. The window where
 * neither exists is one `rename` wide, and a crash inside it leaves the
 * destination absent rather than half-written — the failure mode the whole
 * dance is chosen for.
 *
 * `stagingParent` is a caller decision because the two target shapes disagree
 * about what is safe to leave lying around: it must be on the destination's
 * filesystem (`rename`), and out of any directory a skill runner enumerates.
 */
async function withStaging(
  dest: string,
  stagingParent: string,
  build: (staging: string) => Promise<void>,
): Promise<void> {
  await mkdir(dirname(dest), { recursive: true });
  await mkdir(stagingParent, { recursive: true });
  const suffix = `${process.pid}-${Date.now()}`;
  const staging = join(stagingParent, `build-${suffix}`);
  const retired = join(stagingParent, `retired-${suffix}`);
  try {
    await mkdir(staging, { recursive: true });
    await build(staging);
    let hadPrevious = true;
    try {
      await rename(dest, retired);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
      hadPrevious = false;
    }
    try {
      await rename(staging, dest);
    } catch (err) {
      if (hadPrevious) await rename(retired, dest).catch(() => {});
      throw err;
    }
    if (hadPrevious) await rm(retired, { recursive: true, force: true });
  } finally {
    await rm(staging, { recursive: true, force: true }).catch(() => {});
    await rm(retired, { recursive: true, force: true }).catch(() => {});
    // Best effort: empty after a clean run, and `rmdir` on a non-empty one
    // (a concurrent sync still building) fails harmlessly.
    await rmdir(stagingParent).catch(() => {});
  }
}

/** Write a materialized tree under `dir`, creating intermediate directories. */
async function writeTreeInto(dir: string, files: Record<string, Uint8Array>): Promise<void> {
  await mkdir(dir, { recursive: true });
  for (const path of Object.keys(files).sort()) {
    const target = join(dir, path);
    await mkdir(dirname(target), { recursive: true });
    // `flag: "wx"` — the staging tree is fresh, so an existing target means
    // two entries normalized to the same path and one would silently win.
    await writeFile(target, files[path]!, { flag: "wx" });
  }
}
