// SPDX-License-Identifier: Apache-2.0

/**
 * Where synced skills land, and how they get there without a torn state.
 * `claude-plugin` owns its whole tree and is swapped at once; the shared roots
 * get one swap per skill and nothing outside the ledger is ever removed.
 * Staging is dot-prefixed because both tools enumerate `<root>/*` for skills.
 */

import {
  cp,
  lstat,
  mkdir,
  readdir,
  readFile,
  rename,
  rm,
  rmdir,
  writeFile,
} from "node:fs/promises";
import { dirname, join } from "node:path";
import { getDataDir, homeDir } from "../config.ts";

export const SYNC_TARGETS = ["claude-plugin", "codex", "claude-user"] as const;
export type SyncTarget = (typeof SYNC_TARGETS)[number];

const STAGING_DIR = ".appstrate-staging";

const PLUGIN_NAME = "appstrate";

const PLUGIN_MANIFEST = {
  name: PLUGIN_NAME,
  author: { name: "Appstrate", url: "https://appstrate.dev" },
  description: "Skills from your Appstrate organization, kept in sync by `appstrate skills sync`.",
};

const PLUGIN_README = `# Appstrate skills

This directory is generated by \`appstrate skills sync\` from the skills
installed in the space pinned on your Appstrate CLI profile.

Do not edit it: any sync that refreshes a skill overwrites it, and edits are
never synced back. Edit the skill in Appstrate and publish a new version
instead.

Skills appear in Claude Code as \`/${PLUGIN_NAME}:<skill>\`.
`;

const PLUGIN_FILES: Readonly<Record<string, string>> = {
  ".claude-plugin/plugin.json": `${JSON.stringify(PLUGIN_MANIFEST, null, 2)}\n`,
  "README.md": PLUGIN_README,
};

const PLUGIN_ROOT_ENTRIES = [".claude-plugin", "README.md", "skills"];

export interface SkillTree {
  slug: string;
  files: Record<string, Uint8Array>;
}

const SETUP_SLUG = "setup";

/**
 * The plugin a machine gets before the CLI is connected, so the marketplace
 * install succeeds and the remedy sits where the user works: one skill that
 * says how, plus a `SessionStart` hook that says it at every session start —
 * to the user, and to the model so it can offer to run the login itself.
 * The first connected sync replaces the whole tree.
 */
export function setupPluginFiles(problem: string, remedy: string): Record<string, Uint8Array> {
  const skillMd = [
    "---",
    `name: ${SETUP_SLUG}`,
    "description: Connect this machine to Appstrate so the organization's skills sync into " +
      "Claude Code. Use when the user mentions Appstrate skills, asks why they are missing, " +
      "or wants to finish the Appstrate plugin setup.",
    "---",
    "",
    "# Connect this machine to Appstrate",
    "",
    `The \`${PLUGIN_NAME}\` plugin syncs your Appstrate organization's skills into Claude Code, ` +
      `but this machine is not connected yet: ${problem}.`,
    "",
    "1. Run the login. It opens the browser on the device-flow page; the user only has to " +
      "approve there. Ask for the Appstrate instance URL if unknown (`https://app.appstrate.com` " +
      "for the hosted service) and pass it as `--instance`:",
    "",
    "   ```sh",
    `   ${remedy} --instance <url>`,
    "   ```",
    "",
    "   With several organizations, add `--org <slug>`.",
    "2. Reload the plugin with `claude plugin update appstrate@appstrate`, or start a new " +
      "Claude Code session. The organization's skills then replace this one.",
    "",
  ].join("\n");
  const hookOutput = {
    systemMessage:
      `Appstrate skills: this machine is not connected (${problem}). ` +
      `Run \`${remedy}\`, or ask Claude to run it for you.`,
    hookSpecificOutput: {
      hookEventName: "SessionStart",
      additionalContext:
        `The ${PLUGIN_NAME} plugin is installed but not connected: ${problem}. ` +
        `Offer to run \`${remedy} --instance <url>\` for the user (it opens the browser; ` +
        `they only approve there), then \`claude plugin update appstrate@appstrate\`. ` +
        `The /${PLUGIN_NAME}:${SETUP_SLUG} skill has the details.`,
    },
  };
  const hooks = {
    hooks: {
      SessionStart: [
        {
          matcher: "startup",
          hooks: [
            { type: "command", command: `printf '%s' ${shellQuote(JSON.stringify(hookOutput))}` },
          ],
        },
      ],
    },
  };
  const encoder = new TextEncoder();
  return {
    ...Object.fromEntries(Object.entries(PLUGIN_FILES).map(([k, v]) => [k, encoder.encode(v)])),
    "hooks/hooks.json": encoder.encode(`${JSON.stringify(hooks, null, 2)}\n`),
    [`skills/${SETUP_SLUG}/SKILL.md`]: encoder.encode(skillMd),
  };
}

/** POSIX single-quote quoting: the only escape is closing, backslash-quoting, reopening. */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/** Atomic swap of the whole plugin root, same staging discipline as {@link writePluginTree}. */
export async function writeSetupPlugin(
  root: string,
  files: Record<string, Uint8Array>,
): Promise<void> {
  await withStaging(root, join(dirname(root), STAGING_DIR), (staging) =>
    writeTreeInto(staging, files),
  );
}

/** `homeDir()` is the helper `getDataDir()` uses, so the ledger cannot disagree. */
export function targetRoot(target: SyncTarget): string {
  switch (target) {
    case "claude-plugin":
      return join(getDataDir(), "claude-plugin");
    case "codex":
      return join(homeDir(), ".agents", "skills");
    case "claude-user":
      return join(homeDir(), ".claude", "skills");
  }
}

export function skillDir(target: SyncTarget, slug: string): string {
  const root = targetRoot(target);
  return target === "claude-plugin" ? join(root, "skills", slug) : join(root, slug);
}

export interface SkillWriteFailure {
  slug: string;
  error: unknown;
}

/**
 * `carryOver` slugs are copied from the current tree rather than re-downloaded.
 * Per-skill failures are returned, not thrown: one malformed artifact must not
 * cost the run its whole plugin. Only the final swap fails the run.
 */
export async function writePluginTree(
  fresh: SkillTree[],
  carryOver: string[],
  root: string,
): Promise<SkillWriteFailure[]> {
  const failures: SkillWriteFailure[] = [];
  // Beside, not inside: the plugin root is the directory being replaced.
  await withStaging(root, join(dirname(root), STAGING_DIR), async (staging) => {
    for (const [path, contents] of Object.entries(PLUGIN_FILES)) {
      const dest = join(staging, path);
      await mkdir(dirname(dest), { recursive: true });
      await writeFile(dest, contents);
    }
    await mkdir(join(staging, "skills"), { recursive: true });
    for (const slug of [...carryOver].sort()) {
      try {
        await cp(join(root, "skills", slug), join(staging, "skills", slug), {
          recursive: true,
          dereference: false,
        });
      } catch (error) {
        failures.push({ slug, error });
      }
    }
    for (const tree of [...fresh].sort((a, b) => a.slug.localeCompare(b.slug))) {
      try {
        await writeTreeInto(join(staging, "skills", tree.slug), tree.files);
      } catch (error) {
        // Reported as failed, so the tree must not carry a partial copy.
        await rm(join(staging, "skills", tree.slug), { recursive: true, force: true });
        failures.push({ slug: tree.slug, error });
      }
    }
  });
  return failures;
}

/**
 * Fixed files are compared BY CONTENT: an upgrade that changes `plugin.json` or
 * the README must reach a tree whose skills all happen to be up to date.
 */
export async function pluginTreeMatches(root: string, expectedSlugs: string[]): Promise<boolean> {
  if (!(await entriesMatch(root, PLUGIN_ROOT_ENTRIES))) return false;
  for (const [path, contents] of Object.entries(PLUGIN_FILES)) {
    let actual: string;
    try {
      actual = await readFile(join(root, path), "utf-8");
    } catch {
      return false;
    }
    if (actual !== contents) return false;
  }
  return entriesMatch(join(root, "skills"), expectedSlugs);
}

async function entriesMatch(dir: string, expected: string[]): Promise<boolean> {
  let present: string[];
  try {
    present = (await readdir(dir)).sort();
  } catch {
    return false;
  }
  const want = [...expected].sort();
  return present.length === want.length && present.every((name, i) => name === want[i]);
}

export async function writeSharedSkill(
  target: SyncTarget,
  tree: SkillTree,
  root: string,
): Promise<void> {
  await mkdir(root, { recursive: true });
  await withStaging(skillDir(target, tree.slug), join(root, STAGING_DIR), async (staging) => {
    await writeTreeInto(staging, tree.files);
  });
}

/** The half of ownership the ledger cannot answer: is anything there at all. */
export async function destinationExists(target: SyncTarget, slug: string): Promise<boolean> {
  try {
    await lstat(skillDir(target, slug));
    return true;
  } catch {
    return false;
  }
}

export async function removeManagedDir(path: string): Promise<void> {
  let stats: Awaited<ReturnType<typeof lstat>>;
  try {
    stats = await lstat(path);
  } catch {
    return; // already gone — the ledger outlived the directory
  }
  if (!stats.isDirectory()) {
    // Not something this sync created, whatever the ledger says.
    throw new Error(`Refusing to remove ${path}: not a directory`);
  }
  await rm(path, { recursive: true, force: true });
}

/**
 * POSIX `rename` cannot overwrite a non-empty directory, so an existing `dest`
 * is renamed aside first: the window where neither exists is one `rename`
 * wide, and a crash inside it leaves `dest` absent rather than half-written.
 */
async function withStaging(
  dest: string,
  stagingParent: string,
  build: (staging: string) => Promise<void>,
): Promise<void> {
  await mkdir(dirname(dest), { recursive: true });
  await mkdir(stagingParent, { recursive: true });
  const suffix = `${process.pid}-${Date.now()}`;
  const staging = join(stagingParent, `build-${suffix}`);
  const retired = join(stagingParent, `retired-${suffix}`);
  try {
    await mkdir(staging, { recursive: true });
    await build(staging);
    let hadPrevious = true;
    try {
      await rename(dest, retired);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
      hadPrevious = false;
    }
    try {
      await rename(staging, dest);
    } catch (err) {
      if (hadPrevious) await rename(retired, dest).catch(() => {});
      throw err;
    }
    if (hadPrevious) await rm(retired, { recursive: true, force: true });
  } finally {
    await rm(staging, { recursive: true, force: true }).catch(() => {});
    await rm(retired, { recursive: true, force: true }).catch(() => {});
    // Best effort: `rmdir` on a concurrent sync's staging fails harmlessly.
    await rmdir(stagingParent).catch(() => {});
  }
}

async function writeTreeInto(dir: string, files: Record<string, Uint8Array>): Promise<void> {
  await mkdir(dir, { recursive: true });
  for (const path of Object.keys(files).sort()) {
    const target = join(dir, path);
    await mkdir(dirname(target), { recursive: true });
    // `wx`: the staging tree is fresh, so a collision means two entries
    // normalized to the same path and one would silently win.
    await writeFile(target, files[path]!, { flag: "wx" });
  }
}
