// SPDX-License-Identifier: Apache-2.0

/**
 * Every column a Better Auth plugin declares `index: true` on must be indexed
 * in the Drizzle schema.
 *
 * The plugins own their table shape; the repo owns the DDL, because the OIDC
 * tables are hand-written Drizzle rather than generated by the Better Auth CLI.
 * Nothing reconciles the two at boot, so ten FK columns went unindexed from the
 * day the tables were folded in (#1348) — including the `session_id` columns
 * both token tables carry, which turn one logout into a sequential scan of
 * both.
 *
 * The declarations are read off the LIVE plugin objects rather than restated
 * here, so a plugin upgrade that indexes a new column fails this test instead
 * of passing silently.
 */

import { describe, it, expect } from "bun:test";
import { getTableConfig, type PgTable } from "drizzle-orm/pg-core";
import {
  oauthAccessToken,
  oauthClient,
  oauthClientResource,
  oauthConsent,
  oauthRefreshToken,
} from "@appstrate/db/schema";
import { oidcBetterAuthPlugins } from "../../auth/plugins.ts";

/** The Better Auth model id each plugin-declared table is backed by. */
const TABLE_BY_MODEL: Record<string, PgTable> = {
  oauthClient,
  oauthClientResource,
  oauthRefreshToken,
  oauthAccessToken,
  oauthConsent,
};

interface PluginSchema {
  schema?: Record<string, { fields?: Record<string, { index?: boolean } | undefined> }>;
}

/** `model -> [field, …]` for every field a contributed plugin declares indexed. */
function declaredIndexedFields(): Map<string, string[]> {
  const declared = new Map<string, string[]>();
  for (const plugin of oidcBetterAuthPlugins() as PluginSchema[]) {
    for (const [model, def] of Object.entries(plugin?.schema ?? {})) {
      const fields = Object.entries(def?.fields ?? {})
        .filter(([, field]) => field?.index === true)
        .map(([name]) => name);
      if (fields.length > 0) declared.set(model, fields);
    }
  }
  return declared;
}

/** SQL names of the columns each index on `table` leads with. */
function leadingIndexedColumns(table: PgTable): Set<string> {
  const names = new Set<string>();
  for (const index of getTableConfig(table).indexes) {
    // An index may lead with a raw SQL expression rather than a column, and
    // drizzle types the entry as a partial union of the two. Only the column
    // arm carries a `name`, and only a name answers "is this column indexed".
    const leading = index.config.columns[0];
    if (leading && "name" in leading && typeof leading.name === "string") {
      names.add(leading.name);
    }
  }
  return names;
}

describe("Better Auth `index: true` declarations", () => {
  const declared = declaredIndexedFields();

  it("declares at least the oauth-provider token and consent tables", () => {
    // A guard on the guard: if the plugin ever stops exposing `schema`, the
    // per-model assertions below would all vacuously pass.
    expect([...declared.keys()].sort()).toEqual(Object.keys(TABLE_BY_MODEL).sort());
  });

  for (const [model, fields] of declared) {
    it(`indexes every declared column of ${model}`, () => {
      const table = TABLE_BY_MODEL[model];
      expect(table).toBeDefined();

      const indexed = leadingIndexedColumns(table!);
      const columns = getTableConfig(table!).columns;
      const missing = fields.filter((field) => {
        const column = columns.find((candidate) => candidate.name === toSnakeCase(field));
        expect(column, `${model}.${field} has no column in the Drizzle table`).toBeDefined();
        return !indexed.has(column!.name);
      });

      expect(missing).toEqual([]);
    });
  }
});

/** Better Auth field names are camelCase; the wire and SQL are snake_case. */
function toSnakeCase(field: string): string {
  return field.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}
