// SPDX-License-Identifier: Apache-2.0

import { describe, it, expect, beforeAll, afterAll } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { generateEnvForTier, type Tier } from "../src/lib/install/secrets.ts";

/**
 * Distribution lockstep guard (issue #905).
 *
 * Every env var the installer generates must be threaded through the
 * self-hosting compose templates by hand — `environment:` blocks are
 * whitelists, so a generated-but-not-forwarded secret silently never
 * reaches the container. CONNECT_SESSION_SECRET shipped exactly that
 * way: generated nowhere, forwarded nowhere, and the hosted connect
 * portal 503'd on every `appstrate install` deployment while dev (which
 * reads `.env.example` directly) kept working.
 *
 * Two invariants, one per drift direction:
 *
 *  1. generated ⇒ forwarded — every key `generateEnvForTier` writes to
 *     `.env` appears in the matching compose template (as a passthrough,
 *     an interpolation, or a `:?` loud-fail). Catches the #905 class:
 *     a new secret added to the generator but not to the templates.
 *
 *  2. required ⇒ generated — every `${KEY:?}` loud-fail key a template
 *     demands is produced by the generator for that tier. Catches the
 *     inverse class: a template requiring a secret fresh installs never
 *     write, which would brick `docker compose up` out of the box.
 *
 * The templates are read from the repo checkout (same files `tier123.ts`
 * embeds via text imports), so this test runs against exactly what the
 * CLI ships.
 */

const REPO_ROOT = join(import.meta.dir, "..", "..", "..");

/** Compose template per Docker tier — mirror of `tier123.ts` TIER_COMPOSE. */
const TIER_TEMPLATES: Record<Exclude<Tier, 0>, string> = {
  1: "examples/self-hosting/docker-compose.tier1.yml",
  2: "examples/self-hosting/docker-compose.tier2.yml",
  3: "examples/self-hosting/docker-compose.tier3.yml",
};

/**
 * Non-tier templates operators consume directly (repo-root prod compose,
 * the documented manual self-hosting compose). Both describe a full
 * stack, so they are checked against the Tier 3 generator output.
 */
const FULL_STACK_TEMPLATES = ["docker-compose.yml", "examples/self-hosting/docker-compose.yml"];

function readTemplate(relPath: string): string {
  return readFileSync(join(REPO_ROOT, relPath), "utf8");
}

/** Keys a template marks as required via `${KEY:?...}` interpolation. */
function requiredComposeKeys(template: string): string[] {
  return [...template.matchAll(/\$\{([A-Z][A-Z0-9_]*):\?/g)].map((m) => m[1] as string);
}

describe("installer ↔ compose template secret lockstep (issue #905)", () => {
  // `generateEnvForTier` pins APPSTRATE_VERSION via `resolveDockerImageTag`,
  // which refuses to run from a dev CLI build without an explicit pin.
  let savedVersion: string | undefined;
  beforeAll(() => {
    savedVersion = process.env.APPSTRATE_VERSION;
    process.env.APPSTRATE_VERSION = "0.0.0-test";
  });
  afterAll(() => {
    if (savedVersion === undefined) delete process.env.APPSTRATE_VERSION;
    else process.env.APPSTRATE_VERSION = savedVersion;
  });

  for (const [tier, relPath] of Object.entries(TIER_TEMPLATES)) {
    it(`tier ${tier}: every generated .env key is referenced by ${relPath}`, () => {
      const template = readTemplate(relPath);
      const missing = Object.keys(generateEnvForTier(Number(tier) as Tier)).filter(
        (key) => !new RegExp(`\\b${key}\\b`).test(template),
      );
      expect(missing).toEqual([]);
    });

    it(`tier ${tier}: every \${KEY:?} required by ${relPath} is generated by the installer`, () => {
      const generatedKeys = new Set(Object.keys(generateEnvForTier(Number(tier) as Tier)));
      const unprovisioned = requiredComposeKeys(readTemplate(relPath)).filter(
        (key) => !generatedKeys.has(key),
      );
      expect(unprovisioned).toEqual([]);
    });
  }

  for (const relPath of FULL_STACK_TEMPLATES) {
    it(`${relPath}: every \${KEY:?} required key is generated by the installer (tier 3)`, () => {
      const generatedKeys = new Set(Object.keys(generateEnvForTier(3)));
      const unprovisioned = requiredComposeKeys(readTemplate(relPath)).filter(
        (key) => !generatedKeys.has(key),
      );
      expect(unprovisioned).toEqual([]);
    });
  }

  it("generates CONNECT_SESSION_SECRET on every tier (the #905 regression)", () => {
    for (const tier of [0, 1, 2, 3] as const) {
      const env = generateEnvForTier(tier);
      expect(env.CONNECT_SESSION_SECRET).toMatch(/^[0-9a-f]{64}$/);
    }
  });
});
