#!/usr/bin/env bun
// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Appstrate

/**
 * Build the `briefing-agent` example:
 *
 *   examples/briefing-agent/
 *     source/manifest.json   ← hand-edited
 *     source/prompt.md       ← hand-edited
 *     build.ts               ← this script
 *     agent.afps             ← signed bundle (generated)
 *     key.json               ← Ed25519 keypair (generated, EXAMPLE ONLY)
 *     trust-root.json        ← trust root pinned to key.json (generated)
 *
 * Run `bun run examples/briefing-agent/build.ts` to regenerate the
 * three generated files from the committed source. Keys rotate on
 * every run — these files are demo artifacts, not committed secrets.
 */

import { readFile, writeFile } from "node:fs/promises";
import { zipSync } from "fflate";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildBundleFromAfps } from "../../src/bundle/build.ts";
import { emptyPackageCatalog } from "../../src/bundle/catalog.ts";
import { canonicalBundleDigest, generateKeyPair, signBundle } from "../../src/bundle/signing.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, "source");
const enc = (s: string): Uint8Array => new TextEncoder().encode(s);

async function main(): Promise<void> {
  const manifestBytes = await readFile(join(SRC, "manifest.json"));
  const promptBytes = await readFile(join(SRC, "prompt.md"));

  const unsignedFiles: Record<string, Uint8Array> = {
    "manifest.json": manifestBytes,
    "prompt.md": promptBytes,
  };

  const key = generateKeyPair();
  const unsignedBundle = await buildBundleFromAfps(zipSync(unsignedFiles), emptyPackageCatalog);
  const canonical = canonicalBundleDigest(unsignedBundle);
  const signature = signBundle(canonical, {
    privateKey: key.privateKey,
    keyId: key.keyId,
  });

  const signedFiles: Record<string, Uint8Array> = {
    ...unsignedFiles,
    "signature.sig": enc(JSON.stringify(signature, null, 2) + "\n"),
  };
  const zip = zipSync(signedFiles);

  await writeFile(join(HERE, "agent.afps"), zip);
  await writeFile(join(HERE, "key.json"), JSON.stringify(key, null, 2) + "\n");
  await writeFile(
    join(HERE, "trust-root.json"),
    JSON.stringify(
      {
        keys: [
          {
            keyId: key.keyId,
            publicKey: key.publicKey,
            comment: "briefing-agent example key — regenerated by build.ts",
          },
        ],
      },
      null,
      2,
    ) + "\n",
  );

  process.stdout.write(`✓ wrote agent.afps (keyId: ${key.keyId})\n`);
  process.stdout.write(`  run:  afps run ${join(HERE, "agent.afps")} \\\n`);
  process.stdout.write(`          --events ${join(HERE, "events.json")} \\\n`);
  process.stdout.write(`          --context ${join(HERE, "context.json")} \\\n`);
  process.stdout.write(`          --snapshot ${join(HERE, "snapshot.json")}\n`);
}

await main();
