// SPDX-License-Identifier: Apache-2.0

import { defineConfig, defineDocs } from 'fumadocs-mdx/config';

// `content/` is generated by scripts/sync-content.ts and gitignored.
export const docs = defineDocs({
  dir: 'content',
});

export default defineConfig();
