-- `packages.home_space_id` — the ONE space whose `<type>:write` authorizes
-- editing, publishing, renaming and deleting a package
-- (`assertPackageMutationAccess`, `apps/api/src/lib/package-access.ts`).
--
-- WHY. Write authority used to be "the caller holds the permission in EVERY
-- space where the package is installed". That rule made an author lose their
-- own package the moment someone installed it into a space the author cannot
-- read, and made a package installed in five spaces editable only by whoever
-- administers all five. Authority now follows a home, and the other
-- installations consume. Every organization package HAS one: `0067` adds the
-- CHECK `packages_org_package_has_home`, and the packages that belong to no
-- team are homed in the organization's DEFAULT space (RBAC spec §6.9, §13.7).
-- The only rows that stay homeless are a SYSTEM package, which is a delivery
-- rather than a residency, and an inline run's `ephemeral` shadow.
--
-- `ON DELETE RESTRICT`, not SET NULL: nulling on a space deletion would leave
-- an organization package with no home, i.e. a package nobody in the
-- organization can author — the state `0067`'s CHECK refuses on every write.
-- Deleting a space that homes packages has to re-home or delete them first.
--
-- SHAPE ONLY (`docs/NO_TRANSITIONAL_CODE.md` §2). Every existing row keeps
-- `home_space_id IS NULL` — nobody's to write until a home is chosen — which is
-- why the column is not backfilled here: choosing a home for a package
-- installed in several spaces is an operator decision, made once, by
-- `scripts/migration/0014-packages-home-space-backfill.sql`. Deploy the way
-- `0008` was deployed: stop the platform, run the migrations only, run 0014,
-- then bring the new version up. Serving traffic in between locks every
-- author, and every API key, out of its own packages.
--
-- ROLLBACK: safe BEFORE 0014 only. A previous build never reads or writes the
-- column, and the FK accepts the NULLs this file leaves behind. Once 0014 has
-- run, the column names spaces: the old build ignores it, so a rollback is
-- still serviceable, but `DELETE FROM spaces` is not — the `ON DELETE RESTRICT`
-- fires on a space that homes a package and the older build has no route that
-- clears a home. Clearing the homes is TWO statements in ONE order: drop
-- `0067`'s CHECK first (`ALTER TABLE packages DROP CONSTRAINT
-- packages_org_package_has_home;`), THEN `UPDATE packages SET home_space_id =
-- NULL`. `NOT VALID` governs every INSERT and UPDATE from the moment that
-- constraint applies, so the reverse order raises 23514 and clears nothing. Do
-- it BEFORE any space deletion, not after the first 23503 —
-- `scripts/migration/README.md` → "Rollback — what is actually reversible" is
-- the per-file authority on all of it.
--
-- See `scripts/migration/README.md` → "Personal spaces & sharing rollout" for
-- the order this file, 0064, 0065, 0014 and 0015 go in.

ALTER TABLE "packages" ADD COLUMN "home_space_id" text;--> statement-breakpoint
ALTER TABLE "packages" ADD CONSTRAINT "packages_home_space_id_spaces_id_fk" FOREIGN KEY ("home_space_id") REFERENCES "public"."spaces"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_packages_home_space_id" ON "packages" USING btree ("home_space_id");