-- `organizations.logo` reaches the schema a third time, and the reason is the
-- same twice over.
--
-- It arrived with the redesigned org surfaces as `0039_rainy_next_avengers`,
-- which the 10 September merge of main dropped: main owned a `0039`, the
-- journal kept one file, and the column stayed in the Drizzle schema with
-- nothing to create it. Restored as `0063_org_logo` on 20 September — and the
-- #1437 merge the same day took `0063` through `0068`, so it moves here.
--
-- `IF NOT EXISTS` because the databases that ran either earlier copy already
-- hold the column, and they must migrate rather than abort.
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "logo" text;
