-- `integration_connections.account_id` becomes nullable: NULL means the
-- provider exposed no identity (an API key, a login secret, a token response
-- with no identity claim). It replaces the string 'default', which the service
-- special-cased as "no identity" and which therefore made a real upstream
-- account named `default` indistinguishable from none.
--
-- No index or constraint reads the column, so NULL semantics in uniqueness do
-- not arise.
--
-- The rows still carrying 'default' are rewritten by
-- `scripts/migration/0022-integration-connections-null-account-id.sql`, not
-- here: DROP NOT NULL scans nothing, so it licenses no write
-- (docs/NO_TRANSITIONAL_CODE.md §2). Until that script runs, such rows read as
-- an account literally named 'default'.
--
-- ROLLBACK: `UPDATE integration_connections SET account_id = 'default' WHERE
-- account_id IS NULL;` then `ALTER TABLE "integration_connections" ALTER
-- COLUMN "account_id" SET NOT NULL;`.
ALTER TABLE "integration_connections" ALTER COLUMN "account_id" DROP NOT NULL;
