/**
 * All OpenAPI schema definitions (components/schemas).
 */
export const schemas = {
  Error: {
    type: "object",
    properties: {
      error: {
        type: "string",
        description: "Error code (e.g. VALIDATION_ERROR, UNAUTHORIZED)",
      },
      message: { type: "string", description: "Human-readable error message" },
    },
  },
  User: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      email: { type: "string" },
    },
  },
  Profile: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
      language: { type: "string", enum: ["fr", "en"] },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  ProfileBatchItem: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
    },
  },
  Organization: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      slug: { type: "string" },
      role: { type: "string", enum: ["owner", "admin", "member"] },
    },
  },
  OrgMember: {
    type: "object",
    properties: {
      userId: { type: "string" },
      name: { type: "string" },
      email: { type: "string" },
      displayName: { type: "string" },
      role: { type: "string", enum: ["owner", "admin", "member"] },
      joinedAt: { type: "string", format: "date-time" },
    },
  },
  OrgInvitationInfo: {
    type: "object",
    properties: {
      id: { type: "string" },
      email: { type: "string" },
      role: { type: "string", enum: ["owner", "admin", "member"] },
      status: { type: "string", enum: ["pending", "accepted", "expired", "cancelled"] },
      invitedBy: { type: "string" },
      inviterName: { type: "string" },
      expiresAt: { type: "string", format: "date-time" },
      createdAt: { type: "string", format: "date-time" },
    },
  },
  OrgDetail: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      slug: { type: "string" },
      createdBy: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      members: {
        type: "array",
        items: { $ref: "#/components/schemas/OrgMember" },
      },
      invitations: {
        type: "array",
        items: { $ref: "#/components/schemas/OrgInvitationInfo" },
      },
    },
  },
  ServiceStatus: {
    type: "object",
    properties: {
      id: { type: "string", description: "Service ID" },
      provider: { type: "string", description: "Provider ID" },
      scopes: { type: "array", items: { type: "string" } },
      connectionMode: { type: "string", enum: ["user", "admin"] },
      status: { type: "string", enum: ["connected", "not_connected", "admin_connected"] },
      authMode: { type: "string", enum: ["oauth2", "api_key", "basic", "custom"] },
      displayName: { type: "string" },
    },
  },
  FlowSkillRef: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      description: { type: "string" },
      source: { type: "string", enum: ["built-in", "org"] },
    },
  },
  FlowExtensionRef: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      description: { type: "string" },
      source: { type: "string", enum: ["built-in", "org"] },
    },
  },
  FlowListItem: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
      description: { type: "string" },
      schemaVersion: { type: "string" },
      author: { type: "string" },
      tags: { type: "array", items: { type: "string" } },
      source: { type: "string", enum: ["built-in", "user"] },
      runningExecutions: { type: "integer" },
      requires: {
        type: "object",
        properties: {
          services: { type: "array", items: { type: "string" } },
          skills: { type: "array", items: { type: "string" } },
          extensions: { type: "array", items: { type: "string" } },
        },
      },
    },
  },
  FlowDetail: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
      description: { type: "string" },
      source: { type: "string", enum: ["built-in", "user"] },
      prompt: { type: "string", description: "Agent prompt markdown (user flows only)" },
      updatedAt: { type: "string", format: "date-time" },
      config: {
        type: "object",
        properties: {
          schema: { type: "object" },
          current: { type: "object" },
        },
      },
      input: {
        type: "object",
        properties: {
          schema: { type: "object" },
        },
      },
      output: {
        type: "object",
        properties: {
          schema: { type: "object" },
        },
      },
      execution: {
        type: "object",
        properties: {
          timeout: { type: "integer", description: "Timeout in seconds" },
          outputRetries: { type: "integer", description: "Number of output validation retries" },
        },
      },
      requires: {
        type: "object",
        properties: {
          services: { type: "array", items: { $ref: "#/components/schemas/ServiceStatus" } },
          skills: { type: "array", items: { $ref: "#/components/schemas/FlowSkillRef" } },
          extensions: { type: "array", items: { $ref: "#/components/schemas/FlowExtensionRef" } },
        },
      },
      lastExecution: { $ref: "#/components/schemas/Execution" },
      runningExecutions: { type: "integer" },
    },
  },
  FlowVersion: {
    type: "object",
    properties: {
      id: { type: "integer" },
      flowId: { type: "string" },
      versionNumber: { type: "integer" },
      createdBy: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
    },
  },
  Execution: {
    type: "object",
    properties: {
      id: { type: "string" },
      flowId: { type: "string" },
      userId: { type: "string" },
      status: {
        type: "string",
        enum: ["pending", "running", "success", "failed", "timeout", "cancelled"],
      },
      input: { type: "object" },
      result: { type: "object" },
      state: { type: "object" },
      error: { type: "string" },
      tokensUsed: { type: "integer" },
      tokenUsage: { type: "object" },
      costUsd: { type: "string" },
      startedAt: { type: "string", format: "date-time" },
      completedAt: { type: "string", format: "date-time" },
      duration: { type: "integer", description: "Duration in milliseconds" },
    },
  },
  ExecutionLog: {
    type: "object",
    properties: {
      id: { type: "integer" },
      executionId: { type: "string" },
      type: { type: "string" },
      event: { type: "string" },
      message: { type: "string" },
      data: { type: "object" },
      createdAt: { type: "string", format: "date-time" },
    },
  },
  Schedule: {
    type: "object",
    properties: {
      id: { type: "string" },
      flowId: { type: "string" },
      name: { type: "string" },
      enabled: { type: "boolean" },
      cronExpression: { type: "string" },
      timezone: { type: "string" },
      input: { type: "object" },
      lastRunAt: { type: "string", format: "date-time" },
      nextRunAt: { type: "string", format: "date-time" },
    },
  },
  Integration: {
    type: "object",
    properties: {
      uniqueKey: { type: "string" },
      provider: { type: "string" },
      displayName: { type: "string" },
      logo: { type: "string" },
      status: { type: "string", enum: ["connected", "not_connected"] },
      authMode: { type: "string" },
      connectedAt: { type: "string" },
    },
  },
  ConnectionStatus: {
    type: "object",
    properties: {
      id: { type: "string" },
      providerId: { type: "string" },
      authMode: { type: "string", enum: ["oauth2", "api_key", "basic", "custom"] },
      scopesGranted: { type: "array", items: { type: "string" } },
      createdAt: { type: "string", format: "date-time" },
      expiresAt: { type: "string", format: "date-time" },
    },
  },
  ProviderConfig: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
      authMode: { type: "string", enum: ["oauth2", "api_key", "basic", "custom"] },
      source: { type: "string", enum: ["built-in", "custom"] },
      hasClientId: { type: "boolean" },
      hasClientSecret: { type: "boolean" },
      authorizationUrl: { type: "string" },
      tokenUrl: { type: "string" },
      refreshUrl: { type: "string" },
      defaultScopes: { type: "array", items: { type: "string" } },
      scopeSeparator: { type: "string" },
      pkceEnabled: { type: "boolean" },
      tokenAuthMethod: { type: "string", enum: ["client_secret_post", "client_secret_basic"] },
      credentialSchema: { type: "object" },
      credentialFieldName: { type: "string" },
      credentialHeaderName: { type: "string" },
      credentialHeaderPrefix: { type: "string" },
      availableScopes: { type: "object" },
      authorizedUris: { type: "array", items: { type: "string" } },
      allowAllUris: { type: "boolean" },
      iconUrl: { type: "string" },
      categories: { type: "array", items: { type: "string" } },
      docsUrl: { type: "string" },
      usedByFlows: { type: "integer" },
    },
  },
  ProviderConfigInput: {
    type: "object",
    required: ["id", "displayName", "authMode"],
    properties: {
      id: { type: "string", pattern: "^[a-z0-9][a-z0-9-]*$" },
      displayName: { type: "string" },
      authMode: { type: "string", enum: ["oauth2", "api_key", "basic", "custom"] },
      clientId: { type: "string" },
      clientSecret: { type: "string" },
      authorizationUrl: { type: "string" },
      tokenUrl: { type: "string" },
      refreshUrl: { type: "string" },
      defaultScopes: { type: "array", items: { type: "string" } },
      scopeSeparator: { type: "string" },
      pkceEnabled: { type: "boolean" },
      tokenAuthMethod: { type: "string", enum: ["client_secret_post", "client_secret_basic"] },
      authorizationParams: { type: "object" },
      tokenParams: { type: "object" },
      credentialSchema: { type: "object" },
      credentialFieldName: { type: "string" },
      credentialHeaderName: { type: "string" },
      credentialHeaderPrefix: { type: "string" },
      availableScopes: { type: "object" },
      iconUrl: { type: "string" },
      categories: { type: "array", items: { type: "string" } },
      docsUrl: { type: "string" },
      authorizedUris: { type: "array", items: { type: "string" } },
      allowAllUris: { type: "boolean" },
    },
  },
  ApiKeyInfo: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      keyPrefix: { type: "string", description: "First 8 chars of the key for identification" },
      scopes: {
        type: "array",
        items: { type: "string" },
        description: "Currently empty (admin access). Future: granular permissions.",
      },
      createdBy: { type: "string" },
      createdByName: { type: "string" },
      expiresAt: { type: "string", format: "date-time" },
      lastUsedAt: { type: "string", format: "date-time" },
      revokedAt: { type: "string", format: "date-time" },
      createdAt: { type: "string", format: "date-time" },
    },
  },
  OrgSkill: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      description: { type: "string" },
      source: { type: "string", enum: ["built-in", "org"] },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  OrgSkillDetail: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      description: { type: "string" },
      content: { type: "string", description: "SKILL.md content" },
      source: { type: "string", enum: ["built-in", "org"] },
      createdBy: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  OrgExtension: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      description: { type: "string" },
      source: { type: "string", enum: ["built-in", "org"] },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  OrgExtensionDetail: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      description: { type: "string" },
      content: { type: "string", description: "Extension TypeScript source" },
      source: { type: "string", enum: ["built-in", "org"] },
      createdBy: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  ShareFlowInfo: {
    type: "object",
    properties: {
      flowId: { type: "string" },
      displayName: { type: "string" },
      description: { type: "string" },
      input: {
        type: "object",
        properties: {
          schema: { type: "object" },
        },
      },
    },
  },
} as const;
