/**
 * All OpenAPI schema definitions (components/schemas).
 */
export const schemas = {
  Error: {
    type: "object",
    properties: {
      error: {
        type: "string",
        description: "Error code (e.g. VALIDATION_ERROR, UNAUTHORIZED)",
      },
      message: { type: "string", description: "Human-readable error message" },
    },
  },
  User: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      email: { type: "string" },
    },
  },
  ProfileBatchItem: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
    },
  },
  Organization: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      slug: { type: "string" },
      role: { type: "string", enum: ["owner", "admin", "member"] },
    },
  },
  OrgMember: {
    type: "object",
    properties: {
      userId: { type: "string" },
      displayName: { type: "string" },
      email: { type: "string" },
      role: { type: "string", enum: ["owner", "admin", "member"] },
      joinedAt: { type: "string", format: "date-time" },
    },
  },
  OrgInvitationInfo: {
    type: "object",
    properties: {
      id: { type: "string" },
      email: { type: "string" },
      role: { type: "string", enum: ["owner", "admin", "member"] },
      token: { type: "string" },
      expiresAt: { type: "string", format: "date-time" },
      createdAt: { type: "string", format: "date-time" },
    },
  },
  OrgDetail: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      slug: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      members: {
        type: "array",
        items: { $ref: "#/components/schemas/OrgMember" },
      },
      invitations: {
        type: "array",
        items: { $ref: "#/components/schemas/OrgInvitationInfo" },
      },
    },
  },
  ProviderStatus: {
    type: "object",
    properties: {
      id: { type: "string", description: "Provider requirement ID" },
      provider: { type: "string", description: "Provider ID" },
      description: { type: "string" },
      connectionMode: { type: "string", enum: ["user", "admin"] },
      status: { type: "string", enum: ["connected", "not_connected", "needs_reconnection"] },
      authMode: { type: "string" },
      adminProvided: { type: "boolean" },
      scopesRequired: { type: "array", items: { type: "string" } },
      scopesGranted: { type: "array", items: { type: "string" } },
      scopesSufficient: { type: "boolean" },
      scopesMissing: { type: "array", items: { type: "string" } },
    },
  },
  FlowSkillRef: {
    type: "object",
    properties: {
      id: { type: "string" },
      version: { type: "string" },
      name: { type: "string" },
      description: { type: "string" },
    },
  },
  FlowExtensionRef: {
    type: "object",
    properties: {
      id: { type: "string" },
      version: { type: "string" },
      name: { type: "string" },
      description: { type: "string" },
    },
  },
  FlowListItem: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
      description: { type: "string" },
      schemaVersion: { type: "string" },
      author: { type: "string" },
      tags: { type: "array", items: { type: "string" } },
      source: { type: "string", enum: ["system", "local"] },
      scope: {
        type: ["string", "null"],
        description: "Scope from manifest name (e.g. myorg from @myorg/name)",
      },
      version: { type: ["string", "null"], description: "Version from manifest" },
      type: {
        type: "string",
        description: "Package type from manifest",
        enum: ["flow", "skill", "extension", "provider"],
      },
      runningExecutions: { type: "integer" },
      requires: {
        type: "object",
        properties: {
          providers: { type: "array", items: { type: "string" } },
          skills: { type: "object", additionalProperties: { type: "string" } },
          extensions: { type: "object", additionalProperties: { type: "string" } },
        },
      },
    },
  },
  FlowDetail: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
      description: { type: "string" },
      source: { type: "string", enum: ["system", "local"] },
      scope: { type: ["string", "null"], description: "Scope from manifest name" },
      version: { type: ["string", "null"], description: "Version from manifest" },
      manifest: { type: "object", description: "Full manifest object (user flows only)" },
      prompt: { type: "string", description: "Agent prompt markdown (user flows only)" },
      updatedAt: {
        type: "string",
        format: "date-time",
        description: "Last updated timestamp (user flows only)",
      },
      lockVersion: {
        type: "integer",
        description: "Optimistic lock version (user flows only)",
      },
      config: {
        type: "object",
        properties: {
          schema: { type: "object" },
          current: { type: "object" },
        },
      },
      input: {
        type: "object",
        properties: {
          schema: { type: "object" },
        },
      },
      output: {
        type: "object",
        properties: {
          schema: { type: "object" },
        },
      },
      requires: {
        type: "object",
        properties: {
          providers: { type: "array", items: { $ref: "#/components/schemas/ProviderStatus" } },
          skills: { type: "array", items: { $ref: "#/components/schemas/FlowSkillRef" } },
          extensions: { type: "array", items: { $ref: "#/components/schemas/FlowExtensionRef" } },
        },
      },
      lastExecution: {
        type: ["object", "null"],
        description: "Summary of the most recent execution (null if never executed)",
        properties: {
          id: { type: "string" },
          status: { type: "string" },
          startedAt: { type: "string", format: "date-time" },
          duration: { type: "integer" },
        },
      },
      runningExecutions: { type: "integer" },
      versionCount: {
        type: "integer",
        description: "Number of published versions (0 for built-in flows)",
      },
      forkedFrom: { type: ["string", "null"], description: "Source package ID if forked" },
      hasUnpublishedChanges: {
        type: "boolean",
        description: "Whether the flow has local changes not yet published as a version",
      },
    },
  },
  FlowVersion: {
    type: "object",
    properties: {
      id: { type: "integer" },
      packageId: { type: "string" },
      version: { type: "string", description: "Semver version string (e.g. 1.0.0)" },
      integrity: { type: "string", description: "SRI integrity hash (sha256-...)" },
      artifactSize: { type: "integer", description: "Artifact ZIP size in bytes" },
      yanked: { type: "boolean", description: "Whether this version has been yanked" },
      createdBy: { type: ["string", "null"] },
      createdAt: { type: ["string", "null"], format: "date-time" },
    },
  },
  Execution: {
    type: "object",
    properties: {
      id: { type: "string" },
      packageId: { type: "string" },
      userId: { type: "string" },
      orgId: { type: "string" },
      status: {
        type: "string",
        enum: ["pending", "running", "success", "failed", "timeout", "cancelled"],
      },
      input: { type: "object" },
      result: { type: "object" },
      state: { type: "object" },
      error: { type: "string" },
      tokensUsed: { type: "integer" },
      tokenUsage: { type: "object" },
      startedAt: { type: "string", format: "date-time" },
      completedAt: { type: "string", format: "date-time" },
      duration: { type: "integer", description: "Duration in milliseconds" },
      connectionProfileId: { type: "string" },
      scheduleId: { type: "string" },
      flowVersionId: { type: "integer" },
    },
  },
  ExecutionLog: {
    type: "object",
    properties: {
      id: { type: "integer" },
      executionId: { type: "string" },
      userId: { type: "string" },
      orgId: { type: "string" },
      type: { type: "string" },
      event: { type: "string" },
      message: { type: "string" },
      data: { type: "object" },
      createdAt: { type: "string", format: "date-time" },
    },
  },
  Schedule: {
    type: "object",
    properties: {
      id: { type: "string" },
      packageId: { type: "string" },
      userId: { type: "string" },
      orgId: { type: "string" },
      name: { type: ["string", "null"] },
      enabled: { type: ["boolean", "null"] },
      cronExpression: { type: "string" },
      timezone: { type: ["string", "null"] },
      input: { type: "object" },
      lastRunAt: { type: ["string", "null"], format: "date-time" },
      nextRunAt: { type: ["string", "null"], format: "date-time" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  Integration: {
    type: "object",
    properties: {
      uniqueKey: { type: "string" },
      provider: { type: "string" },
      displayName: { type: "string" },
      logo: { type: "string" },
      status: { type: "string", enum: ["connected", "not_connected", "needs_reconnection"] },
      authMode: { type: "string" },
      connectionId: { type: "string" },
      connectedAt: { type: "string" },
    },
  },
  ConnectionStatus: {
    type: "object",
    properties: {
      provider: { type: "string" },
      status: { type: "string", enum: ["connected", "not_connected", "needs_reconnection"] },
      connectionId: { type: "string" },
      connectedAt: { type: "string" },
      scopesGranted: { type: "array", items: { type: "string" } },
    },
  },
  ProviderConfig: {
    type: "object",
    properties: {
      id: { type: "string" },
      displayName: { type: "string" },
      authMode: {
        type: "string",
        enum: ["oauth2", "oauth1", "api_key", "basic", "custom", "proxy"],
      },
      source: { type: "string", enum: ["built-in", "custom"] },
      hasCredentials: {
        type: "boolean",
        description: "Whether admin credentials are currently configured for this provider",
      },
      enabled: {
        type: "boolean",
        description: "Whether this provider is enabled for use in the organization",
      },
      adminCredentialSchema: {
        type: "object",
        description:
          "JSON Schema describing admin credential fields. Undefined means no admin credentials needed.",
      },
      authorizationUrl: { type: "string" },
      tokenUrl: { type: "string" },
      refreshUrl: { type: "string" },
      requestTokenUrl: { type: "string", description: "OAuth1 request token endpoint" },
      accessTokenUrl: { type: "string", description: "OAuth1 access token endpoint" },
      defaultScopes: { type: "array", items: { type: "string" } },
      scopeSeparator: { type: "string" },
      pkceEnabled: { type: "boolean" },
      tokenAuthMethod: { type: "string", enum: ["client_secret_post", "client_secret_basic"] },
      authorizationParams: { type: "object" },
      tokenParams: { type: "object" },
      credentialSchema: { type: "object" },
      credentialFieldName: { type: "string" },
      credentialHeaderName: { type: "string" },
      credentialHeaderPrefix: { type: "string" },
      availableScopes: {
        type: "array",
        items: {
          type: "object",
          properties: {
            value: { type: "string" },
            label: { type: "string" },
          },
        },
      },
      authorizedUris: { type: "array", items: { type: "string" } },
      allowAllUris: { type: "boolean" },
      iconUrl: { type: "string" },
      categories: { type: "array", items: { type: "string" } },
      docsUrl: { type: "string" },
      usedByFlows: { type: "integer" },
    },
  },
  ProviderConfigInput: {
    type: "object",
    required: ["id", "displayName", "authMode"],
    properties: {
      id: { type: "string", pattern: "^[a-z0-9][a-z0-9-]*$" },
      displayName: { type: "string" },
      authMode: {
        type: "string",
        enum: ["oauth2", "oauth1", "api_key", "basic", "custom", "proxy"],
      },
      clientId: { type: "string" },
      clientSecret: { type: "string" },
      authorizationUrl: { type: "string" },
      tokenUrl: { type: "string" },
      refreshUrl: { type: "string" },
      requestTokenUrl: { type: "string", description: "OAuth1 request token endpoint" },
      accessTokenUrl: { type: "string", description: "OAuth1 access token endpoint" },
      defaultScopes: { type: "array", items: { type: "string" } },
      scopeSeparator: { type: "string" },
      pkceEnabled: { type: "boolean" },
      tokenAuthMethod: { type: "string", enum: ["client_secret_post", "client_secret_basic"] },
      authorizationParams: { type: "object" },
      tokenParams: { type: "object" },
      credentialSchema: { type: "object" },
      credentialFieldName: { type: "string" },
      credentialHeaderName: { type: "string" },
      credentialHeaderPrefix: { type: "string" },
      availableScopes: {
        type: "array",
        items: {
          type: "object",
          properties: {
            value: { type: "string" },
            label: { type: "string" },
          },
        },
      },
      iconUrl: { type: "string" },
      categories: { type: "array", items: { type: "string" } },
      docsUrl: { type: "string" },
      authorizedUris: { type: "array", items: { type: "string" } },
      allowAllUris: { type: "boolean" },
    },
  },
  ApiKeyInfo: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      keyPrefix: { type: "string", description: "First 8 chars of the key for identification" },
      scopes: {
        type: "array",
        items: { type: "string" },
        description: "Currently empty (admin access). Future: granular permissions.",
      },
      createdBy: { type: "string" },
      createdByName: { type: "string" },
      expiresAt: { type: "string", format: "date-time" },
      lastUsedAt: { type: "string", format: "date-time" },
      revokedAt: { type: "string", format: "date-time" },
      createdAt: { type: "string", format: "date-time" },
    },
  },
  OrgPackageItem: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: ["string", "null"] },
      description: { type: ["string", "null"] },
      source: { type: "string", enum: ["system", "local"] },
      createdBy: { type: ["string", "null"] },
      createdByName: { type: "string" },
      usedByFlows: { type: "integer" },
      version: { type: ["string", "null"], description: "Manifest version (semver)" },
      autoInstalled: { type: "boolean" },
      forkedFrom: { type: ["string", "null"], description: "Source package ID if forked" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  OrgPackageItemDetail: {
    type: "object",
    properties: {
      id: { type: "string" },
      name: { type: ["string", "null"] },
      description: { type: ["string", "null"] },
      content: { type: "string", description: "Package item content" },
      source: { type: "string", enum: ["system", "local"] },
      createdBy: { type: ["string", "null"] },
      createdByName: { type: "string" },
      usedByFlows: { type: "integer" },
      autoInstalled: { type: "boolean" },
      version: { type: ["string", "null"], description: "Manifest version (semver)" },
      manifest: { type: "object", description: "Full manifest object" },
      manifestName: {
        type: ["string", "null"],
        description: "Manifest name (@scope/name) — may differ from package ID",
      },
      forkedFrom: { type: ["string", "null"], description: "Source package ID if forked" },
      flows: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: { type: "string" },
            displayName: { type: "string" },
          },
        },
      },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  ShareFlowInfo: {
    type: "object",
    properties: {
      displayName: { type: "string" },
      description: { type: "string" },
      input: {
        type: "object",
        properties: {
          schema: { type: "object" },
        },
      },
      providers: { type: "array", items: { type: "object" } },
      consumed: { type: "boolean" },
      execution: {
        type: "object",
        properties: {
          id: { type: "string" },
          status: { type: "string" },
          result: { type: "object" },
          error: { type: "string" },
        },
      },
    },
  },
  FlowMemory: {
    type: "object",
    properties: {
      id: { type: "integer" },
      content: { type: "string" },
      executionId: { type: ["string", "null"] },
      createdAt: { type: ["string", "null"], format: "date-time" },
    },
  },
  OrgProxy: {
    type: "object",
    properties: {
      id: { type: "string" },
      label: { type: "string" },
      urlPrefix: { type: "string", description: "Masked proxy URL for display" },
      enabled: { type: "boolean" },
      isDefault: { type: "boolean" },
      source: { type: "string", enum: ["built-in", "custom"] },
      createdBy: { type: ["string", "null"] },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
} as const;
