// SPDX-License-Identifier: Apache-2.0

/**
 * Generate TypeScript types for the web SPA from the OpenAPI specification.
 *
 * The OpenAPI spec (assembled from `apps/api/src/openapi/` plus built-in
 * module contributions) is the single source of truth for the wire format.
 * This script turns it into `apps/web/src/api/schema.d.ts` via
 * openapi-typescript, so the frontend's typed client (openapi-fetch) is
 * checked against the exact same contract that `verify:openapi` and
 * `detect:breaking` enforce on the backend.
 *
 * The generated file is committed. The `--check` mode regenerates in memory
 * and fails if the committed file is stale — wired into `bun run check` so a
 * spec change without regeneration breaks CI instead of silently drifting.
 *
 * Usage:
 *   bun scripts/generate-api-types.ts          # write apps/web/src/api/schema.d.ts
 *   bun scripts/generate-api-types.ts --check  # CI gate: fail if file is stale
 */
import { resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import { buildOpenApiSpec } from "../apps/api/src/openapi/index.ts";
import { collectModuleOpenApi } from "./lib/module-openapi.ts";

const OUTPUT_PATH = resolve(import.meta.dir, "../apps/web/src/api/schema.d.ts");
const RELATIVE_OUTPUT = "apps/web/src/api/schema.d.ts";

const BANNER = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-api-types.ts — DO NOT EDIT.
// Source of truth: apps/api/src/openapi/ (+ built-in module contributions).
// Regenerate with: bun run generate:api

`;

/** Codepoint-order key sort — deterministic across platforms and locales. */
function sortKeys<T>(obj: Record<string, T>): Record<string, T> {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
}

async function generate(): Promise<string> {
  // Built-in modules (e.g. webhooks) contribute paths the web SPA may call,
  // so they are included — same discovery as verify-openapi/detect-breaking.
  const { paths, componentSchemas, tags } = await collectModuleOpenApi();
  const spec = buildOpenApiSpec(paths, componentSchemas, tags) as {
    paths?: Record<string, unknown>;
    components?: { schemas?: Record<string, unknown> };
  };

  // Canonicalize object key order before emitting types: the merged spec's
  // key order depends on module discovery order, and `--check` byte-compares
  // the output across machines. Sorting here keeps the committed file
  // independent of where it was generated.
  if (spec.paths) spec.paths = sortKeys(spec.paths);
  if (spec.components?.schemas) spec.components.schemas = sortKeys(spec.components.schemas);

  const ast = await openapiTS(JSON.parse(JSON.stringify(spec)), {
    // Wire enums stay string literal unions (default) — keep options explicit
    // and minimal so output stays stable across openapi-typescript upgrades.
    defaultNonNullable: true,
  });

  return BANNER + astToString(ast);
}

const checkMode = process.argv.includes("--check");
const generated = await generate();

if (checkMode) {
  const existing = await Bun.file(OUTPUT_PATH)
    .text()
    .catch(() => null);
  if (existing === generated) {
    console.log(`✅ ${RELATIVE_OUTPUT} is up to date with the OpenAPI spec`);
    process.exit(0);
  }
  console.error(
    `❌ ${RELATIVE_OUTPUT} is stale — the OpenAPI spec changed without regenerating types.\n` +
      `   Run: bun run generate:api`,
  );
  process.exit(1);
}

await Bun.write(OUTPUT_PATH, generated);
console.log(`✅ wrote ${RELATIVE_OUTPUT}`);
// Module discovery imports may open Redis subscriptions as side effects —
// exit explicitly so the script doesn't hang on open handles.
process.exit(0);
