// SPDX-License-Identifier: Apache-2.0
/// <reference types="bun" />

/**
 * The repo's ESLint entrypoint — `bun run lint` (and `lint:fix`).
 *
 * It exists for one reason: to scope ESLint to TRACKED content instead of the
 * working tree.
 *
 * ─── Why not `eslint .` ──────────────────────────────────────────────
 *
 * `eslint .` walks the filesystem, so its scope is "every file on this
 * developer's disk that the config matches, minus `.eslintignore`-style
 * `ignores`". Since `eslint.config.mjs` was widened from a six-glob directory
 * roster to `**\/*.{ts,tsx}` — a real fix, five tracked files had been covered
 * by nothing — that scope includes any untracked, non-gitignored `.ts`
 * anywhere in the tree. Measured on this branch: an untracked
 * `zz-probe/p.ts` containing `export const a: any = 1;` failed `bun run lint`,
 * which fails `bun run check`, which fails `.husky/pre-push`. A scratch file
 * nobody intends to commit could block a push.
 *
 * The tracked-file rule and the reasoning behind it now live in
 * `scripts/lib/tracked-files.ts`, shared with the two sibling gates
 * (`lint-manifest-casing.ts`, `verify-compose-defaults.ts`) that had each
 * written their own copy of it.
 *
 * ─── Why a script and not a shell one-liner in package.json ──────────
 *
 * `eslint $(git ls-files …)` bets on the shell's word-splitting; `bun run`
 * executes scripts through its own shell, which is not the interactive one and
 * not a POSIX sh either. And `git ls-files | xargs eslint` is worse: xargs may
 * split the list into SEVERAL eslint invocations, which breaks both `--cache`
 * (each run rewrites `.eslintcache` from its own subset) and the exit code
 * (only the last invocation's survives without extra plumbing).
 *
 * Neither is needed. Measured 2026-08-25: 2201 tracked
 * `.ts/.tsx/.js/.jsx/.mjs/.cjs` files, 101 795 bytes of argv, against this
 * machine's `getconf ARG_MAX` of 1 048 576 — a single invocation fits with an
 * order of magnitude to spare, so the file list is passed in one `spawn`.
 *
 * Any extra argument is forwarded to eslint verbatim, which is what makes
 * `lint:fix` (`--fix`) the same scope as `lint` rather than a second
 * definition of it.
 *
 * `//#lint`'s turbo `inputs` mirror this scope — see the note there.
 */

import { ESLint } from "eslint";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { missingFromWorktree, SOURCE_GLOBS, trackedIndexFiles } from "./lib/tracked-files.ts";

const REPO_ROOT = join(import.meta.dir, "..");

/**
 * The tracked files eslint's top-level `ignores` block removes from its scope.
 *
 * Naming files on the command line turns "this file is in `ignores`" from a
 * silent skip into a `File ignored because of a matching ignore pattern`
 * warning — which is the ONLY signal a caller gets that the config just
 * un-scoped something. The version of this file that this replaces answered
 * that one warning line with `--no-warn-ignored`, and that flag does not
 * silence one path, it silences the mechanism: measured 2026-08-25, adding
 * `"apps/**"` to the `ignores` array made `bun run lint` hand eslint 2204
 * paths, get an empty result for ~2100 of them, print ZERO bytes and exit 0.
 * `bun run check` went green over an unlinted API and SPA with no line of
 * output saying so.
 *
 * So the set is asserted instead of muted. Every entry below must still be
 * ignored (a stale entry means the exclusion is now covering whatever lands at
 * that path next) and nothing else may be — same liveness rule, and same
 * reasoning, as `deadExclusions()` in `scripts/lint-manifest-casing.ts`.
 *
 * One entry today, and measured rather than assumed: `apps/web/src/api/schema.d.ts`
 * is generated by `scripts/generate-api-types.ts` and is the only tracked file
 * eslint's `ignores` removes.
 *
 * Liveness is checked against the git INDEX, not against the working tree, and
 * the difference is a gate somebody has to be able to unblock. That one entry
 * is a GENERATED file, so `rm` + regenerate is its ordinary flow; when the
 * liveness list was the on-disk one, the gap between the two commands failed
 * lint — hence check, hence pre-push — with `The path moved, or it stopped
 * being ignored`, neither of which had happened. Asking the index instead keeps
 * both real drifts (an entry deleted from the index, an entry the config
 * stopped ignoring) and drops the one that was never drift.
 */
export const KNOWN_IGNORED: readonly string[] = ["apps/web/src/api/schema.d.ts"];

/**
 * The ignored set is exactly `KNOWN_IGNORED` — no more, no fewer.
 *
 * Pure, so `scripts/test/lint.test.ts` can hold both failure directions against
 * it without an eslint run: a widened `ignores` (files eslint would skip in
 * silence) and a dead entry (an exclusion that stopped excluding).
 */
export function assertIgnoredSetIsExact(ignored: readonly string[]): void {
  const unexpected = ignored.filter((file) => !KNOWN_IGNORED.includes(file));
  const dead = KNOWN_IGNORED.filter((file) => !ignored.includes(file));
  if (unexpected.length === 0 && dead.length === 0) return;

  const parts: string[] = [];
  if (unexpected.length > 0) {
    parts.push(
      `${unexpected.length} tracked file(s) are excluded by \`ignores\` in eslint.config.mjs but ` +
        `are not listed in KNOWN_IGNORED (scripts/lint.ts):\n` +
        unexpected
          .slice(0, 20)
          .map((f) => `  - ${f}`)
          .join("\n") +
        (unexpected.length > 20 ? `\n  … and ${unexpected.length - 20} more` : "") +
        `\nESLint reports nothing at all for these, so leaving them unlisted means \`bun run lint\`` +
        `\nexits 0 over code no rule ever saw. Either narrow the \`ignores\` pattern, or add the` +
        `\npaths here with the reason they are generated/vendored.`,
    );
  }
  if (dead.length > 0) {
    parts.push(
      `${dead.length} KNOWN_IGNORED entr(y|ies) in scripts/lint.ts no longer match an ignored ` +
        `tracked file:\n` +
        dead.map((f) => `  - ${f}`).join("\n") +
        `\nThe path moved, it left the git index, or it stopped being ignored. An entry that` +
        `\nmatches nothing today would silently excuse whatever appears at that path tomorrow —` +
        `\ndelete it, or repoint it.`,
    );
  }
  throw new Error(`lint: eslint's ignored set has drifted.\n\n${parts.join("\n\n")}`);
}

/**
 * Split the tracked files into the ones eslint has a configuration for and the
 * ones its `ignores` block removes.
 *
 * `isIgnored` is injected so the split is testable; production passes
 * `ESLint#isPathIgnored`, which reads the very config the gate runs under.
 * Cost measured over the 2204 tracked files: 584 ms, against eslint's own ~20 s.
 */
export async function partitionIgnored(
  files: readonly string[],
  isIgnored: (file: string) => Promise<boolean> | boolean,
): Promise<{ lintable: string[]; ignored: string[] }> {
  const lintable: string[] = [];
  const ignored: string[] = [];
  for (const file of files) {
    if (await isIgnored(file)) ignored.push(file);
    else lintable.push(file);
  }
  return { lintable, ignored };
}

/**
 * A dialect this config is supposed to have rules for, and the floor under the
 * number of them eslint actually resolves for it.
 *
 * ─── Why a count, when the ignored set is already asserted ───────────
 *
 * `KNOWN_IGNORED` partitions the tracked files into "eslint has a config for
 * this" and "eslint skips this". That partition is orthogonal to whether the
 * config it has says anything. Measured 2026-08-25: taking the 70 rules
 * currently enabled for a `.ts` file and appending one config object setting
 * all 70 to `"off"`, plus a real seeded error, gave GATE EXIT=0 — `bun run
 * lint` reporting success over 2206 files with every TypeScript rule disabled,
 * printing nothing but `Unused eslint-disable directive` warnings. No file had
 * become IGNORED, so the partition was undisturbed and had nothing to say. That
 * is the same "green over an unlinted repo" outcome `KNOWN_IGNORED` exists to
 * prevent, reached through the other door.
 *
 * This is the instrument `MIN_SCHEMA_KEYS` already is in the sibling gate
 * `scripts/verify-compose-defaults.ts` — a floor under the thing the gate
 * measures WITH, checked before its output is trusted. Applying it there and
 * not here was the asymmetry.
 *
 * ─── The numbers are a FLOOR, not a pin ──────────────────────────────
 *
 * Retiring a rule is ordinary and must not fail this gate; switching the config
 * off wholesale must. So each floor sits well under its measurement, and the
 * failure text says so. Measured 2026-08-25 via
 * `ESLint#calculateConfigForFile`, counting entries whose severity is neither
 * `0` nor `"off"`:
 *
 *     apps/api/src/index.ts   70 enabled  (451 resolved)
 *     apps/web/src/main.tsx   92 enabled  (473 resolved)
 *     eslint.config.mjs       63 enabled  (421 resolved)
 *
 * Re-measure with those three calls — `new ESLint({ cwd })`, then
 * `calculateConfigForFile(file)` — and read `rules`. Raise a floor only after
 * re-measuring; never lower one to make a red gate green.
 *
 * The three files are the three dialects the config treats differently: a `.ts`
 * under the TypeScript blocks, a `.tsx` (which adds the React and
 * `apps/web`-scoped rules), and `eslint.config.mjs` itself, whose only cover is
 * the plain-JS `js.configs.recommended` block — the file that decides every
 * rule in this repo, and the one that used to be linted by nothing.
 */
export const RULE_COVERAGE_FLOORS: readonly { file: string; min: number }[] = [
  { file: "apps/api/src/index.ts", min: 55 },
  { file: "apps/web/src/main.tsx", min: 70 },
  { file: "eslint.config.mjs", min: 50 },
];

/**
 * How many of a resolved config's rules are actually ON.
 *
 * `calculateConfigForFile` returns every rule any matched config object
 * mentions, `"off"` ones included — `tseslint.configs.recommended` alone turns
 * dozens off explicitly. Counting keys would therefore count a config that
 * disables everything as fully covered, which is the mutation this exists to
 * catch, so severity is read: `0` / `"off"` do not count, and an array form
 * (`["error", {...}]`) is judged on its first element.
 *
 * Pure, so `scripts/test/lint.test.ts` can hold both directions against it.
 */
export function countEnabledRules(rules: Record<string, unknown> | undefined): number {
  if (!rules) return 0;
  return Object.values(rules).filter((value) => {
    const severity = Array.isArray(value) ? value[0] : value;
    return severity !== 0 && severity !== "off" && severity !== undefined;
  }).length;
}

/**
 * Every dialect still resolves at least its floor's worth of enabled rules.
 *
 * Takes the measurement rather than making it, so the test file can assert both
 * directions without an eslint run.
 */
export function assertRuleCoverage(measured: ReadonlyMap<string, number>): void {
  const under = RULE_COVERAGE_FLOORS.filter(({ file, min }) => (measured.get(file) ?? 0) < min);
  if (under.length === 0) return;

  throw new Error(
    `lint: eslint resolves fewer enabled rules than this repo's floor.\n\n` +
      under
        .map(
          ({ file, min }) =>
            `  - ${file}: ${measured.get(file) ?? 0} enabled rule(s), floor ${min}`,
        )
        .join("\n") +
      `\n\nA config that matches every file and enables nothing lints every file and finds` +
      `\nnothing, and \`bun run lint\` exits 0 over it — the ignored-set assertion above cannot` +
      `\nsee that, because no file became ignored. These floors sit well under the measured` +
      `\ncounts (see RULE_COVERAGE_FLOORS) so that retiring a rule never trips them. If a rule` +
      `\nset was deliberately shrunk this far, re-measure and raise the floor in scripts/lint.ts` +
      `\nwith the new number — do not lower it to make this green.`,
  );
}

/** The floors' subject files, measured against the config the gate runs under. */
export async function measureRuleCoverage(api: ESLint): Promise<Map<string, number>> {
  const measured = new Map<string, number>();
  for (const { file } of RULE_COVERAGE_FLOORS) {
    const config = (await api.calculateConfigForFile(file)) as
      { rules?: Record<string, unknown> } | undefined;
    measured.set(file, countEnabledRules(config?.rules));
  }
  return measured;
}

async function main(): Promise<number> {
  // The INDEX list, not the on-disk one: `assertIgnoredSetIsExact` below asks
  // whether each KNOWN_IGNORED entry is still an ignored TRACKED file, and a
  // generated file between its `rm` and its regeneration is still tracked. The
  // existence question is answered further down, where it belongs — on the list
  // actually handed to eslint.
  const indexed = trackedIndexFiles(SOURCE_GLOBS, "lintable file");

  const api = new ESLint({ cwd: REPO_ROOT });
  const { lintable, ignored } = await partitionIgnored(indexed, (file) => api.isPathIgnored(file));
  assertIgnoredSetIsExact(ignored);
  assertRuleCoverage(await measureRuleCoverage(api));

  // eslint is handed paths it can open. A tracked file missing from the working
  // tree is a `git rm` not yet committed or a refactor in flight — not a lint
  // finding, and not a reason to fail a push. (The compose gate next door makes
  // the opposite choice, for the opposite reason; see `MissingFilePolicy`.)
  const missing = new Set(missingFromWorktree(lintable));
  const present = lintable.filter((file) => !missing.has(file));
  if (present.length === 0) {
    throw new Error(
      `lint: all ${lintable.length} lintable tracked file(s) are missing from the working tree — ` +
        `eslint would be handed nothing and exit 0.`,
    );
  }

  const eslint = join(REPO_ROOT, "node_modules/.bin/eslint");
  if (!existsSync(eslint)) {
    throw new Error(`${eslint} not found — run \`bun install\`.`);
  }

  // No `--no-warn-ignored`: the ignored files are already out of `lintable`, so
  // there is no warning left to suppress, and a file eslint skips for the OTHER
  // reason ("no matching configuration was supplied") still gets to say so.
  const proc = Bun.spawnSync({
    cmd: [eslint, "--cache", "--cache-strategy", "content", ...Bun.argv.slice(2), ...present],
    cwd: REPO_ROOT,
    stdio: ["inherit", "inherit", "inherit"],
  });
  return proc.exitCode ?? 1;
}

// Guarded so `scripts/test/lint.test.ts` can import the pure helpers above
// without spawning eslint and exiting the test process — same pattern as
// `verify-compose-defaults.ts` and `check-index-drift.ts`.
if (import.meta.main) {
  process.exit(await main());
}
