// SPDX-License-Identifier: Apache-2.0
/// <reference types="bun" />

/**
 * The repo's ESLint entrypoint — `bun run lint` (and `lint:fix`).
 *
 * It exists for one reason: to scope ESLint to TRACKED content instead of the
 * working tree.
 *
 * ─── Why not `eslint .` ──────────────────────────────────────────────
 *
 * `eslint .` walks the filesystem, so its scope is "every file on this
 * developer's disk that the config matches, minus `.eslintignore`-style
 * `ignores`". Since `eslint.config.mjs` was widened from a six-glob directory
 * roster to `**\/*.{ts,tsx}` — a real fix, five tracked files had been covered
 * by nothing — that scope includes any untracked, non-gitignored `.ts`
 * anywhere in the tree. Measured on this branch: an untracked
 * `zz-probe/p.ts` containing `export const a: any = 1;` failed `bun run lint`,
 * which fails `bun run check`, which fails `.husky/pre-push`. A scratch file
 * nobody intends to commit could block a push.
 *
 * The tracked-file rule and the reasoning behind it now live in
 * `scripts/lib/tracked-files.ts`, shared with the two sibling gates
 * (`lint-manifest-casing.ts`, `verify-compose-defaults.ts`) that had each
 * written their own copy of it.
 *
 * ─── Why a script and not a shell one-liner in package.json ──────────
 *
 * `eslint $(git ls-files …)` bets on the shell's word-splitting; `bun run`
 * executes scripts through its own shell, which is not the interactive one and
 * not a POSIX sh either. And `git ls-files | xargs eslint` is worse: xargs may
 * split the list into SEVERAL eslint invocations, which breaks both `--cache`
 * (each run rewrites `.eslintcache` from its own subset) and the exit code
 * (only the last invocation's survives without extra plumbing).
 *
 * Neither is needed. Measured 2026-08-25: 2201 tracked
 * `.ts/.tsx/.js/.jsx/.mjs/.cjs` files, 101 795 bytes of argv, against this
 * machine's `getconf ARG_MAX` of 1 048 576 — a single invocation fits with an
 * order of magnitude to spare, so the file list is passed in one `spawn`.
 *
 * Any extra argument is forwarded to eslint verbatim, which is what makes
 * `lint:fix` (`--fix`) the same scope as `lint` rather than a second
 * definition of it.
 *
 * `//#lint`'s turbo `inputs` mirror this scope — see the note there.
 */

import { ESLint } from "eslint";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { SOURCE_GLOBS, trackedFiles } from "./lib/tracked-files.ts";

const REPO_ROOT = join(import.meta.dir, "..");

/**
 * The tracked files eslint's top-level `ignores` block removes from its scope.
 *
 * Naming files on the command line turns "this file is in `ignores`" from a
 * silent skip into a `File ignored because of a matching ignore pattern`
 * warning — which is the ONLY signal a caller gets that the config just
 * un-scoped something. The version of this file that this replaces answered
 * that one warning line with `--no-warn-ignored`, and that flag does not
 * silence one path, it silences the mechanism: measured 2026-08-25, adding
 * `"apps/**"` to the `ignores` array made `bun run lint` hand eslint 2204
 * paths, get an empty result for ~2100 of them, print ZERO bytes and exit 0.
 * `bun run check` went green over an unlinted API and SPA with no line of
 * output saying so.
 *
 * So the set is asserted instead of muted. Every entry below must still be
 * ignored (a stale entry means the exclusion is now covering whatever lands at
 * that path next) and nothing else may be — same liveness rule, and same
 * reasoning, as `deadExclusions()` in `scripts/lint-manifest-casing.ts`.
 *
 * One entry today, and measured rather than assumed: `apps/web/src/api/schema.d.ts`
 * is generated by `scripts/generate-api-types.ts` and is the only tracked file
 * eslint's `ignores` removes.
 */
export const KNOWN_IGNORED: readonly string[] = ["apps/web/src/api/schema.d.ts"];

/**
 * The ignored set is exactly `KNOWN_IGNORED` — no more, no fewer.
 *
 * Pure, so `scripts/test/lint.test.ts` can hold both failure directions against
 * it without an eslint run: a widened `ignores` (files eslint would skip in
 * silence) and a dead entry (an exclusion that stopped excluding).
 */
export function assertIgnoredSetIsExact(ignored: readonly string[]): void {
  const unexpected = ignored.filter((file) => !KNOWN_IGNORED.includes(file));
  const dead = KNOWN_IGNORED.filter((file) => !ignored.includes(file));
  if (unexpected.length === 0 && dead.length === 0) return;

  const parts: string[] = [];
  if (unexpected.length > 0) {
    parts.push(
      `${unexpected.length} tracked file(s) are excluded by \`ignores\` in eslint.config.mjs but ` +
        `are not listed in KNOWN_IGNORED (scripts/lint.ts):\n` +
        unexpected
          .slice(0, 20)
          .map((f) => `  - ${f}`)
          .join("\n") +
        (unexpected.length > 20 ? `\n  … and ${unexpected.length - 20} more` : "") +
        `\nESLint reports nothing at all for these, so leaving them unlisted means \`bun run lint\`` +
        `\nexits 0 over code no rule ever saw. Either narrow the \`ignores\` pattern, or add the` +
        `\npaths here with the reason they are generated/vendored.`,
    );
  }
  if (dead.length > 0) {
    parts.push(
      `${dead.length} KNOWN_IGNORED entr(y|ies) in scripts/lint.ts no longer match an ignored ` +
        `tracked file:\n` +
        dead.map((f) => `  - ${f}`).join("\n") +
        `\nThe path moved, or it stopped being ignored. An entry that matches nothing today` +
        `\nwould silently excuse whatever appears at that path tomorrow — delete it, or repoint it.`,
    );
  }
  throw new Error(`lint: eslint's ignored set has drifted.\n\n${parts.join("\n\n")}`);
}

/**
 * Split the tracked files into the ones eslint has a configuration for and the
 * ones its `ignores` block removes.
 *
 * `isIgnored` is injected so the split is testable; production passes
 * `ESLint#isPathIgnored`, which reads the very config the gate runs under.
 * Cost measured over the 2204 tracked files: 584 ms, against eslint's own ~20 s.
 */
export async function partitionIgnored(
  files: readonly string[],
  isIgnored: (file: string) => Promise<boolean> | boolean,
): Promise<{ lintable: string[]; ignored: string[] }> {
  const lintable: string[] = [];
  const ignored: string[] = [];
  for (const file of files) {
    if (await isIgnored(file)) ignored.push(file);
    else lintable.push(file);
  }
  return { lintable, ignored };
}

async function main(): Promise<number> {
  const files = trackedFiles(SOURCE_GLOBS, "lintable file");

  const api = new ESLint({ cwd: REPO_ROOT });
  const { lintable, ignored } = await partitionIgnored(files, (file) => api.isPathIgnored(file));
  assertIgnoredSetIsExact(ignored);

  const eslint = join(REPO_ROOT, "node_modules/.bin/eslint");
  if (!existsSync(eslint)) {
    throw new Error(`${eslint} not found — run \`bun install\`.`);
  }

  // No `--no-warn-ignored`: the ignored files are already out of `lintable`, so
  // there is no warning left to suppress, and a file eslint skips for the OTHER
  // reason ("no matching configuration was supplied") still gets to say so.
  const proc = Bun.spawnSync({
    cmd: [eslint, "--cache", "--cache-strategy", "content", ...Bun.argv.slice(2), ...lintable],
    cwd: REPO_ROOT,
    stdio: ["inherit", "inherit", "inherit"],
  });
  return proc.exitCode ?? 1;
}

// Guarded so `scripts/test/lint.test.ts` can import the pure helpers above
// without spawning eslint and exiting the test process — same pattern as
// `verify-compose-defaults.ts` and `check-index-drift.ts`.
if (import.meta.main) {
  process.exit(await main());
}
