// SPDX-License-Identifier: Apache-2.0
/// <reference types="bun" />

/**
 * The repo's ESLint entrypoint — `bun run lint` (and `lint:fix`).
 *
 * It exists for one reason: to scope ESLint to TRACKED content instead of the
 * working tree.
 *
 * ─── Why not `eslint .` ──────────────────────────────────────────────
 *
 * `eslint .` walks the filesystem, so its scope is "every file on this
 * developer's disk that the config matches, minus `.eslintignore`-style
 * `ignores`". Since `eslint.config.mjs` was widened from a six-glob directory
 * roster to `**\/*.{ts,tsx}` — a real fix, five tracked files had been covered
 * by nothing — that scope includes any untracked, non-gitignored `.ts`
 * anywhere in the tree. Measured on this branch: an untracked
 * `zz-probe/p.ts` containing `export const a: any = 1;` failed `bun run lint`,
 * which fails `bun run check`, which fails `.husky/pre-push`. A scratch file
 * nobody intends to commit could block a push.
 *
 * The tracked-file rule and the reasoning behind it now live in
 * `scripts/lib/tracked-files.ts`, shared with the two sibling gates
 * (`lint-manifest-casing.ts`, `verify-compose-defaults.ts`) that had each
 * written their own copy of it.
 *
 * ─── Why a script and not a shell one-liner in package.json ──────────
 *
 * `eslint $(git ls-files …)` bets on the shell's word-splitting; `bun run`
 * executes scripts through its own shell, which is not the interactive one and
 * not a POSIX sh either. And `git ls-files | xargs eslint` is worse: xargs may
 * split the list into SEVERAL eslint invocations, which breaks both `--cache`
 * (each run rewrites `.eslintcache` from its own subset) and the exit code
 * (only the last invocation's survives without extra plumbing).
 *
 * Neither is needed. Measured 2026-08-25: 2201 tracked
 * `.ts/.tsx/.js/.jsx/.mjs/.cjs` files, 101 795 bytes of argv, against this
 * machine's `getconf ARG_MAX` of 1 048 576 — a single invocation fits with an
 * order of magnitude to spare, so the file list is passed in one `spawn`.
 *
 * Any extra argument is forwarded to eslint verbatim, which is what makes
 * `lint:fix` (`--fix`) the same scope as `lint` rather than a second
 * definition of it.
 *
 * `//#lint`'s turbo `inputs` mirror this scope — see the note there.
 */

import { ESLint } from "eslint";
import { existsSync } from "node:fs";
import { join } from "node:path";
import {
  applyMissingFilePolicy,
  missingFromWorktree,
  SOURCE_GLOBS,
  trackedIndexFiles,
} from "./lib/tracked-files.ts";

const REPO_ROOT = join(import.meta.dir, "..");

/**
 * The tracked files eslint's top-level `ignores` block removes from its scope.
 *
 * Naming files on the command line turns "this file is in `ignores`" from a
 * silent skip into a `File ignored because of a matching ignore pattern`
 * warning — which is the ONLY signal a caller gets that the config just
 * un-scoped something. The version of this file that this replaces answered
 * that one warning line with `--no-warn-ignored`, and that flag does not
 * silence one path, it silences the mechanism: measured 2026-08-25, adding
 * `"apps/**"` to the `ignores` array made `bun run lint` hand eslint 2204
 * paths, get an empty result for ~2100 of them, print ZERO bytes and exit 0.
 * `bun run check` went green over an unlinted API and SPA with no line of
 * output saying so.
 *
 * So the set is asserted instead of muted. Every entry below must still be
 * ignored (a stale entry means the exclusion is now covering whatever lands at
 * that path next) and nothing else may be — same liveness rule, and same
 * reasoning, as `deadExclusions()` in `scripts/lint-manifest-casing.ts`.
 *
 * One entry today, and measured rather than assumed: `apps/web/src/api/schema.d.ts`
 * is generated by `scripts/generate-api-types.ts` and is the only tracked file
 * eslint's `ignores` removes.
 *
 * Liveness is checked against the git INDEX, not against the working tree, and
 * the difference is a gate somebody has to be able to unblock. That one entry
 * is a GENERATED file, so `rm` + regenerate is its ordinary flow; when the
 * liveness list was the on-disk one, the gap between the two commands failed
 * lint — hence check, hence pre-push — with `The path moved, or it stopped
 * being ignored`, neither of which had happened. Asking the index instead keeps
 * both real drifts (an entry deleted from the index, an entry the config
 * stopped ignoring) and drops the one that was never drift.
 */
export const KNOWN_IGNORED: readonly string[] = ["apps/web/src/api/schema.d.ts"];

/**
 * The ignored set is exactly `KNOWN_IGNORED` — no more, no fewer.
 *
 * Pure, so `scripts/test/lint.test.ts` can hold both failure directions against
 * it without an eslint run: a widened `ignores` (files eslint would skip in
 * silence) and a dead entry (an exclusion that stopped excluding).
 */
export function assertIgnoredSetIsExact(ignored: readonly string[]): void {
  const unexpected = ignored.filter((file) => !KNOWN_IGNORED.includes(file));
  const dead = KNOWN_IGNORED.filter((file) => !ignored.includes(file));
  if (unexpected.length === 0 && dead.length === 0) return;

  const parts: string[] = [];
  if (unexpected.length > 0) {
    parts.push(
      `${unexpected.length} tracked file(s) are excluded by \`ignores\` in eslint.config.mjs but ` +
        `are not listed in KNOWN_IGNORED (scripts/lint.ts):\n` +
        unexpected
          .slice(0, 20)
          .map((f) => `  - ${f}`)
          .join("\n") +
        (unexpected.length > 20 ? `\n  … and ${unexpected.length - 20} more` : "") +
        `\nESLint reports nothing at all for these, so leaving them unlisted means \`bun run lint\`` +
        `\nexits 0 over code no rule ever saw. Either narrow the \`ignores\` pattern, or add the` +
        `\npaths here with the reason they are generated/vendored.`,
    );
  }
  if (dead.length > 0) {
    parts.push(
      `${dead.length} KNOWN_IGNORED entr(y|ies) in scripts/lint.ts no longer match an ignored ` +
        `tracked file:\n` +
        dead.map((f) => `  - ${f}`).join("\n") +
        `\nThe path moved, it left the git index, or it stopped being ignored. An entry that` +
        `\nmatches nothing today would silently excuse whatever appears at that path tomorrow —` +
        `\ndelete it, or repoint it.`,
    );
  }
  throw new Error(`lint: eslint's ignored set has drifted.\n\n${parts.join("\n\n")}`);
}

/**
 * Split the tracked files into the ones eslint has a configuration for and the
 * ones its `ignores` block removes.
 *
 * `isIgnored` is injected so the split is testable; production passes
 * `ESLint#isPathIgnored`, which reads the very config the gate runs under.
 * Cost measured over the 2204 tracked files: 584 ms, against eslint's own ~20 s.
 */
export async function partitionIgnored(
  files: readonly string[],
  isIgnored: (file: string) => Promise<boolean> | boolean,
): Promise<{ lintable: string[]; ignored: string[] }> {
  const lintable: string[] = [];
  const ignored: string[] = [];
  for (const file of files) {
    if (await isIgnored(file)) ignored.push(file);
    else lintable.push(file);
  }
  return { lintable, ignored };
}

/**
 * Rules whose absence is not a style regression but a boundary coming down.
 *
 * Named, not counted. A floor on the NUMBER of enabled rules was tried here and
 * removed: it cost ~190 lines, and its counterfactual — disable everything —
 * only ever passed because the handful of rules that carry an `eslint-disable`
 * somewhere in the repo strand their directives when switched off, which
 * `--max-warnings 0` then catches. Measured: of the 70 rules enabled for a
 * `.ts` file, only five have such a directive. The other 65 can be turned off
 * in silence, and `no-restricted-imports` — which carries BOTH the
 * core-independence boundary and the `@earendil-works/pi-*` supply-chain ban —
 * is one of them. Verified before writing this: disabling it with a real
 * `import { getEnv } from "@appstrate/env"` seeded inside `packages/core/src`
 * gave exit 0 and zero bytes of output.
 *
 * Counting rules answers "is linting still happening". This answers "are the
 * rules that encode an architectural decision still in force", which is the
 * question worth failing a build over. Add to it when a rule starts carrying a
 * boundary rather than a preference.
 */
const LOAD_BEARING_RULES = [
  // Package boundaries + the SDK import ban (`eslint.config.mjs`).
  "no-restricted-imports",
  // Zod 4 migration bans and the other syntax-level architectural rules.
  "no-restricted-syntax",
  // A dropped symbol after a refactor is how dead boundaries go unnoticed.
  "@typescript-eslint/no-unused-vars",
  // The escape hatch out of every other type-level guarantee.
  "@typescript-eslint/no-explicit-any",
  // Failure legibility (PR #1161): a rethrow that drops the caught error
  // destroys the only record of what actually failed. This rule sat at "off"
  // in `eslint.config.mjs` — the file's one unjustified suppression — hiding
  // 20 such sites, so it is exactly the "switched off in silence" case this
  // list exists to catch.
  "preserve-caught-error",
] as const;

/**
 * A representative TypeScript source, taken from a package's `src` tree — not
 * from `packages` at large, which this check itself caught the moment it ran:
 * the first match there was `packages/afps-runtime/bin/afps.ts`, and a `bin`
 * entrypoint sits outside the config blocks that carry these rules, so the
 * guard failed on a healthy repo. Picked from the index rather than hardcoded,
 * so a rename cannot leave it pointing at nothing — which would make the check
 * pass over a file eslint never sees.
 */
async function assertLoadBearingRulesEnabled(api: ESLint): Promise<void> {
  const subject = trackedIndexFiles(["packages/*/src/**/*.ts"], "representative source")[0];
  if (subject === undefined) {
    throw new Error("lint: no tracked `packages/**/*.ts` — this check cannot run.");
  }
  const config = (await api.calculateConfigForFile(subject)) as {
    rules?: Record<string, unknown>;
  };
  const off = LOAD_BEARING_RULES.filter((name) => {
    const entry = config.rules?.[name];
    const severity = Array.isArray(entry) ? entry[0] : entry;
    return severity !== 2 && severity !== "error";
  });
  if (off.length > 0) {
    throw new Error(
      `lint: ${off.length} rule(s) that carry an architectural boundary are no longer ` +
        `errors for ${subject}:\n  - ${off.join("\n  - ")}\n` +
        `Each encodes a decision, not a preference — turning one off removes the ` +
        `boundary, silently, since a disabled rule reports nothing.\n` +
        `If a boundary genuinely moved, remove the rule from LOAD_BEARING_RULES in ` +
        `scripts/lint.ts in the same commit, so the removal is reviewable.`,
    );
  }
}

async function main(): Promise<number> {
  // The INDEX list, not the on-disk one: `assertIgnoredSetIsExact` below asks
  // whether each KNOWN_IGNORED entry is still an ignored TRACKED file, and a
  // generated file between its `rm` and its regeneration is still tracked. The
  // existence question is answered further down, where it belongs — on the list
  // actually handed to eslint.
  const indexed = trackedIndexFiles(SOURCE_GLOBS, "lintable file");

  const api = new ESLint({ cwd: REPO_ROOT });
  const { lintable, ignored } = await partitionIgnored(indexed, (file) => api.isPathIgnored(file));
  assertIgnoredSetIsExact(ignored);
  await assertLoadBearingRulesEnabled(api);

  // eslint is handed paths it can open. A tracked file missing from the working
  // tree is a `git rm` not yet committed or a refactor in flight — not a lint
  // finding, and not a reason to fail a push. (The compose gate next door makes
  // the opposite choice, for the opposite reason; see `MissingFilePolicy`.)
  //
  // The `"skip"` policy itself lives next to `"fail"` in `tracked-files.ts`, so
  // that both answers to the same question are written, and tested, in one
  // place. It cannot be reached through `trackedFiles` here: this gate needs the
  // INDEX list first, for the `KNOWN_IGNORED` liveness check above, and the
  // allowance applies to what survives the ignore partition.
  const present = applyMissingFilePolicy(
    lintable,
    missingFromWorktree(lintable),
    "lintable file",
    "skip",
  );

  const eslint = join(REPO_ROOT, "node_modules/.bin/eslint");
  if (!existsSync(eslint)) {
    throw new Error(`${eslint} not found — run \`bun install\`.`);
  }

  // No `--no-warn-ignored`: the ignored files are already out of `lintable`, so
  // there is no warning left to suppress, and a file eslint skips for the OTHER
  // reason ("no matching configuration was supplied") still gets to say so.
  //
  // `--max-warnings 0`, because eslint's exit code otherwise ignores warnings
  // entirely and "warn" becomes a severity that fails nothing. Measured
  // 2026-08-26: downgrading the 70 rules enabled for a `.ts` file from `"error"`
  // to `"warn"` gave `712 problems (0 errors, 712 warnings)` and GATE EXIT=0 —
  // the whole repo's TypeScript linting turned off, in a run that printed 712
  // findings and called itself a success.
  //
  // The repo's four deliberate `"warn"` rules stay `"warn"`: three under
  // `**\/test\/**` and `react-refresh/only-export-components`. Their severity is
  // an editor signal (a yellow squiggle rather than a red one) and this flag
  // does not change that; what it changes is that CI no longer treats them as
  // optional. The flag costs nothing today — measured 2026-08-26 on a COLD
  // cache, `bun scripts/lint.ts --max-warnings 0` printed zero bytes and exited
  // 0, so the repo currently emits zero warnings of any kind.
  //
  // It goes before `Bun.argv.slice(2)` so that a caller who genuinely wants a
  // budget (`bun run lint --max-warnings 20`) still wins: eslint takes the last
  // occurrence.
  const proc = Bun.spawnSync({
    cmd: [
      eslint,
      "--cache",
      "--cache-strategy",
      "content",
      "--max-warnings",
      "0",
      ...Bun.argv.slice(2),
      ...present,
    ],
    cwd: REPO_ROOT,
    stdio: ["inherit", "inherit", "inherit"],
  });
  return proc.exitCode ?? 1;
}

// Guarded so `scripts/test/lint.test.ts` can import the pure helpers above
// without spawning eslint and exiting the test process — same pattern as
// `verify-compose-defaults.ts` and `check-index-drift.ts`.
if (import.meta.main) {
  process.exit(await main());
}
