#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0

/**
 * `appstrate-connect` — one-shot OAuth helper invoked via
 * `npx @appstrate/connect <pairing-token>`.
 *
 * The pairing token is minted by the dashboard (POST /api/model-providers-oauth/pairing)
 * and surfaced to the user as a copy-paste command. The helper:
 *
 *   1. Decodes the token to recover the platform URL + providerId
 *   2. Runs the loopback OAuth dance against Codex / Claude
 *   3. POSTs the resulting credentials back with the token as Bearer auth
 *
 * Stateless by design — no config files, no keychain, no persisted state.
 * The token's TTL (5 minutes server-side) bounds the helper's
 * usefulness; rerunning after expiry produces a clear 410 error.
 *
 * Exit codes:
 *   0 — success
 *   1 — generic / network / unexpected
 *   2 — bad pairing token (malformed, expired, already consumed)
 *   3 — user cancelled / OAuth flow aborted
 */

import { decodePairingToken, hashPairingSecret as _hashPairingSecret } from "./pairing-token.ts";
import {
  runLoopbackOAuth,
  PROVIDER_ID_TO_SLUG,
  DISPLAY_NAME,
  DEFAULT_LABEL,
  type ConnectProviderSlug,
} from "./loopback-oauth.ts";
import { postImport, ImportRequestError } from "./import-client.ts";
// open() is dynamically imported so the helper still runs on systems where the
// dependency fails to install (rare, but @clack/open's optional binaries can flake).
type OpenFn = (target: string) => Promise<unknown>;

interface CliArgs {
  token: string;
  label?: string;
}

function parseArgs(argv: string[]): CliArgs {
  // Skip node + script args
  const positional: string[] = [];
  const flags: Record<string, string> = {};
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "--label" && i + 1 < argv.length) {
      flags.label = argv[++i]!;
    } else if (a === "--help" || a === "-h") {
      printHelp();
      process.exit(0);
    } else if (a === "--version" || a === "-v") {
      process.stdout.write(`@appstrate/connect ${getVersion()}\n`);
      process.exit(0);
    } else if (a.startsWith("--")) {
      process.stderr.write(`Unknown flag: ${a}\n`);
      process.exit(2);
    } else {
      positional.push(a);
    }
  }
  if (positional.length === 0) {
    printHelp();
    process.exit(2);
  }
  if (positional.length > 1) {
    process.stderr.write(
      `Too many arguments. Expected one pairing token, got ${positional.length}.\n`,
    );
    process.exit(2);
  }
  const result: CliArgs = { token: positional[0]! };
  if (flags.label) result.label = flags.label;
  return result;
}

function printHelp(): void {
  process.stdout.write(
    [
      "Usage: npx @appstrate/connect <pairing-token>",
      "",
      "Connect a personal ChatGPT (Codex) or Claude (Pro/Max) subscription to an",
      "Appstrate organization. The pairing token is generated by the dashboard;",
      "this helper completes the OAuth flow and ships the resulting credentials",
      "back to the platform.",
      "",
      "Options:",
      "  --label <name>   Display name for the credential (default: provider default)",
      "  -h, --help       Show this help",
      "  -v, --version    Print version",
      "",
      "Pairing tokens expire 5 minutes after issue and are single-use.",
      "",
    ].join("\n"),
  );
}

function getVersion(): string {
  // Bundled with the helper at publish time. Falls back to "dev" in source mode.
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const pkg = require("../package.json") as { version?: string };
    return pkg.version ?? "dev";
  } catch {
    return "dev";
  }
}

function logInfo(message: string): void {
  process.stdout.write(`${message}\n`);
}

function logError(message: string): void {
  process.stderr.write(`${message}\n`);
}

async function tryOpenBrowser(url: string): Promise<void> {
  try {
    const mod = (await import("open")) as { default: OpenFn };
    await mod.default(url);
  } catch {
    // Headless / no-browser environment — user copies from stdout.
  }
}

async function main(): Promise<number> {
  const args = parseArgs(process.argv);

  let decoded: ReturnType<typeof decodePairingToken>;
  try {
    decoded = decodePairingToken(args.token);
  } catch (err) {
    logError(`✗ ${err instanceof Error ? err.message : String(err)}`);
    return 2;
  }

  const slug: ConnectProviderSlug | undefined = PROVIDER_ID_TO_SLUG[decoded.providerId];
  if (!slug) {
    logError(
      `✗ Unsupported providerId in pairing token: ${decoded.providerId}. ` +
        `Update @appstrate/connect: \`npm install -g @appstrate/connect@latest\`.`,
    );
    return 2;
  }

  const label = args.label ?? DEFAULT_LABEL[slug];

  logInfo("");
  logInfo(`  Appstrate connect — ${DISPLAY_NAME[slug]}`);
  logInfo(`  Platform: ${decoded.platformUrl}`);
  logInfo(`  Label:    ${label}`);
  logInfo("");

  let credentials;
  try {
    credentials = await runLoopbackOAuth(slug, {
      onAuth: (info) => {
        logInfo("Open the URL below in your browser to authorize:");
        logInfo("");
        logInfo(`  ${info.url}`);
        if (info.instructions) {
          logInfo("");
          logInfo(info.instructions);
        }
        logInfo("");
        logInfo("Waiting for callback…");
        void tryOpenBrowser(info.url);
      },
      onPrompt: async (prompt) => {
        // Read a single line from stdin. Used as the manual-paste fallback
        // when the loopback bind fails (corp firewalls, port already in use).
        process.stdout.write(`${prompt.message}: `);
        return await readLine();
      },
      onProgress: (message) => logInfo(message),
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (/cancel|aborted|abort/i.test(msg)) {
      logError("✗ Authorization cancelled.");
      return 3;
    }
    logError(`✗ Authorization failed: ${msg}`);
    return 1;
  }

  logInfo("");
  logInfo("Authorization received. Sending credentials to the platform…");

  try {
    const result = await postImport({
      platformUrl: decoded.platformUrl,
      bearer: decoded.raw,
      providerId: decoded.providerId,
      label,
      credentials,
    });
    logInfo("");
    logInfo(`✓ Connected.`);
    logInfo(`  Models available: ${result.availableModelIds.join(", ") || "(none)"}`);
    if (result.email) logInfo(`  Account email:    ${result.email}`);
    if (result.subscriptionType) logInfo(`  Subscription:     ${result.subscriptionType}`);
    logInfo("");
    logInfo(
      "You can close this terminal — the dashboard will pick up the connection automatically.",
    );
    return 0;
  } catch (err) {
    if (err instanceof ImportRequestError) {
      const r = err.response;
      if (r.status === 410) {
        logError(
          `✗ This pairing token has expired or already been used. Generate a new one in the dashboard.`,
        );
        return 2;
      }
      if (r.status === 409) {
        logError(`✗ This pairing token has already been consumed. Generate a new one.`);
        return 2;
      }
      logError(`✗ Platform rejected the import: ${r.code} — ${r.detail}`);
      return 1;
    }
    logError(
      `✗ Network or unexpected error while saving: ${err instanceof Error ? err.message : String(err)}`,
    );
    return 1;
  }
}

function readLine(): Promise<string> {
  return new Promise((resolve, reject) => {
    let buffer = "";
    const onData = (chunk: Buffer) => {
      const s = chunk.toString("utf-8");
      buffer += s;
      if (buffer.includes("\n")) {
        process.stdin.off("data", onData);
        process.stdin.off("error", onError);
        resolve(buffer.split("\n")[0]!.trim());
      }
    };
    const onError = (err: Error) => {
      process.stdin.off("data", onData);
      process.stdin.off("error", onError);
      reject(err);
    };
    process.stdin.on("data", onData);
    process.stdin.on("error", onError);
  });
}

void main().then((code) => process.exit(code));
