// SPDX-License-Identifier: Apache-2.0

/**
 * Crypto secret generation + `.env` materialization for the install
 * flow.
 *
 * Every install writes the same base set of Better Auth / connection
 * secrets; Docker tiers add PostgreSQL + (for Tier 3) MinIO passwords
 * on top. All values are generated with `node:crypto.randomBytes` —
 * never derived from hostname, timestamp, or env. A fresh install gets
 * fresh secrets; re-running `install` at the same directory regenerates
 * (and the caller is expected to warn about data reset).
 */

import { randomBytes } from "node:crypto";

/**
 * Supported tier identifiers. `Tier` matches the `--tier` flag values
 * and the names of the embedded `docker-compose.tier*.yml` templates.
 */
export type Tier = 0 | 1 | 2 | 3;

/**
 * `.env` entries as a plain dict so callers can render them with a
 * trivial `Object.entries().map(...).join("\n")`. We keep the type
 * `Record<string, string>` rather than a per-tier discriminated union
 * because `.env` consumers read strings all the way down and the extra
 * typing would be noise for a one-shot materialization.
 */
export type EnvVars = Record<string, string>;

/** 32 random bytes → hex (64 chars). Used for Better Auth session signing, run-token HMAC, upload signing. */
function hex32(): string {
  return randomBytes(32).toString("hex");
}

/** 32 random bytes → base64 (44 chars with padding). Used for AES-256-GCM key (CONNECTION_ENCRYPTION_KEY). */
function base64Key32(): string {
  return randomBytes(32).toString("base64");
}

/** 24 random bytes → base64url (32 chars, URL-safe). Used for DB / object-store passwords. */
function base64urlPassword24(): string {
  return randomBytes(24)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

/**
 * Build the `.env` variable set for the given tier. All tiers share
 * the core Better Auth / connection-encryption secrets; Docker tiers
 * (1/2/3) add infra passwords.
 */
export function generateEnvForTier(tier: Tier, appUrl = "http://localhost:3000"): EnvVars {
  const env: EnvVars = {
    APP_URL: appUrl,
    TRUSTED_ORIGINS: appUrl,
    BETTER_AUTH_SECRET: hex32(),
    CONNECTION_ENCRYPTION_KEY: base64Key32(),
    RUN_TOKEN_SECRET: hex32(),
    UPLOAD_SIGNING_SECRET: hex32(),
  };

  if (tier === 0) {
    // Tier 0 runs directly against PGlite + filesystem, no infra passwords needed.
    return env;
  }

  // Tiers 1/2/3: Postgres password is always required.
  env.POSTGRES_USER = "appstrate";
  env.POSTGRES_PASSWORD = base64urlPassword24();

  if (tier === 3) {
    // MinIO creds only on Tier 3.
    env.MINIO_ROOT_USER = "appstrate";
    env.MINIO_ROOT_PASSWORD = base64urlPassword24();
    env.S3_BUCKET = "appstrate";
    env.S3_REGION = "us-east-1";
  }

  return env;
}

/**
 * Render an `EnvVars` dict to a `.env` file body. Values are written
 * verbatim (no quoting) because every generator above returns URL/
 * ASCII-safe output — no whitespace, no `#`, no `"`. Keys are sorted
 * so the output is stable across invocations (easier to diff when
 * re-generating).
 */
export function renderEnvFile(env: EnvVars): string {
  const lines = Object.keys(env)
    .sort()
    .map((key) => `${key}=${env[key]}`);
  return `# Appstrate — generated by \`appstrate install\`\n# DO NOT commit this file; it contains cryptographic secrets.\n\n${lines.join("\n")}\n`;
}
